---@meta SGG_Modding-Hades2GameDef-Scripts-AudioLogic
local game = {}

---@class SGG_Modding-Hades2GameDef-Scripts-AudioLogic*AudioState

---@type SGG_Modding-Hades2GameDef-Scripts-AudioLogic*AudioState
game.AudioState = {}
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.AudioState ...

function game.StartRoomAmbience(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.StartRoomAmbience ...

function game.PlaySpeechCue(a, b, c, d, e, f, g) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PlaySpeechCue ...

function game.PauseAmbientMusic() end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PauseAmbientMusic ...

function game.AudioStateInit(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.AudioStateInit ...

function game.SetAdvancedTooltipMixing(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.SetAdvancedTooltipMixing ...

function game.GetSpeakerName(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.GetSpeakerName ...

function game.StopSecretMusicTheme(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.StopSecretMusicTheme ...

function game.PauseMusic(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PauseMusic ...

function game.StopMusicianMusic(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.StopMusicianMusic ...

function game.CheckMusicEvents(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.CheckMusicEvents ...

function game.PauseUnpauseSoundWorkaround(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PauseUnpauseSoundWorkaround ...

function game.OnLinePlayedSomething(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.OnLinePlayedSomething ...

function game.SecretMusicPlayer(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.SecretMusicPlayer ...

function game.CleanUpCurrentSpeechId(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.CleanUpCurrentSpeechId ...

function game.GetFirstCueName(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.GetFirstCueName ...

function game.SetMusicSection(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.SetMusicSection ...

function game.GetLineSource(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.GetLineSource ...

function game.SetDefaultMusicParams(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.SetDefaultMusicParams ...

function game.MusicPlayer(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.MusicPlayer ...

function game.EndMusic(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.EndMusic ...

function game.PlayRandomEligibleVoiceLines(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PlayRandomEligibleVoiceLines ...

function game.ResumeAmbientMusic() end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.ResumeAmbientMusic ...

function game.EndAmbience(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.EndAmbience ...

function game.PlaySpeechCueFromSource(a, b, c, d, e, f) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PlaySpeechCueFromSource ...

function game.IsVoiceLineEligible(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.IsVoiceLineEligible ...

function game.MusicSetTrackOffset(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.MusicSetTrackOffset ...

function game.MusicMixer(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.MusicMixer ...

function game.WaitForSpeechFinished() end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.WaitForSpeechFinished ...

function game.PlayVoiceLine(a, b, c, d, e, f) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PlayVoiceLine ...

function game.MusicPlayerEvent(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.MusicPlayerEvent ...

function game.PlayFirstEligibleVoiceLines(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PlayFirstEligibleVoiceLines ...

function game.PlayVoiceLines(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PlayVoiceLines ...

function game.MusicianMusic(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.MusicianMusic ...

function game.PlayVoiceLinesReal(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.PlayVoiceLinesReal ...

function game.DeferredAudioScripts() end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.DeferredAudioScripts ...

function game.StopSecretMusic(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.StopSecretMusic ...

function game.ResumeMusic(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-AudioLogic.ResumeMusic ...

return game