---@meta game-Scripts-BoonInfoLogic
local game = {}

function game.BoonInfoPopulateTraits(a) end
---@alias game-Scripts-BoonInfoLogic.BoonInfoPopulateTraits ...

function game.BoonInfoScreenNext(a, b) end
---@alias game-Scripts-BoonInfoLogic.BoonInfoScreenNext ...

function game.BoonInfoScreenPrevious(a, b) end
---@alias game-Scripts-BoonInfoLogic.BoonInfoScreenPrevious ...

function game.BoonInfoScreenToggleTooltips(a, b) end
---@alias game-Scripts-BoonInfoLogic.BoonInfoScreenToggleTooltips ...

function game.BoonInfoScreenUpdateTooltipToggle(a, b) end
---@alias game-Scripts-BoonInfoLogic.BoonInfoScreenUpdateTooltipToggle ...

function game.BoonInfoSort(a, b) end
---@alias game-Scripts-BoonInfoLogic.BoonInfoSort ...

function game.CloseBoonInfoScreen(a, b) end
---@alias game-Scripts-BoonInfoLogic.CloseBoonInfoScreen ...

function game.CreateBoonInfoButton(a, b, c) end
---@alias game-Scripts-BoonInfoLogic.CreateBoonInfoButton ...

function game.CreateBoonInfoButtons(a) end
---@alias game-Scripts-BoonInfoLogic.CreateBoonInfoButtons ...

function game.CreateTraitRequirementList(a, b, c, d, e) end
---@alias game-Scripts-BoonInfoLogic.CreateTraitRequirementList ...

function game.CreateTraitRequirements(a, b) end
---@alias game-Scripts-BoonInfoLogic.CreateTraitRequirements ...

function game.MouseOffBoonInfoItem(a) end
---@alias game-Scripts-BoonInfoLogic.MouseOffBoonInfoItem ...

function game.MouseOverBoonInfoItem(a) end
---@alias game-Scripts-BoonInfoLogic.MouseOverBoonInfoItem ...

function game.ShowBoonInfoScreen(a, b, c, d) end
---@alias game-Scripts-BoonInfoLogic.ShowBoonInfoScreen ...

function game.UpdateBoonInfoPageButtons(a) end
---@alias game-Scripts-BoonInfoLogic.UpdateBoonInfoPageButtons ...

return game