---@meta game-Scripts-BountyLogic
local game = {}

function game.BountyBoardScreenDisplayCategory(a, b) end
---@alias game-Scripts-BountyLogic.BountyBoardScreenDisplayCategory ...

function game.BountyBoardScreenNextCategory(a, b) end
---@alias game-Scripts-BountyLogic.BountyBoardScreenNextCategory ...

function game.BountyBoardScreenPrevCategory(a, b) end
---@alias game-Scripts-BountyLogic.BountyBoardScreenPrevCategory ...

function game.BountyBoardScreenSelectCategory(a, b) end
---@alias game-Scripts-BountyLogic.BountyBoardScreenSelectCategory ...

function game.BountyInfoBanner(a, b) end
---@alias game-Scripts-BountyLogic.BountyInfoBanner ...

function game.CheckBounties(a, b) end
---@alias game-Scripts-BountyLogic.CheckBounties ...

function game.CloseBountyBoardScreen(a, b) end
---@alias game-Scripts-BountyLogic.CloseBountyBoardScreen ...

function game.HasEligibleBounty(a, b) end
---@alias game-Scripts-BountyLogic.HasEligibleBounty ...

function game.HasUnviewedBounty(a, b) end
---@alias game-Scripts-BountyLogic.HasUnviewedBounty ...

function game.LoadActiveBountyPackages() end
---@alias game-Scripts-BountyLogic.LoadActiveBountyPackages ...

function game.MarkBountyComplete(a, b) end
---@alias game-Scripts-BountyLogic.MarkBountyComplete ...

function game.MouseOffBounty(a) end
---@alias game-Scripts-BountyLogic.MouseOffBounty ...

function game.MouseOverBounty(a) end
---@alias game-Scripts-BountyLogic.MouseOverBounty ...

function game.OpenBountyBoardScreen(a, b) end
---@alias game-Scripts-BountyLogic.OpenBountyBoardScreen ...

function game.RestorePackagedBountyGameState() end
---@alias game-Scripts-BountyLogic.RestorePackagedBountyGameState ...

function game.StartPackagedBounty(a, b) end
---@alias game-Scripts-BountyLogic.StartPackagedBounty ...

function game.UseBountyBoard(a, b) end
---@alias game-Scripts-BountyLogic.UseBountyBoard ...

return game