---@meta SGG_Modding-Hades2GameDef-Scripts-CodexLogic
local game = {}

function game.CodexOpenEntry(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexOpenEntry ...

function game.CodexScrollUp(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexScrollUp ...

function game.CanOpenCodex() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CanOpenCodex ...

function game.CodexNextChapter(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexNextChapter ...

function game.HasNewEntries() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.HasNewEntries ...

function game.EnableCodex() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.EnableCodex ...

function game.UpdateCodexContextualAction(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.UpdateCodexContextualAction ...

function game.CodexCloseEntry(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexCloseEntry ...

function game.CodexScreenCreateChapters(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexScreenCreateChapters ...

function game.CodexUpdateVisibility(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexUpdateVisibility ...

function game.CodexUpdateCursorUp(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexUpdateCursorUp ...

function game.SelectCodexEntry(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.SelectCodexEntry ...

function game.CheckCodexUnlock(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CheckCodexUnlock ...

function game.CodexCloseChapter(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexCloseChapter ...

function game.CreateGiftTrack(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CreateGiftTrack ...

function game.CodexInit() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexInit ...

function game.CalcNumCodexEntriesUnlocked() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CalcNumCodexEntriesUnlocked ...

function game.OpenCodexScreen() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.OpenCodexScreen ...

function game.HasUnlockedEntries(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.HasUnlockedEntries ...

function game.SelectNearbyUnlockedEntry() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.SelectNearbyUnlockedEntry ...

function game.CodexPrevChapter(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexPrevChapter ...

function game.CodexOpenChapter(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexOpenChapter ...

function game.CloseCodexScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CloseCodexScreen ...

function game.AttemptOpenCodexBoonInfo(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.AttemptOpenCodexBoonInfo ...

function game.CreateRelationshipBar(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CreateRelationshipBar ...

function game.InitKillCountText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.InitKillCountText ...

function game.CodexScrollDown(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexScrollDown ...

function game.OnlyBoonScreenOpen() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.OnlyBoonScreenOpen ...

function game.CodexUpdateCursorDown(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.CodexUpdateCursorDown ...

function game.HasCodexEntryBeenFound(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CodexLogic.HasCodexEntryBeenFound ...

return game