---@meta SGG_Modding-Hades2GameDef-Scripts-CombatPresentation
local game = {}

---@class SGG_Modding-Hades2GameDef-Scripts-CombatPresentation*PolymorphPresentationData

---@type SGG_Modding-Hades2GameDef-Scripts-CombatPresentation*PolymorphPresentationData
game.PolymorphPresentationData = {}
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolymorphPresentationData ...

function game.ActivateFusePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ActivateFusePresentation ...

function game.AddSimSpeedChange(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.AddSimSpeedChange ...

function game.ArmorBreakPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ArmorBreakPresentation ...

function game.ArmorDamagePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ArmorDamagePresentation ...

function game.ArmorRestoredPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ArmorRestoredPresentation ...

function game.AssistCompletePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.AssistCompletePresentation ...

function game.AssistFailedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.AssistFailedPresentation ...

function game.BlockAttackPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.BlockAttackPresentation ...

function game.BlockedDamageInvulnerablePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.BlockedDamageInvulnerablePresentation ...

function game.BossChillKillPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.BossChillKillPresentation ...

function game.BossDeathFlash(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.BossDeathFlash ...

function game.CastArmedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.CastArmedPresentation ...

function game.ChronosBattleStart(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ChronosBattleStart ...

function game.ChronosEndTimeSlowPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ChronosEndTimeSlowPresentation ...

function game.ChronosKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ChronosKillPresentation ...

function game.ChronosPostCombatReload(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ChronosPostCombatReload ...

function game.ChronosRemainsEnterTriggerPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ChronosRemainsEnterTriggerPresentation ...

function game.ChronosRemainsLeaveTriggerPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ChronosRemainsLeaveTriggerPresentation ...

function game.ChronosTimeSlowPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ChronosTimeSlowPresentation ...

function game.CleanUpShoutPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.CleanUpShoutPresentation ...

function game.ClearManaChargeIndicator(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ClearManaChargeIndicator ...

function game.ClearPoisonEffectStacks(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ClearPoisonEffectStacks ...

function game.ClearShadeWeapons() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ClearShadeWeapons ...

function game.ClearSimSpeedChanges() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ClearSimSpeedChanges ...

function game.CocoonHitPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.CocoonHitPresentation ...

function game.CrawlerMiniBossKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.CrawlerMiniBossKillPresentation ...

function game.CreateHealthBar(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.CreateHealthBar ...

function game.CreateLevelDisplay(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.CreateLevelDisplay ...

function game.DamagePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DamagePresentation ...

function game.DeferredCombatPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DeferredCombatPresentation ...

function game.DisplayDamageText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DisplayDamageText ...

function game.DoAssistPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoAssistPresentation ...

function game.DoAssistPresentationPostWeapon(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoAssistPresentationPostWeapon ...

function game.DoCameraMotion(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoCameraMotion ...

function game.DoHadesAssistPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoHadesAssistPresentation ...

function game.DoImpactSound(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoImpactSound ...

function game.DoReactionPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoReactionPresentation ...

function game.DoRumble(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoRumble ...

function game.DoubleStrikePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoubleStrikePresentation ...

function game.DoUnitArmorShake(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoUnitArmorShake ...

function game.DoUnitArmorSpark(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoUnitArmorSpark ...

function game.DoUnitHitFlash(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoUnitHitFlash ...

function game.DoUnitHitShake(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoUnitHitShake ...

function game.DoWeaponCancelEffectSimulationSlow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponCancelEffectSimulationSlow ...

function game.DoWeaponChargeRumble(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponChargeRumble ...

function game.DoWeaponFireRadialBlur(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponFireRadialBlur ...

function game.DoWeaponFireRumble(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponFireRumble ...

function game.DoWeaponFireSimulationSlow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponFireSimulationSlow ...

function game.DoWeaponHitRumble(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponHitRumble ...

function game.DoWeaponHitSimulationSlow(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponHitSimulationSlow ...

function game.DoWeaponRadialBlur(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponRadialBlur ...

function game.DoWeaponScreenshake(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponScreenshake ...

function game.DoWeaponSounds(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.DoWeaponSounds ...

function game.EchoDamagePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.EchoDamagePresentation ...

function game.EndLavaPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.EndLavaPresentation ...

function game.EquipPlayerToolPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.EquipPlayerToolPresentation ...

function game.EquipPlayerWeaponPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.EquipPlayerWeaponPresentation ...

function game.ErisFlyByPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ErisFlyByPresentation ...

function game.ErisKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ErisKillPresentation ...

function game.ErisSelfBuffApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ErisSelfBuffApply ...

function game.FadeUnitActivation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.FadeUnitActivation ...

function game.FastClearTraitFailedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.FastClearTraitFailedPresentation ...

function game.FastClearTraitStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.FastClearTraitStartPresentation ...

function game.FastClearTraitSuccessPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.FastClearTraitSuccessPresentation ...

function game.GainLastStandPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GainLastStandPresentation ...

function game.GenericBossKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GenericBossKillPresentation ...

function game.GenericDamagePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GenericDamagePresentation ...

function game.GetDamagedFx(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GetDamagedFx ...

function game.GetDamageNumberTextScale(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GetDamageNumberTextScale ...

function game.GetHideChargeDuration(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GetHideChargeDuration ...

function game.GetLowestSimSpeed(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GetLowestSimSpeed ...

function game.GetNumBossHealthBars() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GetNumBossHealthBars ...

function game.GetPlayerDamageNumberTextScale(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GetPlayerDamageNumberTextScale ...

function game.GhostWallCollidePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.GhostWallCollidePresentation ...

function game.HandleManaChargeIndicator(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HandleManaChargeIndicator ...

function game.HealthTickDecrementPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HealthTickDecrementPresentation ...

function game.HecateBattleStart(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HecateBattleStart ...

function game.HecateCloneHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HecateCloneHitPresentation ...

function game.HecateKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HecateKillPresentation ...

function game.HeraManaRestorePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HeraManaRestorePresentation ...

function game.HeroRootApplyPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HeroRootApplyPresentation ...

function game.HeroRootClearPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HeroRootClearPresentation ...

function game.HighHealthCombatTextPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HighHealthCombatTextPresentation ...

function game.HighlightPlayerToolPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HighlightPlayerToolPresentation ...

function game.HitByMiasmaPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HitByMiasmaPresentation ...

function game.HitBySmokeTrapWeaponPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HitBySmokeTrapWeaponPresentation ...

function game.HitInvulnerablePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HitInvulnerablePresentation ...

function game.HuntersMarkApplyPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HuntersMarkApplyPresentation ...

function game.HuntersMarkUnitDeathPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.HuntersMarkUnitDeathPresentation ...

function game.InCombatText(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InCombatText ...

function game.InCombatTextArgs(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InCombatTextArgs ...

function game.InCombatTextEvent(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InCombatTextEvent ...

function game.IndestructibleObstacleHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.IndestructibleObstacleHitPresentation ...

function game.InfestedCerberusHorribleRaceConditionForTempPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InfestedCerberusHorribleRaceConditionForTempPresentation ...

function game.InfestedCerberusKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InfestedCerberusKillPresentation ...

function game.InvisBreakPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InvisBreakPresentation ...

function game.InvulnerabilityFramePresentationEnd(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InvulnerabilityFramePresentationEnd ...

function game.InvulnerabilityFramePresentationStart(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.InvulnerabilityFramePresentationStart ...

function game.IsCancelSimEffectAllowed(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.IsCancelSimEffectAllowed ...

function game.KillPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.KillPresentation ...

function game.LastAttackHold(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.LastAttackHold ...

function game.LastKillPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.LastKillPresentation ...

function game.LastKillVulnerable() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.LastKillVulnerable ...

function game.LostLastStandPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.LostLastStandPresentation ...

function game.LowHealthCombatTextPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.LowHealthCombatTextPresentation ...

function game.MiasmaClearedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.MiasmaClearedPresentation ...

function game.OnHitShakePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.OnHitShakePresentation ...

function game.OnInvisStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.OnInvisStartPresentation ...

function game.ParryAttackPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ParryAttackPresentation ...

function game.PerfectClearObjectiveFailedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PerfectClearObjectiveFailedPresentation ...

function game.PerfectClearTraitFailedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PerfectClearTraitFailedPresentation ...

function game.PerfectClearTraitStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PerfectClearTraitStartPresentation ...

function game.PerfectClearTraitSuccessPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PerfectClearTraitSuccessPresentation ...

function game.PerfectDashEndPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PerfectDashEndPresentation ...

function game.PerfectDashStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PerfectDashStartPresentation ...

function game.PlayerBlockDeathVoicelines(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerBlockDeathVoicelines ...

function game.PlayerDodgePresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerDodgePresentation ...

function game.PlayerLastStandHealingPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandHealingPresentation ...

function game.PlayerLastStandHealingText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandHealingText ...

function game.PlayerLastStandManaGainText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandManaGainText ...

function game.PlayerLastStandPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandPresentationEnd ...

function game.PlayerLastStandPresentationStart(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandPresentationStart ...

function game.PlayerLastStandProcText() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandProcText ...

function game.PlayerLastStandSFX() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandSFX ...

function game.PlayerLastStandVoicelines(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PlayerLastStandVoicelines ...

function game.PolymorphApplyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolymorphApplyPresentation ...

function game.PolymorphClearPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolymorphClearPresentation ...

function game.PolymorphSimSlow() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolymorphSimSlow ...

function game.PolyphemusBoulderIncomingPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolyphemusBoulderIncomingPresentation ...

function game.PolyphemusGrabOngoingPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolyphemusGrabOngoingPresentation ...

function game.PolyphemusInterruptWeaponPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolyphemusInterruptWeaponPresentation ...

function game.PolyphemusPlayerGrabApplyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolyphemusPlayerGrabApplyPresentation ...

function game.PolyphemusPlayerGrabClearPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PolyphemusPlayerGrabClearPresentation ...

function game.PostActivatFusePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PostActivatFusePresentation ...

function game.PostEnemyKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PostEnemyKillPresentation ...

function game.PostFuseRevivePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PostFuseRevivePresentation ...

function game.PreSpawnFx(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PreSpawnFx ...

function game.PulseCombatText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.PulseCombatText ...

function game.RecreateEffectVfx(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.RecreateEffectVfx ...

function game.RemoveEnemyHealthBar(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.RemoveEnemyHealthBar ...

function game.RemoveEnemyUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.RemoveEnemyUI ...

function game.RemoveHitShieldPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.RemoveHitShieldPresentation ...

function game.RemoveSimSpeedChange(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.RemoveSimSpeedChange ...

function game.RestoreSirenMusic(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.RestoreSirenMusic ...

function game.RevulnerablePlayerAfterShout() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.RevulnerablePlayerAfterShout ...

function game.ScreamerDistortionEffect(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ScreamerDistortionEffect ...

function game.ScyllaKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ScyllaKillPresentation ...

function game.ScyllaSpotlightPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ScyllaSpotlightPresentation ...

function game.ShadeBlockPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ShadeBlockPresentation ...

function game.ShouldIncreasePlayerHitPause(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.ShouldIncreasePlayerHitPause ...

function game.SirenKillPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SirenKillPresentation ...

function game.SirenKillScreenEffects(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SirenKillScreenEffects ...

function game.SoloSirenDrummer(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SoloSirenDrummer ...

function game.SoloSirenKeytarist(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SoloSirenKeytarist ...

function game.SoloSirenVocalist(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SoloSirenVocalist ...

function game.SpawnKillPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SpawnKillPresentation ...

function game.SpecialHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SpecialHitPresentation ...

function game.SpellChargeEndTimeSlowPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SpellChargeEndTimeSlowPresentation ...

function game.SpellChargeTimeSlowPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SpellChargeTimeSlowPresentation ...

function game.SpellChargeTimeSlowPresentationSoftVignette() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.SpellChargeTimeSlowPresentationSoftVignette ...

function game.StartBlockDeathPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.StartBlockDeathPresentation ...

function game.StartLavaPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.StartLavaPresentation ...

function game.StartWavePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.StartWavePresentation ...

function game.StopWeaponSounds(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.StopWeaponSounds ...

function game.TickBlockDeathPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.TickBlockDeathPresentation ...

function game.TintUnitActivation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.TintUnitActivation ...

function game.UnblockableAttackPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UnblockableAttackPresentation ...

function game.UnitActivatePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UnitActivatePresentation ...

function game.UnitInvulnerableHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UnitInvulnerableHitPresentation ...

function game.UnusedWeaponBonusPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UnusedWeaponBonusPresentation ...

function game.UpdateBossHealthBarFalloff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateBossHealthBarFalloff ...

function game.UpdateEnemyHealthBarFalloff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateEnemyHealthBarFalloff ...

function game.UpdateGroupHealthBarFalloff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateGroupHealthBarFalloff ...

function game.UpdateGroupHealthBarReal(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateGroupHealthBarReal ...

function game.UpdateHealthBar(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateHealthBar ...

function game.UpdateHealthBarIcons(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateHealthBarIcons ...

function game.UpdateHealthBarReal(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateHealthBarReal ...

function game.UpdatePoisonEffectStacks(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdatePoisonEffectStacks ...

function game.UpdateSimulationSpeed(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.UpdateSimulationSpeed ...

function game.VictimDeathHold(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.VictimDeathHold ...

function game.WallHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.WallHitPresentation ...

function game.WebSlowedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.WebSlowedPresentation ...

function game.WheatHit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatPresentation.WheatHit ...

return game