---@meta SGG_Modding-Hades2GameDef-Scripts-CombatLogic
local game = {}

function game.ActivateFuse(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ActivateFuse ...

function game.ActivateLuciferFuse(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ActivateLuciferFuse ...

function game.ActivateManaReserveInvulnerability(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ActivateManaReserveInvulnerability ...

function game.AddEnemyHitShield(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddEnemyHitShield ...

function game.AddIncomingDamageModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddIncomingDamageModifier ...

function game.AddLastStand(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddLastStand ...

function game.AddOnDamagedFunction(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddOnDamagedFunction ...

function game.AddOutgoingCritModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddOutgoingCritModifier ...

function game.AddOutgoingDamageModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddOutgoingDamageModifier ...

function game.AddOutgoingLifestealModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddOutgoingLifestealModifier ...

function game.AddPlaceholderEnemyCount() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddPlaceholderEnemyCount ...

function game.AddPlayerImmuneToForce(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AddPlayerImmuneToForce ...

function game.AggroSpawns(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AggroSpawns ...

function game.AIHealthThresholdReached(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.AIHealthThresholdReached ...

function game.CalcEasyModeMultiplier(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CalcEasyModeMultiplier ...

function game.CalculateBaseDamageAdditions(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CalculateBaseDamageAdditions ...

function game.CalculateCritChance(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CalculateCritChance ...

function game.CalculateDamageAdditions(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CalculateDamageAdditions ...

function game.CalculateDamageMultipliers(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CalculateDamageMultipliers ...

function game.CalculateLifestealModifiers(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CalculateLifestealModifiers ...

function game.CheckDashOverride(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CheckDashOverride ...

function game.CheckImpactReaction(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CheckImpactReaction ...

function game.CheckInvulnerabilityFrameTrigger(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CheckInvulnerabilityFrameTrigger ...

function game.CheckLastStand(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CheckLastStand ...

function game.CheckOnKillWeaponUpgrades(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CheckOnKillWeaponUpgrades ...

function game.CheckSkyDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CheckSkyDeath ...

function game.CheckUnitInvulnerableHit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CheckUnitInvulnerableHit ...

function game.CleanupEnemies(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CleanupEnemies ...

function game.CleanupEnemy(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.CleanupEnemy ...

function game.ClearGameplayElapsedTimeMultipliers() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ClearGameplayElapsedTimeMultipliers ...

function game.Damage(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.Damage ...

function game.DamageEnemy(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DamageEnemy ...

function game.DamageHero(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DamageHero ...

function game.DelayedKill(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DelayedKill ...

function game.DestroyOnDelay(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DestroyOnDelay ...

function game.DisableAllyUnits() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DisableAllyUnits ...

function game.DoEnemyHealthBufferDeplete(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DoEnemyHealthBufferDeplete ...

function game.DoEnemyHealthBuffered(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DoEnemyHealthBuffered ...

function game.DoReaction(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DoReaction ...

function game.DropHealth(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.DropHealth ...

function game.EndWeaponSlowMotion(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.EndWeaponSlowMotion ...

function game.EquipPlayerWeapon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.EquipPlayerWeapon ...

function game.FirstHealHitSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.FirstHealHitSetup ...

function game.FizzleOldSpawn(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.FizzleOldSpawn ...

function game.FreezeEscape(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.FreezeEscape ...

function game.FuseSpawns(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.FuseSpawns ...

function game.GameplaySetElapsedTimeMultiplier(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GameplaySetElapsedTimeMultiplier ...

function game.GetGameplayElapsedTimeMultiplier() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GetGameplayElapsedTimeMultiplier ...

function game.GetNumLastStands(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GetNumLastStands ...

function game.GetOutgoingDamageModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GetOutgoingDamageModifier ...

function game.GetPlayerAngle() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GetPlayerAngle ...

function game.GetPlayerGameplayElapsedTimeMultiplier() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GetPlayerGameplayElapsedTimeMultiplier ...

function game.GetProjectileData(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GetProjectileData ...

function game.GetWeaponData(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.GetWeaponData ...

function game.HandleDeathWeapon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.HandleDeathWeapon ...

function game.HasEffectWithEffectGroup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.HasEffectWithEffectGroup ...

function game.HasIncomingDamageModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.HasIncomingDamageModifier ...

function game.HasLastStand(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.HasLastStand ...

function game.HasVulnerabilityGenusEffect(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.HasVulnerabilityGenusEffect ...

function game.Heal(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.Heal ...

function game.HitByFreezeWeapon(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.HitByFreezeWeapon ...

function game.IsOnlyInvulnerableSource(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.IsOnlyInvulnerableSource ...

function game.IsPlayerInterruptible() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.IsPlayerInterruptible ...

function game.Kill(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.Kill ...

function game.KillEnemy(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.KillEnemy ...

function game.ManualReload(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ManualReload ...

function game.OnShadeMercActivate() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.OnShadeMercActivate ...

function game.PlayerLastStandHeal(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.PlayerLastStandHeal ...

function game.ProcessHealthBuffer(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ProcessHealthBuffer ...

function game.ProjectileSpawnUnitOnDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ProjectileSpawnUnitOnDeath ...

function game.QueueOnHitVoiceLines(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.QueueOnHitVoiceLines ...

function game.RecordSpeedModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RecordSpeedModifier ...

function game.RemoveIncomingDamageModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RemoveIncomingDamageModifier ...

function game.RemoveLastStand(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RemoveLastStand ...

function game.RemoveOnDamagedFunction(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RemoveOnDamagedFunction ...

function game.RemoveOutgoingCritModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RemoveOutgoingCritModifier ...

function game.RemoveOutgoingDamageModifier(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RemoveOutgoingDamageModifier ...

function game.RemovePlayerImmuneToForce(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RemovePlayerImmuneToForce ...

function game.RespawnVictim(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.RespawnVictim ...

function game.ScaleToHealthPercentage(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.ScaleToHealthPercentage ...

function game.SelfDestruct(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SelfDestruct ...

function game.SetPlayerInterruptible(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetPlayerInterruptible ...

function game.SetPlayerInvulnerable(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetPlayerInvulnerable ...

function game.SetPlayerNotStopsProjectiles(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetPlayerNotStopsProjectiles ...

function game.SetPlayerStopsProjectiles(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetPlayerStopsProjectiles ...

function game.SetPlayerUninterruptible(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetPlayerUninterruptible ...

function game.SetPlayerVulnerable(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetPlayerVulnerable ...

function game.SetUnitInvulnerable(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetUnitInvulnerable ...

function game.SetUnitVulnerable(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SetUnitVulnerable ...

function game.SkellyDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SkellyDeath ...

function game.SlingshotRepulse(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SlingshotRepulse ...

function game.SpawnImpactReactionObstacle(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SpawnImpactReactionObstacle ...

function game.SpawnImpactReactionObstacles(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SpawnImpactReactionObstacles ...

function game.SpawnObstacleOnProjectileDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SpawnObstacleOnProjectileDeath ...

function game.SpawnObstaclesOnDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SpawnObstaclesOnDeath ...

function game.SpreadBrushFire(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.SpreadBrushFire ...

function game.StartWeaponSlowMotion(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.StartWeaponSlowMotion ...

function game.UnitDeathCheckRoomExitsReady() end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.UnitDeathCheckRoomExitsReady ...

function game.VulnerableAfterDelay(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.VulnerableAfterDelay ...

function game.WipeSpawnsOnKill(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-CombatLogic.WipeSpawnsOnKill ...

return game