---@meta game-Scripts-CosmeticsLogic
local game = {}

function game.ActivateConditionalItem(a, b) end
---@alias game-Scripts-CosmeticsLogic.ActivateConditionalItem ...

function game.ActivateConditionalItems(a, b) end
---@alias game-Scripts-CosmeticsLogic.ActivateConditionalItems ...

function game.CosmeticShopDisplayCategory(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopDisplayCategory ...

function game.CosmeticShopNextCategory(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopNextCategory ...

function game.CosmeticShopPrevCategory(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopPrevCategory ...

function game.CosmeticShopSelectCategory(a, b) end
---@alias game-Scripts-CosmeticsLogic.CosmeticShopSelectCategory ...

function game.DeactivateConditionalItem(a) end
---@alias game-Scripts-CosmeticsLogic.DeactivateConditionalItem ...

function game.DoCosmeticShopPurchase(a, b) end
---@alias game-Scripts-CosmeticsLogic.DoCosmeticShopPurchase ...

function game.DoCosmeticShopRemoval(a, b) end
---@alias game-Scripts-CosmeticsLogic.DoCosmeticShopRemoval ...

function game.HandleCosmeticShopPurchase(a, b) end
---@alias game-Scripts-CosmeticsLogic.HandleCosmeticShopPurchase ...

function game.HandleCosmeticShopRemoval(a, b) end
---@alias game-Scripts-CosmeticsLogic.HandleCosmeticShopRemoval ...

function game.OpenCosmeticsShopScreen(a, b) end
---@alias game-Scripts-CosmeticsLogic.OpenCosmeticsShopScreen ...

function game.UseCosmeticsShop(a, b) end
---@alias game-Scripts-CosmeticsLogic.UseCosmeticsShop ...

return game