---@meta game-Scripts-DeathLoopLogic
local game = {}

function game.ClearMapBlockers(a, b) end
---@alias game-Scripts-DeathLoopLogic.ClearMapBlockers ...

function game.DeathAreaRoomTransition(a, b) end
---@alias game-Scripts-DeathLoopLogic.DeathAreaRoomTransition ...

function game.DeathAreaSwitchRoom(a, b) end
---@alias game-Scripts-DeathLoopLogic.DeathAreaSwitchRoom ...

function game.KillHero(a, b) end
---@alias game-Scripts-DeathLoopLogic.KillHero ...

function game.NPCFollowPath(a, b) end
---@alias game-Scripts-DeathLoopLogic.NPCFollowPath ...

function game.NPCLittering(a, b) end
---@alias game-Scripts-DeathLoopLogic.NPCLittering ...

function game.RequestPreRunLoadoutChangeSave() end
---@alias game-Scripts-DeathLoopLogic.RequestPreRunLoadoutChangeSave ...

function game.RestoreLitter(a, b) end
---@alias game-Scripts-DeathLoopLogic.RestoreLitter ...

function game.SetupCamera(a, b) end
---@alias game-Scripts-DeathLoopLogic.SetupCamera ...

function game.SetupDynamicLitter(a, b) end
---@alias game-Scripts-DeathLoopLogic.SetupDynamicLitter ...

function game.SpawnSkelly(a) end
---@alias game-Scripts-DeathLoopLogic.SpawnSkelly ...

function game.StartDeathLoop(a) end
---@alias game-Scripts-DeathLoopLogic.StartDeathLoop ...

function game.StartOver(a) end
---@alias game-Scripts-DeathLoopLogic.StartOver ...

function game.UnlockDeathAreaInteractables() end
---@alias game-Scripts-DeathLoopLogic.UnlockDeathAreaInteractables ...

function game.UpdateAffordabilityStatus() end
---@alias game-Scripts-DeathLoopLogic.UpdateAffordabilityStatus ...

function game.UseEscapeDoor(a, b) end
---@alias game-Scripts-DeathLoopLogic.UseEscapeDoor ...

function game.UseTrashPoint(a, b, c) end
---@alias game-Scripts-DeathLoopLogic.UseTrashPoint ...

return game