---@meta game-Scripts-Debug
local game = {}

---@class game-Scripts-Debug*DebugState

---@type game-Scripts-Debug*DebugState
game.DebugState = {}
---@alias game-Scripts-Debug.DebugState ...

---@class game-Scripts-Debug*HotLoadInfo

---@type game-Scripts-Debug*HotLoadInfo
game.HotLoadInfo = {}
---@alias game-Scripts-Debug.HotLoadInfo ...

---@class game-Scripts-Debug*UserDebugEquip

---@type game-Scripts-Debug*UserDebugEquip
game.UserDebugEquip = {}
---@alias game-Scripts-Debug.UserDebugEquip ...

function game.AnimateOnDistance(a, b) end
---@alias game-Scripts-Debug.AnimateOnDistance ...

function game.AnimateOutsideDistance(a, b) end
---@alias game-Scripts-Debug.AnimateOutsideDistance ...

function game.AnimTest1(a, b, c) end
---@alias game-Scripts-Debug.AnimTest1 ...

function game.AnimTest2(a, b, c) end
---@alias game-Scripts-Debug.AnimTest2 ...

function game.AnimTest3(a, b, c) end
---@alias game-Scripts-Debug.AnimTest3 ...

function game.AutoPlayOff() end
---@alias game-Scripts-Debug.AutoPlayOff ...

function game.AutoPlayOn() end
---@alias game-Scripts-Debug.AutoPlayOn ...

function game.CreateDebugEnemySpawnPage(a, b) end
---@alias game-Scripts-Debug.CreateDebugEnemySpawnPage ...

function game.CreateDevSaveName(a, b) end
---@alias game-Scripts-Debug.CreateDevSaveName ...

function game.CreateNPCSpawnButtons(a, b) end
---@alias game-Scripts-Debug.CreateNPCSpawnButtons ...

function game.DebugBiomeSpawnButton(a, b) end
---@alias game-Scripts-Debug.DebugBiomeSpawnButton ...

function game.DebugConversationMouseOff(a) end
---@alias game-Scripts-Debug.DebugConversationMouseOff ...

function game.DebugConversationMouseOver(a) end
---@alias game-Scripts-Debug.DebugConversationMouseOver ...

function game.DebugConversationsEnemyButton(a, b) end
---@alias game-Scripts-Debug.DebugConversationsEnemyButton ...

function game.DebugConversationsTextLinesButton(a, b) end
---@alias game-Scripts-Debug.DebugConversationsTextLinesButton ...

function game.DebugEnemySpawnButton(a, b) end
---@alias game-Scripts-Debug.DebugEnemySpawnButton ...

function game.DebugEnemySpawnPageButton(a, b) end
---@alias game-Scripts-Debug.DebugEnemySpawnPageButton ...

function game.DebugNPCSpawn(a, b, c) end
---@alias game-Scripts-Debug.DebugNPCSpawn ...

function game.DebugPrintf(a) end
---@alias game-Scripts-Debug.DebugPrintf ...

function game.DebugPrintTable(a, b, c) end
---@alias game-Scripts-Debug.DebugPrintTable ...

function game.DebugSetupHarvestPointAnims() end
---@alias game-Scripts-Debug.DebugSetupHarvestPointAnims ...

function game.DebugSpawnConsumables(a, b) end
---@alias game-Scripts-Debug.DebugSpawnConsumables ...

function game.DebugSpawnEnemy(a, b) end
---@alias game-Scripts-Debug.DebugSpawnEnemy ...

function game.DebugUnlockMetaUpgrades(a, b) end
---@alias game-Scripts-Debug.DebugUnlockMetaUpgrades ...

function game.DebugWriteCsvRow(a, b) end
---@alias game-Scripts-Debug.DebugWriteCsvRow ...

function game.DebugWriteLine(a, b) end
---@alias game-Scripts-Debug.DebugWriteLine ...

function game.DpsSort(a, b) end
---@alias game-Scripts-Debug.DpsSort ...

function game.DumpGameStateStats() end
---@alias game-Scripts-Debug.DumpGameStateStats ...

function game.DumpGameStateToFile() end
---@alias game-Scripts-Debug.DumpGameStateToFile ...

function game.DumpRunHistoryStats() end
---@alias game-Scripts-Debug.DumpRunHistoryStats ...

function game.DumpRunStats(a, b, c) end
---@alias game-Scripts-Debug.DumpRunStats ...

function game.DumpTableInfo(a) end
---@alias game-Scripts-Debug.DumpTableInfo ...

function game.EditingModeOff() end
---@alias game-Scripts-Debug.EditingModeOff ...

function game.EditingModeOn() end
---@alias game-Scripts-Debug.EditingModeOn ...

function game.EquipTestWeapon(a, b, c) end
---@alias game-Scripts-Debug.EquipTestWeapon ...

function game.GetRewardsOffered(a, b, c) end
---@alias game-Scripts-Debug.GetRewardsOffered ...

function game.GetRewardsTaken(a, b) end
---@alias game-Scripts-Debug.GetRewardsTaken ...

function game.LiveFillInShopOptions() end
---@alias game-Scripts-Debug.LiveFillInShopOptions ...

function game.OnHotLoadLua(a) end
---@alias game-Scripts-Debug.OnHotLoadLua ...

function game.OnHotLoadXML() end
---@alias game-Scripts-Debug.OnHotLoadXML ...

function game.OpenDebugConversationScreen() end
---@alias game-Scripts-Debug.OpenDebugConversationScreen ...

function game.OpenDebugEnemySpawnScreen() end
---@alias game-Scripts-Debug.OpenDebugEnemySpawnScreen ...

function game.PostHotloadXML() end
---@alias game-Scripts-Debug.PostHotloadXML ...

function game.ReloadAllTraits() end
---@alias game-Scripts-Debug.ReloadAllTraits ...

function game.SafeModeOff() end
---@alias game-Scripts-Debug.SafeModeOff ...

function game.SafeModeOn() end
---@alias game-Scripts-Debug.SafeModeOn ...

function game.SetupDebugConversationsTextLinesButton(a, b, c, d, e) end
---@alias game-Scripts-Debug.SetupDebugConversationsTextLinesButton ...

function game.SetupTestWeaponKit(a, b) end
---@alias game-Scripts-Debug.SetupTestWeaponKit ...

function game.ToggleConfigOption(a) end
---@alias game-Scripts-Debug.ToggleConfigOption ...

function game.ToggleDebugEnemySpawnAtHero(a, b) end
---@alias game-Scripts-Debug.ToggleDebugEnemySpawnAtHero ...

function game.ToggleDebugEnemySpawnIdle(a, b) end
---@alias game-Scripts-Debug.ToggleDebugEnemySpawnIdle ...

function game.UnlockAllWeapons(a, b) end
---@alias game-Scripts-Debug.UnlockAllWeapons ...

function game.UnlockElementalIcons() end
---@alias game-Scripts-Debug.UnlockElementalIcons ...

function game.UnlockEntireCodex() end
---@alias game-Scripts-Debug.UnlockEntireCodex ...

return game