---@meta SGG_Modding-Hades2GameDef-Scripts-EffectLogic
local game = {}

function game.AddLobWeaponLockLayer(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.AddLobWeaponLockLayer ...

function game.BurnEffectApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.BurnEffectApply ...

function game.CheckSprintBlitz(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.CheckSprintBlitz ...

function game.CheckStunAnimation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.CheckStunAnimation ...

function game.CheckTriggerAllDamageEcho(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.CheckTriggerAllDamageEcho ...

function game.ClearCastApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.ClearCastApply ...

function game.ClearCastClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.ClearCastClear ...

function game.DamageEchoApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.DamageEchoApply ...

function game.DamageEchoClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.DamageEchoClear ...

function game.DamageEchoProcess(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.DamageEchoProcess ...

function game.DamageEchoTrigger(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.DamageEchoTrigger ...

function game.DamageShareApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.DamageShareApply ...

function game.DamageShareClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.DamageShareClear ...

function game.DelayedKnockbackEffectApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.DelayedKnockbackEffectApply ...

function game.GetExistingAnimationPriority(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.GetExistingAnimationPriority ...

function game.HandleBurnStacks(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.HandleBurnStacks ...

function game.HandleBurnTicks(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.HandleBurnTicks ...

function game.HecatePolymorphApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.HecatePolymorphApply ...

function game.HecatePolymorphClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.HecatePolymorphClear ...

function game.HecatePolymorphEquipWeapons() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.HecatePolymorphEquipWeapons ...

function game.HecatePolymorphUnequipWeapons() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.HecatePolymorphUnequipWeapons ...

function game.LobDisableTriggerLockApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.LobDisableTriggerLockApply ...

function game.LobDisableTriggerLockClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.LobDisableTriggerLockClear ...

function game.MiasmaSlowApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.MiasmaSlowApply ...

function game.MiasmaSlowClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.MiasmaSlowClear ...

function game.OmegaBuffApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.OmegaBuffApply ...

function game.OmegaBuffClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.OmegaBuffClear ...

function game.PlayerSprintPhasingApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.PlayerSprintPhasingApply ...

function game.PlayerSprintPhasingClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.PlayerSprintPhasingClear ...

function game.PolyphemusPlayerGrabApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.PolyphemusPlayerGrabApply ...

function game.PolyphemusPlayerGrabClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.PolyphemusPlayerGrabClear ...

function game.ProcessDamageShare(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.ProcessDamageShare ...

function game.PulseUnitColor(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.PulseUnitColor ...

function game.RemoveEffectBlockOnDelay(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.RemoveEffectBlockOnDelay ...

function game.RemoveLobWeaponLockLayer(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.RemoveLobWeaponLockLayer ...

function game.RootedApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.RootedApply ...

function game.RootedClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.RootedClear ...

function game.SelfEmpowerApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.SelfEmpowerApply ...

function game.SelfEmpowerClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.SelfEmpowerClear ...

function game.StaffSelfBuffApplicatorApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.StaffSelfBuffApplicatorApply ...

function game.StaffSelfBuffApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.StaffSelfBuffApply ...

function game.StaffSelfBuffClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.StaffSelfBuffClear ...

function game.ZeusRepeatedStun(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EffectLogic.ZeusRepeatedStun ...

return game