---@meta SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late
local game = {}

function game.CapturePointEncounterEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.CapturePointEncounterEndPresentation ...

function game.CapturePointEncounterStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.CapturePointEncounterStartPresentation ...

function game.ChronosPhaseTransition(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.ChronosPhaseTransition ...

function game.DevotionTestPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.DevotionTestPresentation ...

function game.FieldsEncounterActivatedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.FieldsEncounterActivatedPresentation ...

function game.FieldsEncounterStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.FieldsEncounterStartPresentation ...

function game.FloodEncounterStartEndAudio() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.FloodEncounterStartEndAudio ...

function game.FloodEncounterStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.FloodEncounterStartPresentation ...

function game.FloodTrapFireEndPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.FloodTrapFireEndPresentation ...

function game.FloodTrapFireStartPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.FloodTrapFireStartPresentation ...

function game.HadesVoicelineBlur(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HadesVoicelineBlur ...

function game.HandleWrapping(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HandleWrapping ...

function game.HeraclesEncounterEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeraclesEncounterEndPresentation ...

function game.HeraclesEncounterStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeraclesEncounterStartPresentation ...

function game.HeraclesExit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeraclesExit ...

function game.HeraclesObjectiveResultPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeraclesObjectiveResultPresentation ...

function game.HeraclesPreSpawnPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeraclesPreSpawnPresentation ...

function game.HeraclesRequiredKillPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeraclesRequiredKillPresentation ...

function game.HeraclesSpawnPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeraclesSpawnPresentation ...

function game.HeroicStandPulse(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.HeroicStandPulse ...

function game.IcarusAppearancePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.IcarusAppearancePresentation ...

function game.IcarusExitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.IcarusExitPresentation ...

function game.IcarusPreSpawnPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.IcarusPreSpawnPresentation ...

function game.InfestedCerberusSetupPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.InfestedCerberusSetupPresentation ...

function game.InfestedCerberusSpawnPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.InfestedCerberusSpawnPresentation ...

function game.InvasionEncounterStartPresentation(a, b, c, d, e, f) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.InvasionEncounterStartPresentation ...

function game.MedeaMusicManager(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.MedeaMusicManager ...

function game.NemesisBetPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisBetPresentation ...

function game.NemesisEncounterEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisEncounterEndPresentation ...

function game.NemesisEncounterStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisEncounterStartPresentation ...

function game.NemesisFieldsApproachPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisFieldsApproachPresentation ...

function game.NemesisFieldsBackAwayFromPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisFieldsBackAwayFromPresentation ...

function game.NemesisPostFieldsCombatCheckExits(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisPostFieldsCombatCheckExits ...

function game.NemesisPostTradeCheckExits(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisPostTradeCheckExits ...

function game.NemesisSpawnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisSpawnPresentation ...

function game.NemesisSpawnPresentationFields(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisSpawnPresentationFields ...

function game.NemesisTeleportExitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisTeleportExitPresentation ...

function game.NemesisThemePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.NemesisThemePresentation ...

function game.ScyllaBoostEndPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.ScyllaBoostEndPresentation ...

function game.ScyllaBoostPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.ScyllaBoostPresentation ...

function game.SurvivalEncounterStartPresentation(a, b, c, d, e, f) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.SurvivalEncounterStartPresentation ...

function game.SurvivalObjectivePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.SurvivalObjectivePresentation ...

function game.SurvivalTollPulse() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.SurvivalTollPulse ...

function game.WrapObstacle(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.WrapObstacle ...

function game.WrappingEncounterEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.WrappingEncounterEndPresentation ...

function game.WrappingEncounterStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation_Late.WrappingEncounterStartPresentation ...

return game