---@meta SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation
local game = {}

function game.AngleNPCToHero(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.AngleNPCToHero ...

function game.ArachneCombatDrumCheck(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ArachneCombatDrumCheck ...

function game.ArachneRewardFoundPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ArachneRewardFoundPresentation ...

function game.ArtemisAppearancePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ArtemisAppearancePresentation ...

function game.ArtemisExitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ArtemisExitPresentation ...

function game.ArtemisFirstAppearancePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ArtemisFirstAppearancePresentation ...

function game.ArtemisPreSpawnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ArtemisPreSpawnPresentation ...

function game.ChallengeEncounterEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ChallengeEncounterEndPresentation ...

function game.ChallengeEncounterStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ChallengeEncounterStartPresentation ...

function game.CrowdReactionPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.CrowdReactionPresentation ...

function game.CrowdReactionPresentationEventSource(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.CrowdReactionPresentationEventSource ...

function game.DoHadesSpeakingPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.DoHadesSpeakingPresentation ...

function game.EncounterEndPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.EncounterEndPresentation ...

function game.ExtraDoorEncounterStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ExtraDoorEncounterStartPresentation ...

function game.HadesSpeakingPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.HadesSpeakingPresentation ...

function game.MoveHeroToArtemisFrontAngle(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.MoveHeroToArtemisFrontAngle ...

function game.MoveHeroToNPCFrontAngle(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.MoveHeroToNPCFrontAngle ...

function game.PerfectClearEncounterEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.PerfectClearEncounterEndPresentation ...

function game.PerfectClearEncounterStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.PerfectClearEncounterStartPresentation ...

function game.SetHeroAngleWithMoveOrder(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.SetHeroAngleWithMoveOrder ...

function game.ShoppingFailedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ShoppingFailedPresentation ...

function game.ShoppingFidgetPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ShoppingFidgetPresentation ...

function game.ShoppingSuccessItemPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ShoppingSuccessItemPresentation ...

function game.ShoppingSuccessNemesisPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ShoppingSuccessNemesisPresentation ...

function game.ShoppingSuccessPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.ShoppingSuccessPresentation ...

function game.TrackTimeChallengeProgress(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterPresentation.TrackTimeChallengeProgress ...

return game