---@meta SGG_Modding-Hades2GameDef-Scripts-EncounterLogic
local game = {}

function game.ActivateNemesisPostRandomEventCombat(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.ActivateNemesisPostRandomEventCombat ...

function game.AddEncounterLayer(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.AddEncounterLayer ...

function game.ApplyScyllaFightSpotlight(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.ApplyScyllaFightSpotlight ...

function game.BoatRopeSwing(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.BoatRopeSwing ...

function game.BossIntro(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.BossIntro ...

function game.BossStageTransition(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.BossStageTransition ...

function game.CalculateActiveEnemyCap(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.CalculateActiveEnemyCap ...

function game.CheckArtemisSpawn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.CheckArtemisSpawn ...

function game.CheckForAllEnemiesDead(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.CheckForAllEnemiesDead ...

function game.CheckForEncounterEnemiesDead(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.CheckForEncounterEnemiesDead ...

function game.CheckIcarusSpawn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.CheckIcarusSpawn ...

function game.ClockworkManager(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.ClockworkManager ...

function game.EncounterAudio(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.EncounterAudio ...

function game.EndCapturePointChallengeEncounter(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.EndCapturePointChallengeEncounter ...

function game.EndChallengeEncounter(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.EndChallengeEncounter ...

function game.GetActiveEnemyCount(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.GetActiveEnemyCount ...

function game.GetEncounterActiveEnemyCount(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.GetEncounterActiveEnemyCount ...

function game.HandleArtemisSpawn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleArtemisSpawn ...

function game.HandleCapturePointMovement(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleCapturePointMovement ...

function game.HandleCoverSpawns(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleCoverSpawns ...

function game.HandleEncounterPreSpawns(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleEncounterPreSpawns ...

function game.HandleEnemySpawns(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleEnemySpawns ...

function game.HandleHazardSpawns(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleHazardSpawns ...

function game.HandleHeraclesSpawn(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleHeraclesSpawn ...

function game.HandleIcarusSpawn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleIcarusSpawn ...

function game.HandleManualCapturePointStart(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleManualCapturePointStart ...

function game.HandleNemesisCombatSpawn(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleNemesisCombatSpawn ...

function game.HandleNextSpawn(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleNextSpawn ...

function game.HandleObstacleSpawns(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleObstacleSpawns ...

function game.HandleShadeWeaponSpawns(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleShadeWeaponSpawns ...

function game.HandleTimedSpawns(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleTimedSpawns ...

function game.HandleTrapChain(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleTrapChain ...

function game.HandleTrapChains(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.HandleTrapChains ...

function game.IsSpawnPointEligible(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.IsSpawnPointEligible ...

function game.NemesisTakeRoomExit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.NemesisTakeRoomExit ...

function game.OnAllEnemiesDead(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.OnAllEnemiesDead ...

function game.PostCombatAudio(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.PostCombatAudio ...

function game.RegenerateElysiumPillar(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.RegenerateElysiumPillar ...

function game.RemoveScyllaFightSpotlight(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.RemoveScyllaFightSpotlight ...

function game.RestoreEncounterObstacle(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.RestoreEncounterObstacle ...

function game.RestoreEncounterSpawn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.RestoreEncounterSpawn ...

function game.ScyllaCoverManager(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.ScyllaCoverManager ...

function game.SelectSpawnPoint(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SelectSpawnPoint ...

function game.SetupArachneCombatEncounter(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SetupArachneCombatEncounter ...

function game.SetupBoss(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SetupBoss ...

function game.SetupGroupHealthBar(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SetupGroupHealthBar ...

function game.ShouldDoLastKillPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.ShouldDoLastKillPresentation ...

function game.SimulateCombatDestruction(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SimulateCombatDestruction ...

function game.SpawnArachneCocoons(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SpawnArachneCocoons ...

function game.SpawnEnemyWeapon(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SpawnEnemyWeapon ...

function game.SpawnMovingObstacle(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SpawnMovingObstacle ...

function game.SpawnNemesisForRandomEvents(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SpawnNemesisForRandomEvents ...

function game.SpawnShipCaptainUnit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SpawnShipCaptainUnit ...

function game.SpawnUnitGroup(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.SpawnUnitGroup ...

function game.StartCapturePointEncounter(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.StartCapturePointEncounter ...

function game.StartChallengeEncounter(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.StartChallengeEncounter ...

function game.StartDevotionTest(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.StartDevotionTest ...

function game.StartFieldsEncounter(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.StartFieldsEncounter ...

function game.ToggleCover(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.ToggleCover ...

function game.TrackCapturePointChallengeProgress(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.TrackCapturePointChallengeProgress ...

function game.TrackCapturePointChallengeProgressReal(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.TrackCapturePointChallengeProgressReal ...

function game.TrackHeraclesChallengeProgress(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.TrackHeraclesChallengeProgress ...

function game.TrackNemesisChallengeProgress(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.TrackNemesisChallengeProgress ...

function game.UnoccupySpawnPoint(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.UnoccupySpawnPoint ...

function game.UnoccupySpawnPointOnDistance(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.UnoccupySpawnPointOnDistance ...

function game.WaitForArachneRewardFound(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.WaitForArachneRewardFound ...

function game.WaveStartChanges(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EncounterLogic.WaveStartChanges ...

return game