---@meta game-Scripts-EnemyAILogic
local game = {}

game.AIThreadName = "AIThread"
---@alias game-Scripts-EnemyAILogic.AIThreadName ...

function game.AggroAI(a) end
---@alias game-Scripts-EnemyAILogic.AggroAI ...

function game.AggroNearbyUnits(a, b) end
---@alias game-Scripts-EnemyAILogic.AggroNearbyUnits ...

function game.AggroUnit(a, b) end
---@alias game-Scripts-EnemyAILogic.AggroUnit ...

function game.AIFireProjectile(a, b, c) end
---@alias game-Scripts-EnemyAILogic.AIFireProjectile ...

function game.AIFireWeapon(a, b) end
---@alias game-Scripts-EnemyAILogic.AIFireWeapon ...

function game.AIWait(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.AIWait ...

function game.AllAIAttack(a, b) end
---@alias game-Scripts-EnemyAILogic.AllAIAttack ...

function game.AllAIFlee(a, b) end
---@alias game-Scripts-EnemyAILogic.AllAIFlee ...

function game.AllAIFollow(a, b) end
---@alias game-Scripts-EnemyAILogic.AllAIFollow ...

function game.AllAIStop(a, b) end
---@alias game-Scripts-EnemyAILogic.AllAIStop ...

function game.AmbientBattleAggroAI(a) end
---@alias game-Scripts-EnemyAILogic.AmbientBattleAggroAI ...

function game.ArtemisHealDrop(a, b) end
---@alias game-Scripts-EnemyAILogic.ArtemisHealDrop ...

function game.ArtemisPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.ArtemisPostCombat ...

function game.AttackAndDie(a) end
---@alias game-Scripts-EnemyAILogic.AttackAndDie ...

function game.AttackerAI(a) end
---@alias game-Scripts-EnemyAILogic.AttackerAI ...

function game.BlendInAI(a) end
---@alias game-Scripts-EnemyAILogic.BlendInAI ...

function game.CalcEnemyWait(a, b, c) end
---@alias game-Scripts-EnemyAILogic.CalcEnemyWait ...

function game.CharybdisTransition(a, b, c) end
---@alias game-Scripts-EnemyAILogic.CharybdisTransition ...

function game.CheckStun(a, b) end
---@alias game-Scripts-EnemyAILogic.CheckStun ...

function game.CheckWeaponInterrupt(a) end
---@alias game-Scripts-EnemyAILogic.CheckWeaponInterrupt ...

function game.ChooseWanderSpawnPoints(a, b) end
---@alias game-Scripts-EnemyAILogic.ChooseWanderSpawnPoints ...

function game.ChronosTimeSlow(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.ChronosTimeSlow ...

function game.ClearLootDrops(a) end
---@alias game-Scripts-EnemyAILogic.ClearLootDrops ...

function game.CollectShadeMerc(a) end
---@alias game-Scripts-EnemyAILogic.CollectShadeMerc ...

function game.CollisionRetaliateAI(a) end
---@alias game-Scripts-EnemyAILogic.CollisionRetaliateAI ...

function game.CreateTargetMarker(a, b) end
---@alias game-Scripts-EnemyAILogic.CreateTargetMarker ...

function game.DefenseAI(a) end
---@alias game-Scripts-EnemyAILogic.DefenseAI ...

function game.DestructibleTreeHit(a, b, c) end
---@alias game-Scripts-EnemyAILogic.DestructibleTreeHit ...

function game.DirectionalShatterAI(a, b, c) end
---@alias game-Scripts-EnemyAILogic.DirectionalShatterAI ...

function game.DoAttack(a, b) end
---@alias game-Scripts-EnemyAILogic.DoAttack ...

function game.DoAttackerAILoop(a, b) end
---@alias game-Scripts-EnemyAILogic.DoAttackerAILoop ...

function game.DoPickup(a, b, c) end
---@alias game-Scripts-EnemyAILogic.DoPickup ...

function game.DoWeaponFire(a, b) end
---@alias game-Scripts-EnemyAILogic.DoWeaponFire ...

function game.DumbFireAttack(a, b) end
---@alias game-Scripts-EnemyAILogic.DumbFireAttack ...

function game.EmptyAI() end
---@alias game-Scripts-EnemyAILogic.EmptyAI ...

function game.EndChronosTimeSlow(a, b) end
---@alias game-Scripts-EnemyAILogic.EndChronosTimeSlow ...

function game.EndEnemyEnrage(a) end
---@alias game-Scripts-EnemyAILogic.EndEnemyEnrage ...

function game.EndOrbitAITimer(a, b) end
---@alias game-Scripts-EnemyAILogic.EndOrbitAITimer ...

function game.EnemyHandleInvisibleAttack(a, b, c) end
---@alias game-Scripts-EnemyAILogic.EnemyHandleInvisibleAttack ...

function game.EnemyInvisibility(a, b, c) end
---@alias game-Scripts-EnemyAILogic.EnemyInvisibility ...

function game.EnrageUnit(a, b) end
---@alias game-Scripts-EnemyAILogic.EnrageUnit ...

function game.ErisOilTransition(a, b) end
---@alias game-Scripts-EnemyAILogic.ErisOilTransition ...

function game.FinishTargetMarker(a) end
---@alias game-Scripts-EnemyAILogic.FinishTargetMarker ...

function game.FireAndQuit(a) end
---@alias game-Scripts-EnemyAILogic.FireAndQuit ...

function game.FireFloodTraps(a) end
---@alias game-Scripts-EnemyAILogic.FireFloodTraps ...

function game.FloodManager(a, b) end
---@alias game-Scripts-EnemyAILogic.FloodManager ...

function game.FogAI(a) end
---@alias game-Scripts-EnemyAILogic.FogAI ...

function game.FollowAI(a, b) end
---@alias game-Scripts-EnemyAILogic.FollowAI ...

function game.GetAllAllyIds(a) end
---@alias game-Scripts-EnemyAILogic.GetAllAllyIds ...

function game.GetTargetId(a, b) end
---@alias game-Scripts-EnemyAILogic.GetTargetId ...

function game.GetWeaponAIData(a, b) end
---@alias game-Scripts-EnemyAILogic.GetWeaponAIData ...

function game.GroupAI(a) end
---@alias game-Scripts-EnemyAILogic.GroupAI ...

function game.GuardAI(a) end
---@alias game-Scripts-EnemyAILogic.GuardAI ...

function game.HandleEnemyTeleportation(a, b, c) end
---@alias game-Scripts-EnemyAILogic.HandleEnemyTeleportation ...

function game.HandleMinionWeapons(a, b) end
---@alias game-Scripts-EnemyAILogic.HandleMinionWeapons ...

function game.HandleSpawnerBurst(a, b) end
---@alias game-Scripts-EnemyAILogic.HandleSpawnerBurst ...

function game.HandleUnitDefenseApply(a) end
---@alias game-Scripts-EnemyAILogic.HandleUnitDefenseApply ...

function game.HecateStageTransition1(a, b, c) end
---@alias game-Scripts-EnemyAILogic.HecateStageTransition1 ...

function game.HecateStageTransition2(a, b, c) end
---@alias game-Scripts-EnemyAILogic.HecateStageTransition2 ...

function game.HeraclesPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.HeraclesPostCombat ...

function game.HideAndPeekAI(a) end
---@alias game-Scripts-EnemyAILogic.HideAndPeekAI ...

function game.IcarusPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.IcarusPostCombat ...

function game.IdleAI(a) end
---@alias game-Scripts-EnemyAILogic.IdleAI ...

function game.IdleAIStage(a) end
---@alias game-Scripts-EnemyAILogic.IdleAIStage ...

function game.IsAIActive(a) end
---@alias game-Scripts-EnemyAILogic.IsAIActive ...

function game.IsEnemyProjectileEligible(a, b) end
---@alias game-Scripts-EnemyAILogic.IsEnemyProjectileEligible ...

function game.IsEnemyWeaponEligible(a, b, c) end
---@alias game-Scripts-EnemyAILogic.IsEnemyWeaponEligible ...

function game.IsEnemyWeaponForced(a, b) end
---@alias game-Scripts-EnemyAILogic.IsEnemyWeaponForced ...

function game.IsLocationBlockedWithinDistance(a, b) end
---@alias game-Scripts-EnemyAILogic.IsLocationBlockedWithinDistance ...

function game.LayDrop(a, b) end
---@alias game-Scripts-EnemyAILogic.LayDrop ...

function game.Leap(a, b, c) end
---@alias game-Scripts-EnemyAILogic.Leap ...

function game.LeapIntoRangeAI(a, b) end
---@alias game-Scripts-EnemyAILogic.LeapIntoRangeAI ...

function game.MineAI(a) end
---@alias game-Scripts-EnemyAILogic.MineAI ...

function game.MinionFollowAI(a) end
---@alias game-Scripts-EnemyAILogic.MinionFollowAI ...

function game.MoveToRandomLocation(a, b, c, d, e) end
---@alias game-Scripts-EnemyAILogic.MoveToRandomLocation ...

function game.MoveWithinRange(a, b, c) end
---@alias game-Scripts-EnemyAILogic.MoveWithinRange ...

function game.NemesisPostCombat(a) end
---@alias game-Scripts-EnemyAILogic.NemesisPostCombat ...

function game.NumAttacksSinceWeapon(a, b) end
---@alias game-Scripts-EnemyAILogic.NumAttacksSinceWeapon ...

function game.NumConsecutiveUses(a, b) end
---@alias game-Scripts-EnemyAILogic.NumConsecutiveUses ...

function game.OilPuddleOnHit(a, b) end
---@alias game-Scripts-EnemyAILogic.OilPuddleOnHit ...

function game.OnUseBallista(a, b) end
---@alias game-Scripts-EnemyAILogic.OnUseBallista ...

function game.OrbitAI(a, b) end
---@alias game-Scripts-EnemyAILogic.OrbitAI ...

function game.OrbitId(a, b, c, d) end
---@alias game-Scripts-EnemyAILogic.OrbitId ...

function game.PassiveAI(a) end
---@alias game-Scripts-EnemyAILogic.PassiveAI ...

function game.PolyphemusPickup(a, b, c) end
---@alias game-Scripts-EnemyAILogic.PolyphemusPickup ...

function game.PolyphemusWaitForPlayerAction(a, b, c) end
---@alias game-Scripts-EnemyAILogic.PolyphemusWaitForPlayerAction ...

function game.ProcessAttackSlots(a, b) end
---@alias game-Scripts-EnemyAILogic.ProcessAttackSlots ...

function game.ProcessFireProjecile(a, b) end
---@alias game-Scripts-EnemyAILogic.ProcessFireProjecile ...

function game.ProcessPickup(a, b) end
---@alias game-Scripts-EnemyAILogic.ProcessPickup ...

function game.RamAILoop(a, b) end
---@alias game-Scripts-EnemyAILogic.RamAILoop ...

function game.ReachedAIStageEnd(a) end
---@alias game-Scripts-EnemyAILogic.ReachedAIStageEnd ...

function game.RemoteAI(a) end
---@alias game-Scripts-EnemyAILogic.RemoteAI ...

function game.ResetSentry(a) end
---@alias game-Scripts-EnemyAILogic.ResetSentry ...

function game.RetaliateAttackerAILoop(a, b) end
---@alias game-Scripts-EnemyAILogic.RetaliateAttackerAILoop ...

function game.Retreat(a, b, c) end
---@alias game-Scripts-EnemyAILogic.Retreat ...

function game.SafeZoneAI(a) end
---@alias game-Scripts-EnemyAILogic.SafeZoneAI ...

function game.ScyllaFightTrackSpotlight(a) end
---@alias game-Scripts-EnemyAILogic.ScyllaFightTrackSpotlight ...

function game.SelectTentacleBurrowPoints(a, b) end
---@alias game-Scripts-EnemyAILogic.SelectTentacleBurrowPoints ...

function game.SelectWeapon(a) end
---@alias game-Scripts-EnemyAILogic.SelectWeapon ...

function game.SentryAI(a) end
---@alias game-Scripts-EnemyAILogic.SentryAI ...

function game.SetAI(a, b, c) end
---@alias game-Scripts-EnemyAILogic.SetAI ...

function game.SetupHordeBoss(a) end
---@alias game-Scripts-EnemyAILogic.SetupHordeBoss ...

function game.ShadeMercAI(a) end
---@alias game-Scripts-EnemyAILogic.ShadeMercAI ...

function game.SheepAI(a) end
---@alias game-Scripts-EnemyAILogic.SheepAI ...

function game.SheepHit(a, b, c) end
---@alias game-Scripts-EnemyAILogic.SheepHit ...

function game.SkyAttackerAI(a, b) end
---@alias game-Scripts-EnemyAILogic.SkyAttackerAI ...

function game.SpawnChronosBanners(a, b) end
---@alias game-Scripts-EnemyAILogic.SpawnChronosBanners ...

function game.SpawnSheepGhost(a) end
---@alias game-Scripts-EnemyAILogic.SpawnSheepGhost ...

function game.SpawnSupportAI(a) end
---@alias game-Scripts-EnemyAILogic.SpawnSupportAI ...

function game.StagedAI(a) end
---@alias game-Scripts-EnemyAILogic.StagedAI ...

function game.SurroundAI(a) end
---@alias game-Scripts-EnemyAILogic.SurroundAI ...

function game.SurroundAIRetaliate(a) end
---@alias game-Scripts-EnemyAILogic.SurroundAIRetaliate ...

function game.TakeAmbientBattleDamage(a) end
---@alias game-Scripts-EnemyAILogic.TakeAmbientBattleDamage ...

function game.ThornTreeHit(a, b, c) end
---@alias game-Scripts-EnemyAILogic.ThornTreeHit ...

function game.UnitConsumeHeal(a, b) end
---@alias game-Scripts-EnemyAILogic.UnitConsumeHeal ...

function game.UnitSplit(a, b) end
---@alias game-Scripts-EnemyAILogic.UnitSplit ...

function game.WanderToId(a, b) end
---@alias game-Scripts-EnemyAILogic.WanderToId ...

function game.WeaponRevertStunImmunity(a, b) end
---@alias game-Scripts-EnemyAILogic.WeaponRevertStunImmunity ...

function game.WeaponSetImmuneToStun(a, b) end
---@alias game-Scripts-EnemyAILogic.WeaponSetImmuneToStun ...

return game