---@meta SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late
local game = {}

function game.BouldyBlessingPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.BouldyBlessingPresentation ...

function game.CerberusStageEnter(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.CerberusStageEnter ...

function game.CerberusStageExit(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.CerberusStageExit ...

function game.ChaosManaDrainPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.ChaosManaDrainPresentation ...

function game.ChaosRewardIncreasedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.ChaosRewardIncreasedPresentation ...

function game.ChronosRemainsPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.ChronosRemainsPresentation ...

function game.ChronosRepulseFromObject(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.ChronosRepulseFromObject ...

function game.CirceBlessingPostChoicePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.CirceBlessingPostChoicePresentation ...

function game.CirceBlessingPreChoicePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.CirceBlessingPreChoicePresentation ...

function game.CirceEnlargePresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.CirceEnlargePresentation ...

function game.CirceRemoveShrinePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.CirceRemoveShrinePresentation ...

function game.CirceShrinkPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.CirceShrinkPresentation ...

function game.EchoLastRunBoonPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.EchoLastRunBoonPresentation ...

function game.EchoPostChoicePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.EchoPostChoicePresentation ...

function game.EndHermesEntranceVisuals() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.EndHermesEntranceVisuals ...

function game.EphyraZoomOut(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.EphyraZoomOut ...

function game.FieldsEncounterEndPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.FieldsEncounterEndPresentation ...

function game.FieldsExitsReadyPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.FieldsExitsReadyPresentation ...

function game.FirstPylonHubReturnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.FirstPylonHubReturnPresentation ...

function game.FirstPylonHubReturnPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.FirstPylonHubReturnPresentationEnd ...

function game.IcarusPostChoicePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.IcarusPostChoicePresentation ...

function game.LeaveCharonFight(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.LeaveCharonFight ...

function game.MedeaCursePostChoicePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.MedeaCursePostChoicePresentation ...

function game.NarcissusPostChoicePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NarcissusPostChoicePresentation ...

function game.NemesisDamageContestCountdownPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NemesisDamageContestCountdownPresentation ...

function game.NemesisDamageContestFailPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NemesisDamageContestFailPresentation ...

function game.NemesisDamageContestFinalHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NemesisDamageContestFinalHitPresentation ...

function game.NemesisDamageContestGreatSuccessPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NemesisDamageContestGreatSuccessPresentation ...

function game.NemesisDamageContestHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NemesisDamageContestHitPresentation ...

function game.NemesisDamageContestStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NemesisDamageContestStartPresentation ...

function game.NemesisDamageContestSuccessPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.NemesisDamageContestSuccessPresentation ...

function game.PlayErisTauntAnim(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.PlayErisTauntAnim ...

function game.PlayPolyphemusTauntAnim(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.PlayPolyphemusTauntAnim ...

function game.PlayScyllaTauntAnim(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.PlayScyllaTauntAnim ...

function game.PoseidonSprintBallDetachPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.PoseidonSprintBallDetachPresentation ...

function game.RemoveHermesInPerson(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.RemoveHermesInPerson ...

function game.ResetScyllaMusicStem(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.ResetScyllaMusicStem ...

function game.SpawnHermesInPerson(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.SpawnHermesInPerson ...

function game.StartHermesVisualEffects(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.StartHermesVisualEffects ...

function game.StartSurfacePenaltyPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.StartSurfacePenaltyPresentation ...

function game.StyxFountainPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.StyxFountainPresentation ...

function game.SurfacePenaltyPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.SurfacePenaltyPresentation ...

function game.TartarusChamberMoverPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.TartarusChamberMoverPresentation ...

function game.UnlockCosmeticsShop(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.UnlockCosmeticsShop ...

function game.UseFieldsRewardFinderPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation_Late.UseFieldsRewardFinderPresentation ...

return game