---@meta SGG_Modding-Hades2GameDef-Scripts-EventPresentation
local game = {}

function game.StartClearCastPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StartClearCastPresentation ...

function game.GiftPointEpicRefundPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.GiftPointEpicRefundPresentation ...

function game.CollectRemainingMercenariesPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CollectRemainingMercenariesPresentation ...

function game.PulseAnimation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PulseAnimation ...

function game.StartSpellSlowPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StartSpellSlowPresentation ...

function game.CannotUseFieldsRewardFinderPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CannotUseFieldsRewardFinderPresentation ...

function game.RefundKeepsakeExpiredPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RefundKeepsakeExpiredPresentation ...

function game.RunStartChaosBlessingPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RunStartChaosBlessingPresentation ...

function game.MetaPointRoomRewardPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MetaPointRoomRewardPresentation ...

function game.SuperSacrificePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SuperSacrificePresentation ...

function game.RecordKeeperReaction(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RecordKeeperReaction ...

function game.HestiaSacrificePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HestiaSacrificePresentation ...

function game.HammerKeepsakeLostPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HammerKeepsakeLostPresentation ...

function game.DoraTeleportExit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DoraTeleportExit ...

function game.DaggerBlockTriggeredPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DaggerBlockTriggeredPresentation ...

function game.IncreasedTraitLevelPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.IncreasedTraitLevelPresentation ...

function game.TraitSacrificedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TraitSacrificedPresentation ...

function game.BossShieldTriggeredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.BossShieldTriggeredPresentation ...

function game.SetPlayerFade(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SetPlayerFade ...

function game.HeroShopDeliveryPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroShopDeliveryPresentation ...

function game.PlayEmote(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayEmote ...

function game.WretchedBrokerReaction(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.WretchedBrokerReaction ...

function game.ContinuousRarifyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ContinuousRarifyPresentation ...

function game.SpeedKeepsakeExpiredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SpeedKeepsakeExpiredPresentation ...

function game.CannotUseObjectPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CannotUseObjectPresentation ...

function game.TimedBuffExpiredPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TimedBuffExpiredPresentation ...

function game.FirstTimeWeaponPickupPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.FirstTimeWeaponPickupPresentation ...

function game.ConvertMetaRewardPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ConvertMetaRewardPresentation ...

function game.TemporaryHealExpirationPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TemporaryHealExpirationPresentation ...

function game.HitShieldTriggeredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HitShieldTriggeredPresentation ...

function game.MoneyFlashRed() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MoneyFlashRed ...

function game.FinishedTextLinesPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.FinishedTextLinesPresentation ...

function game.GiftPointRefundPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.GiftPointRefundPresentation ...

function game.CannotUseZoomOutPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CannotUseZoomOutPresentation ...

function game.PreDamagePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PreDamagePresentation ...

function game.PerfectChargeRefundPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PerfectChargeRefundPresentation ...

function game.PowerWordPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PowerWordPresentation ...

function game.HadesGiftPointRefundPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HadesGiftPointRefundPresentation ...

function game.OnionTransformationPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.OnionTransformationPresentation ...

function game.BlockedKeepsakePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.BlockedKeepsakePresentation ...

function game.OncePerMenuRarifyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.OncePerMenuRarifyPresentation ...

function game.ClearPlayerFade(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ClearPlayerFade ...

function game.FrogFamiliarReaction(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.FrogFamiliarReaction ...

function game.PlayEmoteSimple(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayEmoteSimple ...

function game.ManaTraitGainedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ManaTraitGainedPresentation ...

function game.LoungeRevelryPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.LoungeRevelryPresentation ...

function game.LearnedSageReaction(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.LearnedSageReaction ...

function game.GiftPointRareRefundPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.GiftPointRareRefundPresentation ...

function game.BonusHealthAndManaPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.BonusHealthAndManaPresentation ...

function game.CheckSpawnNearIdEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CheckSpawnNearIdEndPresentation ...

function game.ShowInvincibubbleOnObject(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ShowInvincibubbleOnObject ...

function game.SprintShieldTriggeredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SprintShieldTriggeredPresentation ...

function game.PowerWordPresentationWorld(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PowerWordPresentationWorld ...

function game.DirectionHintPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DirectionHintPresentation ...

function game.HeroMajorDamagePresentationThread(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroMajorDamagePresentationThread ...

function game.HammerKeepsakeAcquiredPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HammerKeepsakeAcquiredPresentation ...

function game.RaiseDeadPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RaiseDeadPresentation ...

function game.PlayEmoteAnimFromSource(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayEmoteAnimFromSource ...

function game.HeroLowHealthPresentationThread(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroLowHealthPresentationThread ...

function game.PlayerArmorBreakPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayerArmorBreakPresentation ...

function game.AutoUseFailedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.AutoUseFailedPresentation ...

function game.CheckSpawnNearIdPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CheckSpawnNearIdPresentation ...

function game.DisplayFreezeEscapeHint(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DisplayFreezeEscapeHint ...

function game.dumpA(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.dumpA ...

function game.TerminateBlinkTrail() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TerminateBlinkTrail ...

function game.SwitchWeaponImage(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SwitchWeaponImage ...

function game.HeroArmorDamagePresentationThread(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroArmorDamagePresentationThread ...

function game.DoubleRewardPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DoubleRewardPresentation ...

function game.ChaosTimerAboutToExpirePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ChaosTimerAboutToExpirePresentation ...

function game.HeroLowHealthBarPulseThread() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroLowHealthBarPulseThread ...

function game.StoreRewardRandomStackPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StoreRewardRandomStackPresentation ...

function game.SpellSlowWarnPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SpellSlowWarnPresentation ...

function game.DoraReturnToHaunting(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DoraReturnToHaunting ...

function game.ActivateTempInvulnerabilityPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ActivateTempInvulnerabilityPresentation ...

function game.AddAmmoPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.AddAmmoPresentation ...

function game.PlayHecateTauntAnim(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayHecateTauntAnim ...

function game.BiomeTimerExpiredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.BiomeTimerExpiredPresentation ...

function game.AddOverheadText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.AddOverheadText ...

function game.SurpriseNPCPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SurpriseNPCPresentation ...

function game.MatchModelToPortrait(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MatchModelToPortrait ...

function game.RelationshipChangedIconPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RelationshipChangedIconPresentation ...

function game.BiomeTimerAboutToExpirePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.BiomeTimerAboutToExpirePresentation ...

function game.GenericThankCharacterPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.GenericThankCharacterPresentation ...

function game.LootPickupPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.LootPickupPresentation ...

function game.HeroDamagePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroDamagePresentation ...

function game.CannotUseKeepsakeRackPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CannotUseKeepsakeRackPresentation ...

function game.EndClearCastPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.EndClearCastPresentation ...

function game.CantPurchaseWorldItemPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CantPurchaseWorldItemPresentation ...

function game.ChaosKeepsakeAcquiredPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ChaosKeepsakeAcquiredPresentation ...

function game.StaffHealPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StaffHealPresentation ...

function game.ElementalTraitUpdatedPresentation(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ElementalTraitUpdatedPresentation ...

function game.StartTimeSlowPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StartTimeSlowPresentation ...

function game.AddedMetaUpgradePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.AddedMetaUpgradePresentation ...

function game.DisplayPlayerDamageText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DisplayPlayerDamageText ...

function game.HeroDamagePresentationThread(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroDamagePresentationThread ...

function game.HeroTraitTransformPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroTraitTransformPresentation ...

function game.SkellyHitQuestCompletePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SkellyHitQuestCompletePresentation ...

function game.UpgradeBoonRarityPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.UpgradeBoonRarityPresentation ...

function game.TrackPlayer(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TrackPlayer ...

function game.HeroFinalDamagePresentationThread(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroFinalDamagePresentationThread ...

function game.HouseFrontDoorUsedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HouseFrontDoorUsedPresentation ...

function game.HypnosReturnToSleep(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HypnosReturnToSleep ...

function game.RerollPanelPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RerollPanelPresentation ...

function game.MedeaCursePreChoicePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MedeaCursePreChoicePresentation ...

function game.CantAffordPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CantAffordPresentation ...

function game.RepulseFromObject(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RepulseFromObject ...

function game.ChaosHammerPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ChaosHammerPresentation ...

function game.TimePassesFishingSFX(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TimePassesFishingSFX ...

function game.UnfrozenPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.UnfrozenPresentation ...

function game.HeroDamageLowHealthPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroDamageLowHealthPresentation ...

function game.ChillClearPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ChillClearPresentation ...

function game.DaggerBlockActivePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DaggerBlockActivePresentation ...

function game.GenericPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.GenericPresentation ...

function game.ResourceGiftedInEventPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ResourceGiftedInEventPresentation ...

function game.HeroLowHealthShroudPulseThread() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HeroLowHealthShroudPulseThread ...

function game.StasisPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StasisPresentation ...

function game.KeepsakeLevelUpPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.KeepsakeLevelUpPresentation ...

function game.MultipleEncounterStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MultipleEncounterStartPresentation ...

function game.EndTimeSlowPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.EndTimeSlowPresentation ...

function game.RootClearPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RootClearPresentation ...

function game.CannotUseDoorPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CannotUseDoorPresentation ...

function game.OnManaRestored(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.OnManaRestored ...

function game.HadesPreDamagePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HadesPreDamagePresentation ...

function game.DoorHealKeepsakeExpiredPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DoorHealKeepsakeExpiredPresentation ...

function game.DoubleBoonPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DoubleBoonPresentation ...

function game.CannotRerollPanelPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CannotRerollPanelPresentation ...

function game.PopOverheadText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PopOverheadText ...

function game.ShowMetaUpgradeCard(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ShowMetaUpgradeCard ...

function game.PulseText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PulseText ...

function game.OnPlayerHealed(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.OnPlayerHealed ...

function game.RunStartHammerKeepsakeAcquiredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RunStartHammerKeepsakeAcquiredPresentation ...

function game.InteractBlockedByEnemiesPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.InteractBlockedByEnemiesPresentation ...

function game.MagicWordPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MagicWordPresentation ...

function game.DiminishingDodgeExpiredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DiminishingDodgeExpiredPresentation ...

function game.StartedTextLinesPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StartedTextLinesPresentation ...

function game.CreateDialogueBackground() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CreateDialogueBackground ...

function game.PlayCharacterAnim(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayCharacterAnim ...

function game.TimePassesPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TimePassesPresentation ...

function game.MetaPointRoomRewardPresentationThread(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MetaPointRoomRewardPresentationThread ...

function game.RandomStoreItemPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RandomStoreItemPresentation ...

function game.IncreasedTraitRarityPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.IncreasedTraitRarityPresentation ...

function game.PermafyShopItemPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PermafyShopItemPresentation ...

function game.DaggerBlockClearedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DaggerBlockClearedPresentation ...

function game.RootApplyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RootApplyPresentation ...

function game.DisplayPlayerHealingText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DisplayPlayerHealingText ...

function game.ChaosTransformationPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ChaosTransformationPresentation ...

function game.AtLastStandMaxPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.AtLastStandMaxPresentation ...

function game.FrozenPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.FrozenPresentation ...

function game.PlayerArmorBreakSimSpeed() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayerArmorBreakSimSpeed ...

function game.ReducedTraitRarityPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ReducedTraitRarityPresentation ...

function game.BonusManaPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.BonusManaPresentation ...

function game.ExShieldTriggeredPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ExShieldTriggeredPresentation ...

function game.UnwrapLootPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.UnwrapLootPresentation ...

function game.RangedFailedNoAmmoPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RangedFailedNoAmmoPresentation ...

function game.MaxedRelationshipPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.MaxedRelationshipPresentation ...

function game.HarvestBoonTraitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.HarvestBoonTraitPresentation ...

function game.TraitLockedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.TraitLockedPresentation ...

function game.AddKeepsakeChargePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.AddKeepsakeChargePresentation ...

function game.SpeedKeepsakeActivatedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.SpeedKeepsakeActivatedPresentation ...

function game.StartBlinkTrailPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StartBlinkTrailPresentation ...

function game.ElementalTraitUpdatedPresentationReal() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ElementalTraitUpdatedPresentationReal ...

function game.FreezeEscapeInputPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.FreezeEscapeInputPresentation ...

function game.CantPurchasePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.CantPurchasePresentation ...

function game.OnPlayerArmorGain(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.OnPlayerArmorGain ...

function game.BiomeDamagePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.BiomeDamagePresentation ...

function game.DisplayEnemyHealingText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DisplayEnemyHealingText ...

function game.DaggerFinalHitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DaggerFinalHitPresentation ...

function game.ChillApplyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ChillApplyPresentation ...

function game.PlayedMusicPlayerTrackPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.PlayedMusicPlayerTrackPresentation ...

function game.EndSpellSlowPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.EndSpellSlowPresentation ...

function game.NHubBossDoorExitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.NHubBossDoorExitPresentation ...

function game.DisableTempInvulnerabilityPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.DisableTempInvulnerabilityPresentation ...

function game.StartHeroLowHealthPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.StartHeroLowHealthPresentation ...

function game.RelationshipChangedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.RelationshipChangedPresentation ...

function game.GodLootPickupPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.GodLootPickupPresentation ...

function game.ResourceGiftedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-EventPresentation.ResourceGiftedPresentation ...

return game