---@meta game-Scripts-FamiliarPresentation
local game = {}

function game.CatFamiliarAlertedPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarAlertedPresentation ...

function game.CatFamiliarAttackPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarAttackPresentation ...

function game.CatFamiliarPreAttackPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarPreAttackPresentation ...

function game.CatFamiliarRecruit(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarRecruit ...

function game.CatFamiliarSpawnPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarSpawnPresentation ...

function game.CatFamiliarSpecialInteractLockedInRun(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarSpecialInteractLockedInRun ...

function game.CatFamiliarSpecialInteractUnlockedInHub(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFamiliarSpecialInteractUnlockedInHub ...

function game.CatFledPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.CatFledPresentation ...

function game.EquipFamiliarPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.EquipFamiliarPresentation ...

function game.FamiliarRestedPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.FamiliarRestedPresentation ...

function game.FamiliarRestingPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.FamiliarRestingPresentation ...

function game.FamiliarRoomExitPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarRoomExitPresentation ...

function game.FamiliarVictoryPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FamiliarVictoryPresentation ...

function game.FrogFamiliarRecruit(a, b) end
---@alias game-Scripts-FamiliarPresentation.FrogFamiliarRecruit ...

function game.FrogFamiliarSpawnPresentation(a, b) end
---@alias game-Scripts-FamiliarPresentation.FrogFamiliarSpawnPresentation ...

function game.PetFamiliarFrog(a, b) end
---@alias game-Scripts-FamiliarPresentation.PetFamiliarFrog ...

function game.UnequipFamiliarPresentation(a) end
---@alias game-Scripts-FamiliarPresentation.UnequipFamiliarPresentation ...

return game