---@meta game-Scripts-FamiliarShopPresentation
local game = {}

function game.CleanUpUpgradeSparkles(a) end
---@alias game-Scripts-FamiliarShopPresentation.CleanUpUpgradeSparkles ...

function game.FamiliarShopItemPurchasedPresentation(a, b, c) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopItemPurchasedPresentation ...

function game.FamiliarShopPurchasePostActivatePresentation(a, b, c) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopPurchasePostActivatePresentation ...

function game.FamiliarShopPurchasePreActivatePresentation(a, b, c, d) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopPurchasePreActivatePresentation ...

function game.FamiliarShopScreenCloseFinishedPresentation(a) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopScreenCloseFinishedPresentation ...

function game.FamiliarShopScreenCloseStartPresentation(a) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopScreenCloseStartPresentation ...

function game.FamiliarShopScreenOpenedPresentation(a, b) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopScreenOpenedPresentation ...

function game.FamiliarShopScreenOpenFinishedPresentation(a) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopScreenOpenFinishedPresentation ...

function game.FamiliarShopScreenScrollPresentation(a, b) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopScreenScrollPresentation ...

function game.FamiliarShopScreenSelectCategoryPresentation(a, b) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopScreenSelectCategoryPresentation ...

function game.FamiliarShopSessionCompletePresentation(a, b) end
---@alias game-Scripts-FamiliarShopPresentation.FamiliarShopSessionCompletePresentation ...

function game.GiftFamiliarUpgradePresentation(a, b) end
---@alias game-Scripts-FamiliarShopPresentation.GiftFamiliarUpgradePresentation ...

function game.MouseOffFamiliarShopItem(a) end
---@alias game-Scripts-FamiliarShopPresentation.MouseOffFamiliarShopItem ...

function game.MouseOverFamiliarShopItem(a) end
---@alias game-Scripts-FamiliarShopPresentation.MouseOverFamiliarShopItem ...

return game