---@meta game-Scripts-FamiliarLogic
local game = {}

function game.ActivateFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.ActivateFamiliar ...

function game.AssignFamiliarKits(a, b) end
---@alias game-Scripts-FamiliarLogic.AssignFamiliarKits ...

function game.BackPlayerUp(a, b, c) end
---@alias game-Scripts-FamiliarLogic.BackPlayerUp ...

function game.CatFamiliarAI(a, b) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarAI ...

function game.CatFamiliarMoveToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarMoveToLocation ...

function game.CatFamiliarMoveToRandomLocation(a, b, c) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarMoveToRandomLocation ...

function game.CatFamiliarShouldAlert(a, b) end
---@alias game-Scripts-FamiliarLogic.CatFamiliarShouldAlert ...

function game.EquipFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.EquipFamiliar ...

function game.FamiliarSetup(a, b) end
---@alias game-Scripts-FamiliarLogic.FamiliarSetup ...

function game.FamiliarTimeTick(a) end
---@alias game-Scripts-FamiliarLogic.FamiliarTimeTick ...

function game.FrogFamiliarMoveToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.FrogFamiliarMoveToLocation ...

function game.FrogFollowAI(a, b) end
---@alias game-Scripts-FamiliarLogic.FrogFollowAI ...

function game.FrogHitResponse(a, b) end
---@alias game-Scripts-FamiliarLogic.FrogHitResponse ...

function game.FrogLeap(a, b, c) end
---@alias game-Scripts-FamiliarLogic.FrogLeap ...

function game.GetFamiliarBonusUses(a) end
---@alias game-Scripts-FamiliarLogic.GetFamiliarBonusUses ...

function game.MoveFamiliarToLocation(a, b) end
---@alias game-Scripts-FamiliarLogic.MoveFamiliarToLocation ...

function game.ReenableFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.ReenableFamiliar ...

function game.ReturnFamiliarToKit(a, b, c) end
---@alias game-Scripts-FamiliarLogic.ReturnFamiliarToKit ...

function game.UnequipFamiliar(a, b) end
---@alias game-Scripts-FamiliarLogic.UnequipFamiliar ...

function game.UpdateFamiliarKits(a) end
---@alias game-Scripts-FamiliarLogic.UpdateFamiliarKits ...

function game.UseFamiliar(a, b, c) end
---@alias game-Scripts-FamiliarLogic.UseFamiliar ...

function game.UseFamiliarUnequip(a, b, c) end
---@alias game-Scripts-FamiliarLogic.UseFamiliarUnequip ...

return game