---@meta SGG_Modding-Hades2GameDef-Scripts-FishingPresentation
local game = {}

function game.FishingReadyForInputPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingReadyForInputPresentation ...

function game.FishingReelSequenceStartPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingReelSequenceStartPresentation ...

function game.FishingReelMissPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingReelMissPresentation ...

function game.GiftActivityFishingStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.GiftActivityFishingStartPresentation ...

function game.GiftActivityFishingEndPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.GiftActivityFishingEndPresentation ...

function game.FishingReelHitPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingReelHitPresentation ...

function game.FamiliarFishingPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FamiliarFishingPresentation ...

function game.FishingEndPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingEndPresentation ...

function game.FishingBlockedByEncounterPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingBlockedByEncounterPresentation ...

function game.FishingCaughtPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingCaughtPresentation ...

function game.FishingReelCooldownPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingReelCooldownPresentation ...

function game.FishingBlockedByLavaPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingBlockedByLavaPresentation ...

function game.FishingReadyForReelInputPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingReadyForReelInputPresentation ...

function game.FishingStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingStartPresentation ...

function game.FishingTargetPulse(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingTargetPulse ...

function game.FishingInProgressPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingInProgressPresentation ...

function game.FishingWayLatePresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-FishingPresentation.FishingWayLatePresentation ...

return game