---@meta game-Scripts-FlashbackPresentation
local game = {}

function game.ConcludeFlashback() end
---@alias game-Scripts-FlashbackPresentation.ConcludeFlashback ...

function game.FlashbackExpandClamps() end
---@alias game-Scripts-FlashbackPresentation.FlashbackExpandClamps ...

function game.HecateFlashback02Exit(a, b) end
---@alias game-Scripts-FlashbackPresentation.HecateFlashback02Exit ...

function game.HecateHideAndSeekExit(a, b) end
---@alias game-Scripts-FlashbackPresentation.HecateHideAndSeekExit ...

function game.HecateHideAndSeekHint(a, b) end
---@alias game-Scripts-FlashbackPresentation.HecateHideAndSeekHint ...

function game.NightmareScreenEffects(a, b) end
---@alias game-Scripts-FlashbackPresentation.NightmareScreenEffects ...

function game.SetupFlashback01(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashback01 ...

function game.SetupFlashback02(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashback02 ...

function game.SetupFlashback02_DeathArea(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashback02_DeathArea ...

function game.SetupFlashbackMusic(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashbackMusic ...

function game.SetupFlashbackPlayerUnitHades(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashbackPlayerUnitHades ...

function game.SetupFlashbackPlayerUnitMel(a, b) end
---@alias game-Scripts-FlashbackPresentation.SetupFlashbackPlayerUnitMel ...

function game.UpdateHubMainFlashback(a, b) end
---@alias game-Scripts-FlashbackPresentation.UpdateHubMainFlashback ...

return game