---@meta game-Scripts-GameStatsLogic
local game = {}

function game.CloseGameStatsScreen(a, b) end
---@alias game-Scripts-GameStatsLogic.CloseGameStatsScreen ...

function game.GameStatsChangeSortMode(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsChangeSortMode ...

function game.GameStatsNextCategory(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsNextCategory ...

function game.GameStatsPrevCategory(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsPrevCategory ...

function game.GameStatsProcessTraitsForRun(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsProcessTraitsForRun ...

function game.GameStatsScrollDown(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsScrollDown ...

function game.GameStatsScrollUp(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsScrollUp ...

function game.GameStatsSelectCategory(a, b) end
---@alias game-Scripts-GameStatsLogic.GameStatsSelectCategory ...

function game.GameStatsUpdateVisibility(a) end
---@alias game-Scripts-GameStatsLogic.GameStatsUpdateVisibility ...

function game.GetFastestRunClearTime(a) end
---@alias game-Scripts-GameStatsLogic.GetFastestRunClearTime ...

function game.GetFastestRunClearTimeWithWeapon(a, b) end
---@alias game-Scripts-GameStatsLogic.GetFastestRunClearTimeWithWeapon ...

function game.GetHighestPrevRunRepth(a) end
---@alias game-Scripts-GameStatsLogic.GetHighestPrevRunRepth ...

function game.GetHighestShrinePointRunClear(a, b) end
---@alias game-Scripts-GameStatsLogic.GetHighestShrinePointRunClear ...

function game.GetHighestShrinePointRunClearWithWeapon(a, b) end
---@alias game-Scripts-GameStatsLogic.GetHighestShrinePointRunClearWithWeapon ...

function game.GetNumRunsClearedWithWeapon(a) end
---@alias game-Scripts-GameStatsLogic.GetNumRunsClearedWithWeapon ...

function game.GetNumRunsWithWeapon(a) end
---@alias game-Scripts-GameStatsLogic.GetNumRunsWithWeapon ...

function game.IsRecordRunDepth(a) end
---@alias game-Scripts-GameStatsLogic.IsRecordRunDepth ...

function game.OpenGameStatsScreen(a) end
---@alias game-Scripts-GameStatsLogic.OpenGameStatsScreen ...

function game.PassesTraitFilter(a, b) end
---@alias game-Scripts-GameStatsLogic.PassesTraitFilter ...

function game.RunHasOneOfTraits(a, b) end
---@alias game-Scripts-GameStatsLogic.RunHasOneOfTraits ...

function game.RunHasTraits(a, b) end
---@alias game-Scripts-GameStatsLogic.RunHasTraits ...

function game.RunHistoryStatsSort(a, b) end
---@alias game-Scripts-GameStatsLogic.RunHistoryStatsSort ...

function game.ShowTraitStats(a) end
---@alias game-Scripts-GameStatsLogic.ShowTraitStats ...

function game.ShowWeaponStats(a) end
---@alias game-Scripts-GameStatsLogic.ShowWeaponStats ...

function game.UseGameStatsScreenObject(a, b) end
---@alias game-Scripts-GameStatsLogic.UseGameStatsScreenObject ...

return game