---@meta game-Scripts-GhostAdminLogic
local game = {}

function game.AddWorldUpgrade(a, b) end
---@alias game-Scripts-GhostAdminLogic.AddWorldUpgrade ...

function game.CloseGhostAdminScreen(a, b) end
---@alias game-Scripts-GhostAdminLogic.CloseGhostAdminScreen ...

function game.CookTimeTick(a) end
---@alias game-Scripts-GhostAdminLogic.CookTimeTick ...

function game.DoGhostAdminPurchase(a, b) end
---@alias game-Scripts-GhostAdminLogic.DoGhostAdminPurchase ...

function game.DoGhostAdminRemoval(a, b) end
---@alias game-Scripts-GhostAdminLogic.DoGhostAdminRemoval ...

function game.GhostAdminAllowViewItem(a, b, c) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminAllowViewItem ...

function game.GhostAdminDisplayCategory(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminDisplayCategory ...

function game.GhostAdminHideItems(a) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminHideItems ...

function game.GhostAdminNextCategory(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminNextCategory ...

function game.GhostAdminPinItem(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminPinItem ...

function game.GhostAdminPrevCategory(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminPrevCategory ...

function game.GhostAdminPurchaseSequenceFinished(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminPurchaseSequenceFinished ...

function game.GhostAdminScrollDown(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminScrollDown ...

function game.GhostAdminScrollUp(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminScrollUp ...

function game.GhostAdminSelectCategory(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminSelectCategory ...

function game.GhostAdminUpdateVisibility(a, b) end
---@alias game-Scripts-GhostAdminLogic.GhostAdminUpdateVisibility ...

function game.HandleGhostAdminPurchase(a, b) end
---@alias game-Scripts-GhostAdminLogic.HandleGhostAdminPurchase ...

function game.HandleGhostAdminRemoval(a, b) end
---@alias game-Scripts-GhostAdminLogic.HandleGhostAdminRemoval ...

function game.HasUnpurchasedCosmetic(a) end
---@alias game-Scripts-GhostAdminLogic.HasUnpurchasedCosmetic ...

function game.HasUnviewedCosmetic(a) end
---@alias game-Scripts-GhostAdminLogic.HasUnviewedCosmetic ...

function game.HasUnviewedWorldUpgrade(a) end
---@alias game-Scripts-GhostAdminLogic.HasUnviewedWorldUpgrade ...

function game.OpenGhostAdminScreen(a, b) end
---@alias game-Scripts-GhostAdminLogic.OpenGhostAdminScreen ...

function game.SetupCauldronCookStatus(a, b) end
---@alias game-Scripts-GhostAdminLogic.SetupCauldronCookStatus ...

function game.UnlockWorldUpgrade(a) end
---@alias game-Scripts-GhostAdminLogic.UnlockWorldUpgrade ...

function game.UseCauldronCookComplete(a, b) end
---@alias game-Scripts-GhostAdminLogic.UseCauldronCookComplete ...

function game.UseGhostAdmin(a, b) end
---@alias game-Scripts-GhostAdminLogic.UseGhostAdmin ...

function game.ValidateItemCategories() end
---@alias game-Scripts-GhostAdminLogic.ValidateItemCategories ...

return game