---@meta SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation
local game = {}

function game.CauldronIncantationPresentation(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.CauldronIncantationPresentation ...

function game.CauldronResourceSpendPresentation(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.CauldronResourceSpendPresentation ...

function game.CauldronSceneSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.CauldronSceneSetup ...

function game.GhostAdminItemPurchasedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminItemPurchasedPresentation ...

function game.GhostAdminMouseOffScrollArrow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminMouseOffScrollArrow ...

function game.GhostAdminMouseOverScrollArrow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminMouseOverScrollArrow ...

function game.GhostAdminPostDisplayCategoryPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminPostDisplayCategoryPresentation ...

function game.GhostAdminScreenClosedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminScreenClosedPresentation ...

function game.GhostAdminScreenOpenFinishedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminScreenOpenFinishedPresentation ...

function game.GhostAdminScreenRevealNewItemsPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminScreenRevealNewItemsPresentation ...

function game.GhostAdminScreenScrollPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminScreenScrollPresentation ...

function game.GhostAdminSelectCategoryPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminSelectCategoryPresentation ...

function game.GhostAdminSessionCompletePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.GhostAdminSessionCompletePresentation ...

function game.MouseOffGhostAdminCategory(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.MouseOffGhostAdminCategory ...

function game.MouseOffGhostAdminItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.MouseOffGhostAdminItem ...

function game.MouseOverGhostAdminCategory(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.MouseOverGhostAdminCategory ...

function game.MouseOverGhostAdminItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.MouseOverGhostAdminItem ...

function game.PostActivateCriticalItemPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.PostActivateCriticalItemPresentation ...

function game.PostIncantationPresentationUnlockText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.PostIncantationPresentationUnlockText ...

function game.PreActivateCriticalItemPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.PreActivateCriticalItemPresentation ...

function game.SetupCauldronCookActivePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.SetupCauldronCookActivePresentation ...

function game.SetupCauldronLocked(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.SetupCauldronLocked ...

function game.UpdateGhostAdminInteractionText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.UpdateGhostAdminInteractionText ...

function game.UseCauldronCookActivePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.UseCauldronCookActivePresentation ...

function game.UseCauldronCookCompletePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-GhostAdminPresentation.UseCauldronCookCompletePresentation ...

return game