---@meta SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation
local game = {}

function game.ExorcismFailPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismFailPresentation ...

function game.ExorcismGhostEmotePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismGhostEmotePresentation ...

function game.ExorcismInputCheckPresentation(a, b, c, d, e, f, g, h, i, j) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismInputCheckPresentation ...

function game.ExorcismNextMovePresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismNextMovePresentation ...

function game.ExorcismPointChosenPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismPointChosenPresentation ...

function game.ExorcismPointGetUseText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismPointGetUseText ...

function game.ExorcismStartPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismStartPresentation ...

function game.ExorcismSuccessPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ExorcismSuccessPresentation ...

function game.FamiliarExorcismStartPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.FamiliarExorcismStartPresentation ...

function game.FamiliarExorcismSuccessPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.FamiliarExorcismSuccessPresentation ...

function game.FamiliarPickaxeStartPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.FamiliarPickaxeStartPresentation ...

function game.HarvestBlockedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.HarvestBlockedPresentation ...

function game.HarvestBonusResourcePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.HarvestBonusResourcePresentation ...

function game.HarvestEndPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.HarvestEndPresentation ...

function game.HarvestNoToolPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.HarvestNoToolPresentation ...

function game.HarvestStartPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.HarvestStartPresentation ...

function game.PickaxeDepositDamagedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.PickaxeDepositDamagedPresentation ...

function game.PickaxeDepositDestroyedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.PickaxeDepositDestroyedPresentation ...

function game.PickaxeStartPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.PickaxeStartPresentation ...

function game.PulseExorcismIcon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.PulseExorcismIcon ...

function game.ShovelEndPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ShovelEndPresentation ...

function game.ShovelPointBombPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ShovelPointBombPresentation ...

function game.ShovelStartPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HarvestPresentation.ShovelStartPresentation ...

return game