---@meta game-Scripts-HubPresentation
local game = {}

function game.AltarEnterPresentation(a, b) end
---@alias game-Scripts-HubPresentation.AltarEnterPresentation ...

function game.AltarExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.AltarExitPresentation ...

function game.AttemptPetCerberusThread() end
---@alias game-Scripts-HubPresentation.AttemptPetCerberusThread ...

function game.BathHouseEndPresentation(a, b) end
---@alias game-Scripts-HubPresentation.BathHouseEndPresentation ...

function game.BathHouseQuipPresentation(a, b, c) end
---@alias game-Scripts-HubPresentation.BathHouseQuipPresentation ...

function game.BathHouseStartPresentation(a, b, c) end
---@alias game-Scripts-HubPresentation.BathHouseStartPresentation ...

function game.CauldronAssistCompletePresentation(a, b) end
---@alias game-Scripts-HubPresentation.CauldronAssistCompletePresentation ...

function game.CauldronCastingJoinInVoiceLines(a, b) end
---@alias game-Scripts-HubPresentation.CauldronCastingJoinInVoiceLines ...

function game.CauldronCastingPresentation(a, b) end
---@alias game-Scripts-HubPresentation.CauldronCastingPresentation ...

function game.CauldronPresentationBurst() end
---@alias game-Scripts-HubPresentation.CauldronPresentationBurst ...

function game.CauldronPresentationRing() end
---@alias game-Scripts-HubPresentation.CauldronPresentationRing ...

function game.CauldronWitchcraftPresentation(a, b) end
---@alias game-Scripts-HubPresentation.CauldronWitchcraftPresentation ...

function game.CloseWeaponUpgradeScreenPresentation(a) end
---@alias game-Scripts-HubPresentation.CloseWeaponUpgradeScreenPresentation ...

function game.DeathAreaAttackFailPresentation(a, b) end
---@alias game-Scripts-HubPresentation.DeathAreaAttackFailPresentation ...

function game.DimmerPresentation(a, b) end
---@alias game-Scripts-HubPresentation.DimmerPresentation ...

function game.EnterHubRoomPresentation(a, b) end
---@alias game-Scripts-HubPresentation.EnterHubRoomPresentation ...

function game.EstablishConversationStartingPoint(a, b) end
---@alias game-Scripts-HubPresentation.EstablishConversationStartingPoint ...

function game.FailToPetCerberus() end
---@alias game-Scripts-HubPresentation.FailToPetCerberus ...

function game.FishingPierEndPresentation(a, b) end
---@alias game-Scripts-HubPresentation.FishingPierEndPresentation ...

function game.FishingPierStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.FishingPierStartPresentation ...

function game.GhostEavesdroppers(a, b) end
---@alias game-Scripts-HubPresentation.GhostEavesdroppers ...

function game.GhostFollowerAI(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowerAI ...

function game.GhostFollowerGainAggroPresentation(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowerGainAggroPresentation ...

function game.GhostFollowerLoseAggroPresentation(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowerLoseAggroPresentation ...

function game.GhostFollowers(a, b) end
---@alias game-Scripts-HubPresentation.GhostFollowers ...

function game.LeaveHubRoomPresentation(a, b) end
---@alias game-Scripts-HubPresentation.LeaveHubRoomPresentation ...

function game.LockedSurfaceRunPresentation(a, b) end
---@alias game-Scripts-HubPresentation.LockedSurfaceRunPresentation ...

function game.MelFootDrop() end
---@alias game-Scripts-HubPresentation.MelFootDrop ...

function game.MelReadyFlash() end
---@alias game-Scripts-HubPresentation.MelReadyFlash ...

function game.MorosObserveFatedList(a, b, c) end
---@alias game-Scripts-HubPresentation.MorosObserveFatedList ...

function game.MorosObservingInterrupt(a, b, c) end
---@alias game-Scripts-HubPresentation.MorosObservingInterrupt ...

function game.OdysseusArriveAtGardenPlot(a, b, c) end
---@alias game-Scripts-HubPresentation.OdysseusArriveAtGardenPlot ...

function game.OdysseusArriveAtTable(a, b, c) end
---@alias game-Scripts-HubPresentation.OdysseusArriveAtTable ...

function game.OpenShrineScreenPostPresentation(a) end
---@alias game-Scripts-HubPresentation.OpenShrineScreenPostPresentation ...

function game.OpenShrineScreenPrePresentation(a, b) end
---@alias game-Scripts-HubPresentation.OpenShrineScreenPrePresentation ...

function game.PetCerberus() end
---@alias game-Scripts-HubPresentation.PetCerberus ...

function game.PetCerberusThread() end
---@alias game-Scripts-HubPresentation.PetCerberusThread ...

function game.PostBossFirstFloorPresentation(a, b) end
---@alias game-Scripts-HubPresentation.PostBossFirstFloorPresentation ...

function game.PostBossSecondFloorPresentation(a, b) end
---@alias game-Scripts-HubPresentation.PostBossSecondFloorPresentation ...

function game.PreOpenWeaponUpgradeScreenPresentation(a) end
---@alias game-Scripts-HubPresentation.PreOpenWeaponUpgradeScreenPresentation ...

function game.PreRunBackToRoom() end
---@alias game-Scripts-HubPresentation.PreRunBackToRoom ...

function game.PreRunOverlook() end
---@alias game-Scripts-HubPresentation.PreRunOverlook ...

function game.RevealBathHousePresentation(a) end
---@alias game-Scripts-HubPresentation.RevealBathHousePresentation ...

function game.RevealFishingPointPresentation(a) end
---@alias game-Scripts-HubPresentation.RevealFishingPointPresentation ...

function game.RevealTavernaPresentation(a) end
---@alias game-Scripts-HubPresentation.RevealTavernaPresentation ...

function game.SetupCauldronWitchcraftPresentation(a, b) end
---@alias game-Scripts-HubPresentation.SetupCauldronWitchcraftPresentation ...

function game.SetupLockedGiftRack(a) end
---@alias game-Scripts-HubPresentation.SetupLockedGiftRack ...

function game.ShowOverlookText() end
---@alias game-Scripts-HubPresentation.ShowOverlookText ...

function game.StartDeathLoopPresentation(a) end
---@alias game-Scripts-HubPresentation.StartDeathLoopPresentation ...

function game.StartNewRunPresentation(a, b) end
---@alias game-Scripts-HubPresentation.StartNewRunPresentation ...

function game.TavernaEndPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TavernaEndPresentation ...

function game.TavernaStartPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TavernaStartPresentation ...

function game.TechTestEscapeDoorClosed(a, b) end
---@alias game-Scripts-HubPresentation.TechTestEscapeDoorClosed ...

function game.TeleportToConversationStartingPoint(a, b) end
---@alias game-Scripts-HubPresentation.TeleportToConversationStartingPoint ...

function game.TentEnterPresentation() end
---@alias game-Scripts-HubPresentation.TentEnterPresentation ...

function game.TentExitPresentation(a, b) end
---@alias game-Scripts-HubPresentation.TentExitPresentation ...

function game.UseCauldronJoinWitchcraft(a, b, c) end
---@alias game-Scripts-HubPresentation.UseCauldronJoinWitchcraft ...

function game.UseCrossroadsPet01(a, b) end
---@alias game-Scripts-HubPresentation.UseCrossroadsPet01 ...

function game.UseGhostEavesdropper(a, b, c) end
---@alias game-Scripts-HubPresentation.UseGhostEavesdropper ...

function game.UseLockedSystemObjectPresentation(a, b) end
---@alias game-Scripts-HubPresentation.UseLockedSystemObjectPresentation ...

function game.WeaponKitSpecialInteractPresentation(a, b, c) end
---@alias game-Scripts-HubPresentation.WeaponKitSpecialInteractPresentation ...

return game