---@meta SGG_Modding-Hades2GameDef-Scripts-HUDLogic
local game = {}

function game.ShowManaMeter() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowManaMeter ...

function game.HideAxeUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideAxeUI ...

function game.HideStaffUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideStaffUI ...

function game.UpdateResourceUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateResourceUI ...

function game.ShowCombatUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowCombatUI ...

function game.HideTraitUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideTraitUI ...

function game.UpdateRerollUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateRerollUI ...

function game.HUDHideTrait(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HUDHideTrait ...

function game.UpdateAxeUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateAxeUI ...

function game.HideMoneyUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideMoneyUI ...

function game.HideResourceUIs(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideResourceUIs ...

function game.UpdateFamiliarIconUses() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateFamiliarIconUses ...

function game.TraitUIDeactivateTrait(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.TraitUIDeactivateTrait ...

function game.HideHealthUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideHealthUI ...

function game.UpdateMoneyUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateMoneyUI ...

function game.ShowMoneyUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowMoneyUI ...

function game.HideManaMeter(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideManaMeter ...

function game.ShowAmmoUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowAmmoUI ...

function game.ShowHealthUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowHealthUI ...

function game.UpdateTraitSummary(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateTraitSummary ...

function game.TraitUIActivateTraits() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.TraitUIActivateTraits ...

function game.HideTorchUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideTorchUI ...

function game.ShowAxeUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowAxeUI ...

function game.ShowTraitUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowTraitUI ...

function game.GetTraitWithSlot(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.GetTraitWithSlot ...

function game.HideDaggerUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideDaggerUI ...

function game.ShowStaffUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowStaffUI ...

function game.ShowTorchUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowTorchUI ...

function game.ShowResourceUIs(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowResourceUIs ...

function game.RecreateLifePips() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.RecreateLifePips ...

function game.UpdateHealthUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateHealthUI ...

function game.UpdateManaMeterUIReal() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateManaMeterUIReal ...

function game.GetExistingUITrait(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.GetExistingUITrait ...

function game.HideCombatUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideCombatUI ...

function game.HideAfterDelay() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideAfterDelay ...

function game.UpdateLifePips(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateLifePips ...

function game.TraitUIUpdateText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.TraitUIUpdateText ...

function game.UpdateDaggerUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateDaggerUI ...

function game.UpdateAmmoUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateAmmoUI ...

function game.GetTraitTooltip(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.GetTraitTooltip ...

function game.HUDShowTrait(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HUDShowTrait ...

function game.UpdateTorchUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateTorchUI ...

function game.UpdateManaMeterUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateManaMeterUI ...

function game.GetTraitTooltipTitle(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.GetTraitTooltipTitle ...

function game.TraitUIAdd(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.TraitUIAdd ...

function game.StartHideAfterDelayThread() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.StartHideAfterDelayThread ...

function game.ShowRerollUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowRerollUI ...

function game.GetTraitIcon(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.GetTraitIcon ...

function game.IsExistingTraitShown(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.IsExistingTraitShown ...

function game.HideRerollUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideRerollUI ...

function game.TraitUIRemove(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.TraitUIRemove ...

function game.TraitUIActivateTrait(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.TraitUIActivateTrait ...

function game.ResetUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ResetUI ...

function game.GetExistingUITraitName(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.GetExistingUITraitName ...

function game.UpdateTraitNumber(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UpdateTraitNumber ...

function game.TraitUICreateText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.TraitUICreateText ...

function game.HideAmmoUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.HideAmmoUI ...

function game.UnblockCombatUI(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.UnblockCombatUI ...

function game.ShowDaggerUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.ShowDaggerUI ...

function game.GetTraitFrame(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-HUDLogic.GetTraitFrame ...

return game