---@meta game-Scripts-InteractPresentation
local game = {}

function game.CantAffordWeaponKitPresentation(a) end
---@alias game-Scripts-InteractPresentation.CantAffordWeaponKitPresentation ...

function game.ErisLitterPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.ErisLitterPresentation ...

function game.GetEquippedWeaponValue(a) end
---@alias game-Scripts-InteractPresentation.GetEquippedWeaponValue ...

function game.GhostRecruitSpecialInteractPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.GhostRecruitSpecialInteractPresentation ...

function game.LightRangedSalute(a, b) end
---@alias game-Scripts-InteractPresentation.LightRangedSalute ...

function game.ManaDropUsePresentation(a, b) end
---@alias game-Scripts-InteractPresentation.ManaDropUsePresentation ...

function game.NarcissusDropPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.NarcissusDropPresentation ...

function game.NarcissusPreDropPresentation(a, b) end
---@alias game-Scripts-InteractPresentation.NarcissusPreDropPresentation ...

function game.PlantAdmirePresentation(a, b) end
---@alias game-Scripts-InteractPresentation.PlantAdmirePresentation ...

function game.PlayInteractAnimation(a, b) end
---@alias game-Scripts-InteractPresentation.PlayInteractAnimation ...

function game.PlayUnequipAnimation(a) end
---@alias game-Scripts-InteractPresentation.PlayUnequipAnimation ...

function game.PlayWeaponEquipAnimation(a) end
---@alias game-Scripts-InteractPresentation.PlayWeaponEquipAnimation ...

function game.PostWeaponKitUnlockPresentation(a) end
---@alias game-Scripts-InteractPresentation.PostWeaponKitUnlockPresentation ...

function game.PreNarrativeUnequipAnimation() end
---@alias game-Scripts-InteractPresentation.PreNarrativeUnequipAnimation ...

function game.PreWeaponKitUnlockPresentation(a) end
---@alias game-Scripts-InteractPresentation.PreWeaponKitUnlockPresentation ...

function game.RemoveInteractAnimationInputBlock() end
---@alias game-Scripts-InteractPresentation.RemoveInteractAnimationInputBlock ...

function game.SpecialInteractLightRanged(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractLightRanged ...

function game.SpecialInteractSalute(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSalute ...

function game.SpecialInteractSaluteBroker(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSaluteBroker ...

function game.SpecialInteractSaluteInterrupt(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSaluteInterrupt ...

function game.SpecialInteractShade(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractShade ...

function game.SpecialInteractSirenFan(a, b) end
---@alias game-Scripts-InteractPresentation.SpecialInteractSirenFan ...

function game.SpellPotionRefillPresentation(a, b, c) end
---@alias game-Scripts-InteractPresentation.SpellPotionRefillPresentation ...

function game.WeaponUnlockedPresentation(a) end
---@alias game-Scripts-InteractPresentation.WeaponUnlockedPresentation ...

return game