---@meta game-Scripts-InteractLogic
local game = {}

function game.AddControlBlock(a, b) end
---@alias game-Scripts-InteractLogic.AddControlBlock ...

function game.AddInteractBlock(a, b) end
---@alias game-Scripts-InteractLogic.AddInteractBlock ...

function game.AddKeepsakeCharge(a) end
---@alias game-Scripts-InteractLogic.AddKeepsakeCharge ...

function game.ApplyConsumableItemResourceMultiplier(a, b) end
---@alias game-Scripts-InteractLogic.ApplyConsumableItemResourceMultiplier ...

function game.ArachneArmorApply(a, b) end
---@alias game-Scripts-InteractLogic.ArachneArmorApply ...

function game.AttemptPanelReroll(a, b) end
---@alias game-Scripts-InteractLogic.AttemptPanelReroll ...

function game.AttemptReroll(a, b) end
---@alias game-Scripts-InteractLogic.AttemptReroll ...

function game.AttemptRerollDoor(a, b) end
---@alias game-Scripts-InteractLogic.AttemptRerollDoor ...

function game.AttemptRerollFieldsDoor(a, b) end
---@alias game-Scripts-InteractLogic.AttemptRerollFieldsDoor ...

function game.AttemptRerollShipWheel(a, b) end
---@alias game-Scripts-InteractLogic.AttemptRerollShipWheel ...

function game.AttemptUseChallengeSwitch(a, b, c) end
---@alias game-Scripts-InteractLogic.AttemptUseChallengeSwitch ...

function game.ClearCombatControlBlock(a) end
---@alias game-Scripts-InteractLogic.ClearCombatControlBlock ...

function game.CreateConsumableItem(a, b, c, d) end
---@alias game-Scripts-InteractLogic.CreateConsumableItem ...

function game.CreateConsumableItemFromData(a, b, c, d) end
---@alias game-Scripts-InteractLogic.CreateConsumableItemFromData ...

function game.DelayedHeal(a, b, c) end
---@alias game-Scripts-InteractLogic.DelayedHeal ...

function game.FinishedEndVoiceLines(a, b, c) end
---@alias game-Scripts-InteractLogic.FinishedEndVoiceLines ...

function game.GetGenusName(a) end
---@alias game-Scripts-InteractLogic.GetGenusName ...

function game.GetRampedConsumableData(a, b, c) end
---@alias game-Scripts-InteractLogic.GetRampedConsumableData ...

function game.GetSecretDoorCost() end
---@alias game-Scripts-InteractLogic.GetSecretDoorCost ...

function game.GushMoney(a) end
---@alias game-Scripts-InteractLogic.GushMoney ...

function game.HandleLootPickup(a, b, c) end
---@alias game-Scripts-InteractLogic.HandleLootPickup ...

function game.HandleNemesisEncounterReward(a, b) end
---@alias game-Scripts-InteractLogic.HandleNemesisEncounterReward ...

function game.HasUsed(a) end
---@alias game-Scripts-InteractLogic.HasUsed ...

function game.HasUsedThisRun(a) end
---@alias game-Scripts-InteractLogic.HasUsedThisRun ...

function game.NPCRewardDrop(a, b) end
---@alias game-Scripts-InteractLogic.NPCRewardDrop ...

function game.NPCRewardDropPreProcess(a, b, c) end
---@alias game-Scripts-InteractLogic.NPCRewardDropPreProcess ...

function game.NPCRewardDropPreProcessArgs(a, b, c) end
---@alias game-Scripts-InteractLogic.NPCRewardDropPreProcessArgs ...

function game.PickupWeaponKit(a) end
---@alias game-Scripts-InteractLogic.PickupWeaponKit ...

function game.RecordConsumableItem(a) end
---@alias game-Scripts-InteractLogic.RecordConsumableItem ...

function game.RecordUse(a, b) end
---@alias game-Scripts-InteractLogic.RecordUse ...

function game.RemoveControlBlock(a, b) end
---@alias game-Scripts-InteractLogic.RemoveControlBlock ...

function game.RemoveInteractBlock(a, b) end
---@alias game-Scripts-InteractLogic.RemoveInteractBlock ...

function game.SacrificeHealth(a) end
---@alias game-Scripts-InteractLogic.SacrificeHealth ...

function game.SacrificeHealthAndHeal(a) end
---@alias game-Scripts-InteractLogic.SacrificeHealthAndHeal ...

function game.SetupResourceText(a) end
---@alias game-Scripts-InteractLogic.SetupResourceText ...

function game.StartedEndVoiceLines(a, b, c) end
---@alias game-Scripts-InteractLogic.StartedEndVoiceLines ...

function game.ToggleCombatControl(a, b, c) end
---@alias game-Scripts-InteractLogic.ToggleCombatControl ...

function game.TogglePlayerMove(a, b) end
---@alias game-Scripts-InteractLogic.TogglePlayerMove ...

function game.UseChallengeSwitch(a) end
---@alias game-Scripts-InteractLogic.UseChallengeSwitch ...

function game.UseConsumableItem(a, b, c) end
---@alias game-Scripts-InteractLogic.UseConsumableItem ...

function game.UseHealthFountain(a, b) end
---@alias game-Scripts-InteractLogic.UseHealthFountain ...

function game.UseInspectPoint(a, b, c) end
---@alias game-Scripts-InteractLogic.UseInspectPoint ...

function game.UseLoot(a, b, c) end
---@alias game-Scripts-InteractLogic.UseLoot ...

function game.UseNPC(a, b, c) end
---@alias game-Scripts-InteractLogic.UseNPC ...

function game.UseNPCPostTextLines(a, b, c) end
---@alias game-Scripts-InteractLogic.UseNPCPostTextLines ...

function game.UseWeaponKit(a, b, c) end
---@alias game-Scripts-InteractLogic.UseWeaponKit ...

function game.UseWellShop(a) end
---@alias game-Scripts-InteractLogic.UseWellShop ...

return game