---@meta game-Scripts-KeepsakeLogic
local game = {}

function game.AdvanceKeepsake() end
---@alias game-Scripts-KeepsakeLogic.AdvanceKeepsake ...

function game.CanFreeSwapKeepsakes() end
---@alias game-Scripts-KeepsakeLogic.CanFreeSwapKeepsakes ...

function game.CheckOverTimeManaRefund(a, b) end
---@alias game-Scripts-KeepsakeLogic.CheckOverTimeManaRefund ...

function game.CheckSpeedKeepsakeTrigger(a, b) end
---@alias game-Scripts-KeepsakeLogic.CheckSpeedKeepsakeTrigger ...

function game.CreateKeepsakeIcon(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.CreateKeepsakeIcon ...

function game.DamageAfterInterval(a, b) end
---@alias game-Scripts-KeepsakeLogic.DamageAfterInterval ...

function game.EquipAssist(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.EquipAssist ...

function game.EquipKeepsake(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.EquipKeepsake ...

function game.EquipLastAssistTrait(a, b) end
---@alias game-Scripts-KeepsakeLogic.EquipLastAssistTrait ...

function game.EquipLastAwardTrait(a, b) end
---@alias game-Scripts-KeepsakeLogic.EquipLastAwardTrait ...

function game.FastClearThread(a, b) end
---@alias game-Scripts-KeepsakeLogic.FastClearThread ...

function game.GetAssistKeepsakeLevel(a) end
---@alias game-Scripts-KeepsakeLogic.GetAssistKeepsakeLevel ...

function game.GetKeepsakeChambersToNextLevel(a) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeChambersToNextLevel ...

function game.GetKeepsakeData(a) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeData ...

function game.GetKeepsakeLevel(a, b) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeLevel ...

function game.GetKeepsakeProgress(a) end
---@alias game-Scripts-KeepsakeLogic.GetKeepsakeProgress ...

function game.HandleUpgradeToggle(a, b, c) end
---@alias game-Scripts-KeepsakeLogic.HandleUpgradeToggle ...

function game.HasNewTraits() end
---@alias game-Scripts-KeepsakeLogic.HasNewTraits ...

function game.IsKeepsakeMaxed(a) end
---@alias game-Scripts-KeepsakeLogic.IsKeepsakeMaxed ...

function game.KeepsakeHasHeroicRarity(a) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeHasHeroicRarity ...

function game.KeepsakeScreenClose(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeScreenClose ...

function game.KeepsakeScreenShowInfo(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeScreenShowInfo ...

function game.KeepsakeScreenUpdateActionBar(a, b) end
---@alias game-Scripts-KeepsakeLogic.KeepsakeScreenUpdateActionBar ...

function game.ManaOverTimeRefund(a, b, c, d) end
---@alias game-Scripts-KeepsakeLogic.ManaOverTimeRefund ...

function game.MouseOffKeepsake(a) end
---@alias game-Scripts-KeepsakeLogic.MouseOffKeepsake ...

function game.MouseOverKeepsake(a) end
---@alias game-Scripts-KeepsakeLogic.MouseOverKeepsake ...

function game.OpenKeepsakeRackScreen(a) end
---@alias game-Scripts-KeepsakeLogic.OpenKeepsakeRackScreen ...

function game.SetSelectedFrame(a, b) end
---@alias game-Scripts-KeepsakeLogic.SetSelectedFrame ...

function game.SetupBlockDeathThread() end
---@alias game-Scripts-KeepsakeLogic.SetupBlockDeathThread ...

function game.SetupDodgeBonus(a, b) end
---@alias game-Scripts-KeepsakeLogic.SetupDodgeBonus ...

function game.UnequipAssist(a, b) end
---@alias game-Scripts-KeepsakeLogic.UnequipAssist ...

function game.UnequipKeepsake(a, b) end
---@alias game-Scripts-KeepsakeLogic.UnequipKeepsake ...

function game.UpdateGiftRackShineStatus(a) end
---@alias game-Scripts-KeepsakeLogic.UpdateGiftRackShineStatus ...

function game.UseKeepsakeRack(a, b) end
---@alias game-Scripts-KeepsakeLogic.UseKeepsakeRack ...

return game