---@meta SGG_Modding-Hades2GameDef-Scripts-MailboxLogic
local game = {}

function game.CheckCharonPointsOwed(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.CheckCharonPointsOwed ...

function game.CloseMailboxScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.CloseMailboxScreen ...

function game.GenerateMailboxItems(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.GenerateMailboxItems ...

function game.HandleMailboxPurchase(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.HandleMailboxPurchase ...

function game.MailboxScreenDisplayCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.MailboxScreenDisplayCategory ...

function game.MailboxScreenSelectCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.MailboxScreenSelectCategory ...

function game.MailboxScreenUpdateResourceStatus(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.MailboxScreenUpdateResourceStatus ...

function game.MailboxTimeTick(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.MailboxTimeTick ...

function game.OpenMailboxScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.OpenMailboxScreen ...

function game.SetupMailboxStatus(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.SetupMailboxStatus ...

function game.UpdateMailboxScreenInteractionText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.UpdateMailboxScreenInteractionText ...

function game.UseMailboxDeliveryReady(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.UseMailboxDeliveryReady ...

function game.UseMailboxObject(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MailboxLogic.UseMailboxObject ...

return game