---@meta game-Scripts-ManaLogic
local game = {}

function game.CalculateManaGain(a, b) end
---@alias game-Scripts-ManaLogic.CalculateManaGain ...

function game.CastCircleManaRegen() end
---@alias game-Scripts-ManaLogic.CastCircleManaRegen ...

function game.CheckManaOnHit(a, b, c) end
---@alias game-Scripts-ManaLogic.CheckManaOnHit ...

function game.CheckManaRefund(a, b) end
---@alias game-Scripts-ManaLogic.CheckManaRefund ...

function game.CheckOnManaSpendPowers(a, b) end
---@alias game-Scripts-ManaLogic.CheckOnManaSpendPowers ...

function game.DrainManaPerSecond(a) end
---@alias game-Scripts-ManaLogic.DrainManaPerSecond ...

function game.GetHeroMaxAvailableMana() end
---@alias game-Scripts-ManaLogic.GetHeroMaxAvailableMana ...

function game.GetLowestManaCost() end
---@alias game-Scripts-ManaLogic.GetLowestManaCost ...

function game.GetManaCost(a, b, c) end
---@alias game-Scripts-ManaLogic.GetManaCost ...

function game.GetManaReservationCost(a) end
---@alias game-Scripts-ManaLogic.GetManaReservationCost ...

function game.IdleManaRegen(a) end
---@alias game-Scripts-ManaLogic.IdleManaRegen ...

function game.IdleManaRegenSetup(a, b) end
---@alias game-Scripts-ManaLogic.IdleManaRegenSetup ...

function game.InCastCircleManaRegenSetup(a, b) end
---@alias game-Scripts-ManaLogic.InCastCircleManaRegenSetup ...

function game.IsOutOfMana() end
---@alias game-Scripts-ManaLogic.IsOutOfMana ...

function game.ManaDelta(a, b) end
---@alias game-Scripts-ManaLogic.ManaDelta ...

function game.ManaFountainReady(a) end
---@alias game-Scripts-ManaLogic.ManaFountainReady ...

function game.ManaRegen() end
---@alias game-Scripts-ManaLogic.ManaRegen ...

function game.ManaRegenSetup(a, b) end
---@alias game-Scripts-ManaLogic.ManaRegenSetup ...

function game.MovingManaRegen(a) end
---@alias game-Scripts-ManaLogic.MovingManaRegen ...

function game.MovingManaRegenSetup(a, b) end
---@alias game-Scripts-ManaLogic.MovingManaRegenSetup ...

function game.RefillMana() end
---@alias game-Scripts-ManaLogic.RefillMana ...

function game.ReserveMana(a, b) end
---@alias game-Scripts-ManaLogic.ReserveMana ...

function game.UnreserveMana(a) end
---@alias game-Scripts-ManaLogic.UnreserveMana ...

function game.UpdateWeaponMana(a, b) end
---@alias game-Scripts-ManaLogic.UpdateWeaponMana ...

function game.UseManaFountain(a, b) end
---@alias game-Scripts-ManaLogic.UseManaFountain ...

return game