---@meta SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic
local game = {}

function game.CancelExitBelowLimitScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.CancelExitBelowLimitScreen ...

function game.CancelExitCardUpgradeInfoScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.CancelExitCardUpgradeInfoScreen ...

function game.CancelExitMetaUpgradeCardPrompt(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.CancelExitMetaUpgradeCardPrompt ...

function game.CancelExitNoUpgradeInfoScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.CancelExitNoUpgradeInfoScreen ...

function game.CloseGraspLimitScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.CloseGraspLimitScreen ...

function game.CloseMetaUpgradeCardPromptScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.CloseMetaUpgradeCardPromptScreen ...

function game.ConfirmExitBelowLimitScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.ConfirmExitBelowLimitScreen ...

function game.ConfirmExitCardUpgradeInfoScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.ConfirmExitCardUpgradeInfoScreen ...

function game.ConfirmExitMetaUpgradeCardPrompt(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.ConfirmExitMetaUpgradeCardPrompt ...

function game.ConfirmExitNoUpgradeInfoScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.ConfirmExitNoUpgradeInfoScreen ...

function game.OpenBelowLimitScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.OpenBelowLimitScreen ...

function game.OpenCardUpgradeInfoScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.OpenCardUpgradeInfoScreen ...

function game.OpenGraspLimitScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.OpenGraspLimitScreen ...

function game.OpenMetaUpgradeCardPromptScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.OpenMetaUpgradeCardPromptScreen ...

function game.OpenNoUpgradeInfoScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardPromptScreenLogic.OpenNoUpgradeInfoScreen ...

return game