---@meta SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic
local game = {}

function game.CreateMetaUpgradeCard(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.CreateMetaUpgradeCard ...

function game.DoMetaUpgradePatches() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.DoMetaUpgradePatches ...

function game.MetaUpgradeCardScreenPinItem(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardScreenPinItem ...

function game.OpenMetaUpgradeCardScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.OpenMetaUpgradeCardScreen ...

function game.GetCoordsInRow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetCoordsInRow ...

function game.GetNeighboringCoords(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetNeighboringCoords ...

function game.DoCardSwap(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.DoCardSwap ...

function game.MouseOffMetaUpgradeCardLimit(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.MouseOffMetaUpgradeCardLimit ...

function game.NoMetaUpgradeCardsUnlocked() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.NoMetaUpgradeCardsUnlocked ...

function game.HasAvailableMetaUpgradeCapacity(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.HasAvailableMetaUpgradeCapacity ...

function game.MouseOverMetaUpgradeCardLimit(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.MouseOverMetaUpgradeCardLimit ...

function game.UpdateMetaUpgradeCardAnimation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCardAnimation ...

function game.MouseOffMetaUpgrade(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.MouseOffMetaUpgrade ...

function game.EquipMetaUpgradeButton(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.EquipMetaUpgradeButton ...

function game.GetCurrentMetaUpgradeCost() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetCurrentMetaUpgradeCost ...

function game.IncreaseMetaUpgradeCardLimit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.IncreaseMetaUpgradeCardLimit ...

function game.CloseMetaUpgradeCardScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.CloseMetaUpgradeCardScreen ...

function game.UpdateMetaUpgradeCardInteractionText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCardInteractionText ...

function game.HasNeighboringUnlockedCards(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.HasNeighboringUnlockedCards ...

function game.GetMetaUpgradeCardButton(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetMetaUpgradeCardButton ...

function game.SelectMetaUpgradeButton(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.SelectMetaUpgradeButton ...

function game.UpdateMetaUpgradeCostDisplay(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCostDisplay ...

function game.EnterUpgradeMode(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.EnterUpgradeMode ...

function game.HandleCardSwapInput(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.HandleCardSwapInput ...

function game.UpdateMetaUpgradeUnlockedCountCache() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeUnlockedCountCache ...

function game.MetaUpgradeCardAction(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardAction ...

function game.GetMetaUpgradeKey(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetMetaUpgradeKey ...

function game.GetMaxMetaUpgradeCost() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetMaxMetaUpgradeCost ...

function game.CheckAutoEquipCards(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.CheckAutoEquipCards ...

function game.UpdateMetaUpgradeCardState(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCardState ...

function game.MouseOverMetaUpgrade(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.MouseOverMetaUpgrade ...

function game.UpdateMetaUpgradeCostText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCostText ...

function game.GetCurrentMetaUpgradeLimitLevel() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetCurrentMetaUpgradeLimitLevel ...

function game.UpdateMetaUpgradeCard(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.UpdateMetaUpgradeCard ...

function game.GetZoomLevel() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.GetZoomLevel ...

function game.CanUpgradeCards() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.CanUpgradeCards ...

function game.CanIncreaseMetaUpgradeCardLimit() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.CanIncreaseMetaUpgradeCardLimit ...

function game.MetaUpgradeCardEquipped(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.MetaUpgradeCardEquipped ...

function game.CreateMetaUpgradeCards(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.CreateMetaUpgradeCards ...

function game.SetCardOnDelay(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.SetCardOnDelay ...

function game.RecordStartingMetaUpgrades(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.RecordStartingMetaUpgrades ...

function game.RecordMetaUpgradeChanges(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeCardScreenLogic.RecordMetaUpgradeChanges ...

return game