---@meta SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic
local game = {}

function game.AddRandomMetaUpgrades(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.AddRandomMetaUpgrades ...

function game.CastProjectileCleanup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.CastProjectileCleanup ...

function game.CheckAutoEquipRequirements(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.CheckAutoEquipRequirements ...

function game.CheckCastCompleteGraphic(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.CheckCastCompleteGraphic ...

function game.CheckWeaponCastChannelSlow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.CheckWeaponCastChannelSlow ...

function game.EndWeaponCastChannelSlow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.EndWeaponCastChannelSlow ...

function game.EquipMetaUpgrades(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.EquipMetaUpgrades ...

function game.EquipPreRunMetaUpgrades(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.EquipPreRunMetaUpgrades ...

function game.GetMetaUpgradeCardCoords(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.GetMetaUpgradeCardCoords ...

function game.GetMetaUpgradeLevel(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.GetMetaUpgradeLevel ...

function game.GrantMetaUpgradeCurrency(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.GrantMetaUpgradeCurrency ...

function game.GrantMetaUpgradeLastStands(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.GrantMetaUpgradeLastStands ...

function game.GrantMetaUpgradeRerolls(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.GrantMetaUpgradeRerolls ...

function game.InitializeMetaUpgradeState() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.InitializeMetaUpgradeState ...

function game.LastStandTimeSlow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.LastStandTimeSlow ...

function game.RefreshImpactSlow(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.RefreshImpactSlow ...

function game.RoomStatGrowth(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.RoomStatGrowth ...

function game.RunLastStandTimeSlow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.RunLastStandTimeSlow ...

function game.StartCastSlow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.StartCastSlow ...

function game.UnequipMetaUpgrades(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.UnequipMetaUpgrades ...

function game.UpdateMetaUpgradeCardAdjacencyBonuses() end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.UpdateMetaUpgradeCardAdjacencyBonuses ...

function game.UpgradeMetaUpgradeCurrency(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.UpgradeMetaUpgradeCurrency ...

function game.UpgradeMetaUpgradeLastStands(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.UpgradeMetaUpgradeLastStands ...

function game.UpgradeMetaUpgradeRerolls(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.UpgradeMetaUpgradeRerolls ...

function game.WeaponCastFired(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-MetaUpgradeLogic.WeaponCastFired ...

return game