---@meta game-Scripts-MetaUpgrades
local game = {}

function game.BiomeSpeedTimerLoop() end
---@alias game-Scripts-MetaUpgrades.BiomeSpeedTimerLoop ...

function game.CalculateHealingMultiplier() end
---@alias game-Scripts-MetaUpgrades.CalculateHealingMultiplier ...

function game.CalculateMetaPointMultiplier() end
---@alias game-Scripts-MetaUpgrades.CalculateMetaPointMultiplier ...

function game.CalculatePositiveHealingMultiplier() end
---@alias game-Scripts-MetaUpgrades.CalculatePositiveHealingMultiplier ...

function game.GetBaseAmmoReloadTime() end
---@alias game-Scripts-MetaUpgrades.GetBaseAmmoReloadTime ...

function game.GetMetaUpgradePrice(a, b) end
---@alias game-Scripts-MetaUpgrades.GetMetaUpgradePrice ...

function game.GetMetaUpgradePurchasePrice(a) end
---@alias game-Scripts-MetaUpgrades.GetMetaUpgradePurchasePrice ...

function game.GetMetaUpgradeRefundPrice(a, b) end
---@alias game-Scripts-MetaUpgrades.GetMetaUpgradeRefundPrice ...

function game.GetMetaUpgradeStatDelta(a) end
---@alias game-Scripts-MetaUpgrades.GetMetaUpgradeStatDelta ...

function game.GetMetaUpgradeTotalInvestment(a) end
---@alias game-Scripts-MetaUpgrades.GetMetaUpgradeTotalInvestment ...

function game.GetNulledMetaUpgradeCount() end
---@alias game-Scripts-MetaUpgrades.GetNulledMetaUpgradeCount ...

function game.GetNumMetaUpgradeLastStands() end
---@alias game-Scripts-MetaUpgrades.GetNumMetaUpgradeLastStands ...

function game.GetTotalStatChange(a, b) end
---@alias game-Scripts-MetaUpgrades.GetTotalStatChange ...

function game.IsBiomeTimerPaused() end
---@alias game-Scripts-MetaUpgrades.IsBiomeTimerPaused ...

function game.IsMetaUpgradeActive(a, b) end
---@alias game-Scripts-MetaUpgrades.IsMetaUpgradeActive ...

function game.IsMetaUpgradeSelected(a) end
---@alias game-Scripts-MetaUpgrades.IsMetaUpgradeSelected ...

function game.MetaUpgradePresentation(a) end
---@alias game-Scripts-MetaUpgrades.MetaUpgradePresentation ...

function game.StartSurfaceHealthPenalty(a, b) end
---@alias game-Scripts-MetaUpgrades.StartSurfaceHealthPenalty ...

function game.SurfaceHealthPenalty(a) end
---@alias game-Scripts-MetaUpgrades.SurfaceHealthPenalty ...

function game.UpdateSeenMetaUpgrades() end
---@alias game-Scripts-MetaUpgrades.UpdateSeenMetaUpgrades ...

return game