---@meta game-Scripts-NarrativeLogic
local game = {}

game.NarrativeThreadName = "NarrativeThreadName"
---@alias game-Scripts-NarrativeLogic.NarrativeThreadName ...

function game.AutoAdvanceNarration(a, b, c) end
---@alias game-Scripts-NarrativeLogic.AutoAdvanceNarration ...

function game.CancelSpeakingAnimation(a, b, c) end
---@alias game-Scripts-NarrativeLogic.CancelSpeakingAnimation ...

function game.CheckPartnerConversationData(a) end
---@alias game-Scripts-NarrativeLogic.CheckPartnerConversationData ...

function game.CheckPartnerConversations(a, b) end
---@alias game-Scripts-NarrativeLogic.CheckPartnerConversations ...

function game.DisplayTextLine(a, b, c, d, e) end
---@alias game-Scripts-NarrativeLogic.DisplayTextLine ...

function game.GetLastRunTextLinesOccured(a) end
---@alias game-Scripts-NarrativeLogic.GetLastRunTextLinesOccured ...

function game.GetNarrativeDataValue(a, b) end
---@alias game-Scripts-NarrativeLogic.GetNarrativeDataValue ...

function game.GetRandomEligibleTextLines(a, b, c, d) end
---@alias game-Scripts-NarrativeLogic.GetRandomEligibleTextLines ...

function game.GetTextLinesUseableStatus(a, b) end
---@alias game-Scripts-NarrativeLogic.GetTextLinesUseableStatus ...

function game.HasPlayedAnyTextLines(a, b) end
---@alias game-Scripts-NarrativeLogic.HasPlayedAnyTextLines ...

function game.IsTextLineEligible(a, b, c, d, e, f) end
---@alias game-Scripts-NarrativeLogic.IsTextLineEligible ...

function game.NarrativeInit() end
---@alias game-Scripts-NarrativeLogic.NarrativeInit ...

function game.NeedsUseableOff(a) end
---@alias game-Scripts-NarrativeLogic.NeedsUseableOff ...

function game.OnPartnerConversationSet(a, b) end
---@alias game-Scripts-NarrativeLogic.OnPartnerConversationSet ...

function game.PlayFirstEligibleTextLines(a, b) end
---@alias game-Scripts-NarrativeLogic.PlayFirstEligibleTextLines ...

function game.PlayRandomRemainingTextLines(a, b) end
---@alias game-Scripts-NarrativeLogic.PlayRandomRemainingTextLines ...

function game.PlayTextLine(a, b, c, d, e, f) end
---@alias game-Scripts-NarrativeLogic.PlayTextLine ...

function game.PlayTextLines(a, b, c) end
---@alias game-Scripts-NarrativeLogic.PlayTextLines ...

function game.ShowContinueArrow(a, b, c) end
---@alias game-Scripts-NarrativeLogic.ShowContinueArrow ...

return game