---@meta SGG_Modding-Hades2GameDef-Scripts-PowersLogic
local game = {}

function game.AddBlockEmpower(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AddBlockEmpower ...

function game.AddRandomChaosBlessing(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AddRandomChaosBlessing ...

function game.AddRandomHammer(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AddRandomHammer ...

function game.AddTalentPoints(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AddTalentPoints ...

function game.AddTraitResources(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AddTraitResources ...

function game.AmplifyKnockbackApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AmplifyKnockbackApply ...

function game.AmplifyKnockbackClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AmplifyKnockbackClear ...

function game.ApolloBlindStrike(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApolloBlindStrike ...

function game.ApolloPerfectDash(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApolloPerfectDash ...

function game.ApolloRetaliate(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApolloRetaliate ...

function game.ApplyAphroditeVulnerability(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApplyAphroditeVulnerability ...

function game.ApplyBurn(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApplyBurn ...

function game.ApplyDamageShare(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApplyDamageShare ...

function game.ApplyDashKnockup(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApplyDashKnockup ...

function game.ApplyOmegaBuff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApplyOmegaBuff ...

function game.ApplyRoot(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ApplyRoot ...

function game.AttachCastAtLocation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.AttachCastAtLocation ...

function game.CacheCurrentLifestealUses(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CacheCurrentLifestealUses ...

function game.ChaosBlessingBonus(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ChaosBlessingBonus ...

function game.ChaosManaDrain(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ChaosManaDrain ...

function game.ChaosStunSelf(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ChaosStunSelf ...

function game.ChargeSkullImpulse(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ChargeSkullImpulse ...

function game.CharmCrowd(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CharmCrowd ...

function game.CheckArmedApolloCast(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckArmedApolloCast ...

function game.CheckArmImput(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckArmImput ...

function game.CheckAxeCastArm(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckAxeCastArm ...

function game.CheckBlindVampOnHit(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckBlindVampOnHit ...

function game.CheckBurnConsumption(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckBurnConsumption ...

function game.CheckBurnConsumptionDelay(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckBurnConsumptionDelay ...

function game.CheckBurnDeathExplosion(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckBurnDeathExplosion ...

function game.CheckCastAphroditeVulnerabilityApply(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckCastAphroditeVulnerabilityApply ...

function game.CheckCastBurnApply(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckCastBurnApply ...

function game.CheckCastDetach(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckCastDetach ...

function game.CheckCastSummonDamage(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckCastSummonDamage ...

function game.CheckCastVolley(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckCastVolley ...

function game.CheckClearCastCount(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckClearCastCount ...

function game.CheckClearCastManaRefund(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckClearCastManaRefund ...

function game.CheckDaggerBlock(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckDaggerBlock ...

function game.CheckDaggerCritCharges(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckDaggerCritCharges ...

function game.CheckDamageShareJump(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckDamageShareJump ...

function game.CheckFireballSpawn(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckFireballSpawn ...

function game.CheckHeraManaRestore(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckHeraManaRestore ...

function game.CheckIcarusExplosion(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckIcarusExplosion ...

function game.CheckLavaPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckLavaPresentation ...

function game.CheckLavaSplashPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckLavaSplashPresentation ...

function game.CheckLeapCritCharges(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckLeapCritCharges ...

function game.CheckLinkDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckLinkDeath ...

function game.CheckLobDetonate(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckLobDetonate ...

function game.CheckManaBurst(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckManaBurst ...

function game.CheckMassiveAttack(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckMassiveAttack ...

function game.CheckMaximumLink(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckMaximumLink ...

function game.CheckOmegaZeroBurn(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckOmegaZeroBurn ...

function game.CheckOnDamagedPowers(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckOnDamagedPowers ...

function game.CheckOnDeathPowers(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckOnDeathPowers ...

function game.CheckOnHitPowers(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckOnHitPowers ...

function game.CheckOnImpactPowers(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckOnImpactPowers ...

function game.CheckPerfectAxeCrit(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckPerfectAxeCrit ...

function game.CheckPerfectChargeRefund(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckPerfectChargeRefund ...

function game.CheckPlayerOnFirePowers(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckPlayerOnFirePowers ...

function game.CheckPoseidonKnockback(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckPoseidonKnockback ...

function game.CheckPoseidonManaDrop(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckPoseidonManaDrop ...

function game.CheckPoseidonSplash(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckPoseidonSplash ...

function game.CheckProjectilePull(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckProjectilePull ...

function game.CheckProjectileSpawn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckProjectileSpawn ...

function game.CheckSkullImpulseStart() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckSkullImpulseStart ...

function game.CheckSpawnArmorDamage(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckSpawnArmorDamage ...

function game.CheckSpawnCurseDamage(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckSpawnCurseDamage ...

function game.CheckSpawnZeusDamage(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckSpawnZeusDamage ...

function game.CheckStaffSelfHit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckStaffSelfHit ...

function game.CheckSteam(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckSteam ...

function game.CheckSupportingFire(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckSupportingFire ...

function game.CheckTimedKillBuff(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckTimedKillBuff ...

function game.CheckTorchDetonation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckTorchDetonation ...

function game.CheckTorchRepeatStrike(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckTorchRepeatStrike ...

function game.CheckWeaponAmmoFire(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckWeaponAmmoFire ...

function game.CheckWeaponFullManaFire(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckWeaponFullManaFire ...

function game.CheckWeaponInvisibleFire(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckWeaponInvisibleFire ...

function game.CheckWorldSlowWeapon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckWorldSlowWeapon ...

function game.CheckZeusManaBolt(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckZeusManaBolt ...

function game.CheckZeusProjectile(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CheckZeusProjectile ...

function game.CleanupRaiseDeadEncounter(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CleanupRaiseDeadEncounter ...

function game.ClearOriginMarker(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ClearOriginMarker ...

function game.ClearRoot(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ClearRoot ...

function game.ConvertArmorToHealth(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ConvertArmorToHealth ...

function game.CreateAlliedEnemy(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CreateAlliedEnemy ...

function game.CreateZeusBolt(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CreateZeusBolt ...

function game.CurseRetaliate(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.CurseRetaliate ...

function game.DaggerBlockSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DaggerBlockSetup ...

function game.DaggerFinalHitIncrease(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DaggerFinalHitIncrease ...

function game.DaggerLastHitSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DaggerLastHitSetup ...

function game.DamageOverTimeApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DamageOverTimeApply ...

function game.DamageOverTimeClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DamageOverTimeClear ...

function game.DemeterCastBlast(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DemeterCastBlast ...

function game.DemeterSprintBlast(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DemeterSprintBlast ...

function game.DemeterSprintStormDetach(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DemeterSprintStormDetach ...

function game.DiminishingDodge(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DiminishingDodge ...

function game.DiminishingDodgeSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DiminishingDodgeSetup ...

function game.DoCurseDamage(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DoCurseDamage ...

function game.DoLinkDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DoLinkDeath ...

function game.DoubleBurnBoon(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DoubleBurnBoon ...

function game.DoZeusSpawnDamage(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DoZeusSpawnDamage ...

function game.DropOriginMarker(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.DropOriginMarker ...

function game.EndAxeSturdy() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.EndAxeSturdy ...

function game.EndLobSturdy() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.EndLobSturdy ...

function game.EndTimedBuff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.EndTimedBuff ...

function game.EnlargeApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.EnlargeApply ...

function game.EnlargeClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.EnlargeClear ...

function game.FireRallyHeal(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.FireRallyHeal ...

function game.FireRallyThread(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.FireRallyThread ...

function game.FireWeaponWithinRange(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.FireWeaponWithinRange ...

function game.FreezeFrameApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.FreezeFrameApply ...

function game.FreezeFrameClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.FreezeFrameClear ...

function game.FreezeStunApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.FreezeStunApply ...

function game.GetNearestEnemyArgs(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.GetNearestEnemyArgs ...

function game.GetRequiredForceToEnemy(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.GetRequiredForceToEnemy ...

function game.GetTotalGodEnhancement() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.GetTotalGodEnhancement ...

function game.GiveDurationHammer(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.GiveDurationHammer ...

function game.GrantRandomManaTrait(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.GrantRandomManaTrait ...

function game.HadesInvisibility() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HadesInvisibility ...

function game.HadesInvisibilitySetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HadesInvisibilitySetup ...

function game.HadesInvisibleClear() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HadesInvisibleClear ...

function game.HadesRetaliate(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HadesRetaliate ...

function game.HandleOnSprintEffect() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HandleOnSprintEffect ...

function game.HeavyArmorExpire(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HeavyArmorExpire ...

function game.HeavyArmorSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HeavyArmorSetup ...

function game.HephaestusArmor(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HephaestusArmor ...

function game.HeraManaRestoreEligible(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HeraManaRestoreEligible ...

function game.HeraRetaliate(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HeraRetaliate ...

function game.HeraSprintLink(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HeraSprintLink ...

function game.HeraSprintMana(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HeraSprintMana ...

function game.HeraSprintSuction(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HeraSprintSuction ...

function game.HestiaBlockSpend(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HestiaBlockSpend ...

function game.HestiaSprintDefense(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HestiaSprintDefense ...

function game.HestiaSprintSplash(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.HestiaSprintSplash ...

function game.IcarusArmorExplosion(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.IcarusArmorExplosion ...

function game.IcarusArmorInvulnerability(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.IcarusArmorInvulnerability ...

function game.IcarusHazardCast(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.IcarusHazardCast ...

function game.IcarusSelfDamage(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.IcarusSelfDamage ...

function game.ImpactSlowApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ImpactSlowApply ...

function game.InsideCastBuffApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.InsideCastBuffApply ...

function game.InsideCastBuffClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.InsideCastBuffClear ...

function game.InterruptRegen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.InterruptRegen ...

function game.LavaSlowApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.LavaSlowApply ...

function game.LavaSlowClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.LavaSlowClear ...

function game.ManageProjectilePull(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ManageProjectilePull ...

function game.ManageZeusCloud(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ManageZeusCloud ...

function game.MarkRandomNearby(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.MarkRandomNearby ...

function game.MassiveAttackSetup(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.MassiveAttackSetup ...

function game.MultiplyCurrentArmor(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.MultiplyCurrentArmor ...

function game.MultiplySameRoomRewards(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.MultiplySameRoomRewards ...

function game.NearbyVulnerabilityApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.NearbyVulnerabilityApply ...

function game.NearbyVulnerabilityClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.NearbyVulnerabilityClear ...

function game.NearbyVulnerabilityThread(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.NearbyVulnerabilityThread ...

function game.OnDemeterCastArmed(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OnDemeterCastArmed ...

function game.OnHephCastArmed(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OnHephCastArmed ...

function game.OnHitStunApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OnHitStunApply ...

function game.OnPoseidonCastArmed(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OnPoseidonCastArmed ...

function game.OnPoseidonCastArmedExtension(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OnPoseidonCastArmedExtension ...

function game.OnZeusCastArmed(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OnZeusCastArmed ...

function game.OutOfCombatRegen(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OutOfCombatRegen ...

function game.OutOfCombatRegenSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.OutOfCombatRegenSetup ...

function game.PeriodicMark(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PeriodicMark ...

function game.PermanentSwitchWeapon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PermanentSwitchWeapon ...

function game.PlayerWorldSlow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PlayerWorldSlow ...

function game.PlayerWorldSlowSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PlayerWorldSlowSetup ...

function game.PolymorphEnlargeClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PolymorphEnlargeClear ...

function game.PoseidonSprintBackSplash(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PoseidonSprintBackSplash ...

function game.PoseidonSprintBall(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PoseidonSprintBall ...

function game.PoseidonSprintBlastDetach(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PoseidonSprintBlastDetach ...

function game.PoseidonSprintBlastRefresh(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PoseidonSprintBlastRefresh ...

function game.PoseidonSprintFollow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PoseidonSprintFollow ...

function game.PoseidonSprintSpend(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PoseidonSprintSpend ...

function game.PoseidonSprintSplash(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PoseidonSprintSplash ...

function game.PostProcessDashProperties(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PostProcessDashProperties ...

function game.PostProcessDashThread(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PostProcessDashThread ...

function game.PreDamageBoss(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PreDamageBoss ...

function game.PrepOnHitEmpower(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.PrepOnHitEmpower ...

function game.ProcessDashProperties(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ProcessDashProperties ...

function game.RaiseKilledEnemy(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RaiseKilledEnemy ...

function game.RecordSecondStageApolloCast(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RecordSecondStageApolloCast ...

function game.ReduceKillBuff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ReduceKillBuff ...

function game.RemoveArcana(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RemoveArcana ...

function game.RemoveCastVolleyProjectile(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RemoveCastVolleyProjectile ...

function game.RemoveCritVolley(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RemoveCritVolley ...

function game.RemoveLeapCritVolley(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RemoveLeapCritVolley ...

function game.RemoveWeaponAmmoFire(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RemoveWeaponAmmoFire ...

function game.RemoveWeaponFullManaFire(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RemoveWeaponFullManaFire ...

function game.RemoveWeaponInvisibleFire(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.RemoveWeaponInvisibleFire ...

function game.ResetPerfectAxeCrit(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ResetPerfectAxeCrit ...

function game.SetupAnywhereCast(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SetupAnywhereCast ...

function game.SetupCastCast(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SetupCastCast ...

function game.SetupClearCastUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SetupClearCastUI ...

function game.SetupExShields(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SetupExShields ...

function game.SetupHadesCast(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SetupHadesCast ...

function game.SetupPerfectCritUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SetupPerfectCritUI ...

function game.SetupSkullImpulseUI() end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SetupSkullImpulseUI ...

function game.SkullImpulseTransform(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SkullImpulseTransform ...

function game.SprintShieldSetup(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SprintShieldSetup ...

function game.StaffEXHitHeal(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StaffEXHitHeal ...

function game.StartAxeSturdy(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StartAxeSturdy ...

function game.StartChaosTimer(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StartChaosTimer ...

function game.StartExBurn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StartExBurn ...

function game.StartHermesKeepsakeTimer(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StartHermesKeepsakeTimer ...

function game.StartHitShield(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StartHitShield ...

function game.StartLobSturdy(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StartLobSturdy ...

function game.StasisApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StasisApply ...

function game.StasisClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StasisClear ...

function game.StasisStunApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StasisStunApply ...

function game.StasisStunClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.StasisStunClear ...

function game.SturdySetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.SturdySetup ...

function game.TimedBuffSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.TimedBuffSetup ...

function game.TimeSlowApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.TimeSlowApply ...

function game.TimeSlowClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.TimeSlowClear ...

function game.TimeSlowPerfectDash(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.TimeSlowPerfectDash ...

function game.TimeSlowUpdate(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.TimeSlowUpdate ...

function game.TorchSprintRecall(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.TorchSprintRecall ...

function game.TraitReserveMana(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.TraitReserveMana ...

function game.WeakCrowdMana(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.WeakCrowdMana ...

function game.ZeusRetaliate(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ZeusRetaliate ...

function game.ZeusSprintSpend(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ZeusSprintSpend ...

function game.ZeusSprintZap(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-PowersLogic.ZeusSprintZap ...

return game