---@meta SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic
local game = {}

function game.CashOutQuest(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.CashOutQuest ...

function game.CheckQuestStatus(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.CheckQuestStatus ...

function game.CloseQuestLogScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.CloseQuestLogScreen ...

function game.HasActiveQuestForItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.HasActiveQuestForItem ...

function game.HasActiveQuestForName(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.HasActiveQuestForName ...

function game.HasAllQuestsWithStatus(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.HasAllQuestsWithStatus ...

function game.HasAnyQuestWithStatus(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.HasAnyQuestWithStatus ...

function game.OpenQuestLogScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.OpenQuestLogScreen ...

function game.QuestLogScrollDown(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.QuestLogScrollDown ...

function game.QuestLogScrollUp(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.QuestLogScrollUp ...

function game.QuestLogUpdateVisibility(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.QuestLogUpdateVisibility ...

function game.ShowQuestProgress(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.ShowQuestProgress ...

function game.UseQuestLog(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-QuestLogLogic.UseQuestLog ...

return game