---@meta SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation
local game = {}

function game.AddStoreItemPinPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.AddStoreItemPinPresentation ...

function game.FlyTextToUI(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.FlyTextToUI ...

function game.HideMoneyAfterDelay() end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.HideMoneyAfterDelay ...

function game.HideResourceAfterDelay(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.HideResourceAfterDelay ...

function game.InventoryScreenChangeCategoryPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.InventoryScreenChangeCategoryPresentation ...

function game.InventoryScreenClosePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.InventoryScreenClosePresentation ...

function game.InventoryScreenMouseOffPin(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.InventoryScreenMouseOffPin ...

function game.InventoryScreenMouseOverPin(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.InventoryScreenMouseOverPin ...

function game.InventoryScreenOpenPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.InventoryScreenOpenPresentation ...

function game.LootSpawnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.LootSpawnPresentation ...

function game.MoneyGainPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.MoneyGainPresentation ...

function game.MoneyLossPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.MoneyLossPresentation ...

function game.MouseOffResourceItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.MouseOffResourceItem ...

function game.MouseOverResourceItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.MouseOverResourceItem ...

function game.RemoveStoreItemPinPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.RemoveStoreItemPinPresentation ...

function game.ResourceGainNewTotalPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.ResourceGainNewTotalPresentation ...

function game.ResourceGainPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.ResourceGainPresentation ...

function game.ResourceSpendPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.ResourceSpendPresentation ...

function game.RoomRewardPreSpawnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.RoomRewardPreSpawnPresentation ...

function game.RoomRewardSpawnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.RoomRewardSpawnPresentation ...

function game.UnviewedLastResourceGainedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.UnviewedLastResourceGainedPresentation ...

function game.UpdateResourceInteractionText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ResourcePresentation.UpdateResourceInteractionText ...

return game