---@meta game-Scripts-ResourceLogic
local game = {}

function game.AddRerolls(a, b) end
---@alias game-Scripts-ResourceLogic.AddRerolls ...

function game.AddResource(a, b, c, d) end
---@alias game-Scripts-ResourceLogic.AddResource ...

function game.AddResources(a, b) end
---@alias game-Scripts-ResourceLogic.AddResources ...

function game.AddStoreItemPin(a, b) end
---@alias game-Scripts-ResourceLogic.AddStoreItemPin ...

function game.CanOpenInventoryScreen() end
---@alias game-Scripts-ResourceLogic.CanOpenInventoryScreen ...

function game.CloseInventoryScreen(a, b) end
---@alias game-Scripts-ResourceLogic.CloseInventoryScreen ...

function game.GetResourceAmount(a) end
---@alias game-Scripts-ResourceLogic.GetResourceAmount ...

function game.GetResourceCost(a, b) end
---@alias game-Scripts-ResourceLogic.GetResourceCost ...

function game.GiveSelectedGift(a, b) end
---@alias game-Scripts-ResourceLogic.GiveSelectedGift ...

function game.HasPinWithResource(a) end
---@alias game-Scripts-ResourceLogic.HasPinWithResource ...

function game.HasResource(a, b) end
---@alias game-Scripts-ResourceLogic.HasResource ...

function game.HasResourceCost(a) end
---@alias game-Scripts-ResourceLogic.HasResourceCost ...

function game.HasResources(a) end
---@alias game-Scripts-ResourceLogic.HasResources ...

function game.HasStoreItemPin(a) end
---@alias game-Scripts-ResourceLogic.HasStoreItemPin ...

function game.InvenotryScreenRemovePin(a, b) end
---@alias game-Scripts-ResourceLogic.InvenotryScreenRemovePin ...

function game.InventoryScreenDisplayCategory(a, b, c) end
---@alias game-Scripts-ResourceLogic.InventoryScreenDisplayCategory ...

function game.InventoryScreenDisplayLineHistory(a) end
---@alias game-Scripts-ResourceLogic.InventoryScreenDisplayLineHistory ...

function game.InventoryScreenDisplayPins(a) end
---@alias game-Scripts-ResourceLogic.InventoryScreenDisplayPins ...

function game.InventoryScreenHideLineHistory(a) end
---@alias game-Scripts-ResourceLogic.InventoryScreenHideLineHistory ...

function game.InventoryScreenHidePins(a) end
---@alias game-Scripts-ResourceLogic.InventoryScreenHidePins ...

function game.InventoryScreenMoonPhaseButtonMouseOff(a) end
---@alias game-Scripts-ResourceLogic.InventoryScreenMoonPhaseButtonMouseOff ...

function game.InventoryScreenMoonPhaseButtonMouseOver(a) end
---@alias game-Scripts-ResourceLogic.InventoryScreenMoonPhaseButtonMouseOver ...

function game.InventoryScreenNextCategory(a, b) end
---@alias game-Scripts-ResourceLogic.InventoryScreenNextCategory ...

function game.InventoryScreenPrevCategory(a, b) end
---@alias game-Scripts-ResourceLogic.InventoryScreenPrevCategory ...

function game.InventoryScreenScrollDown(a, b) end
---@alias game-Scripts-ResourceLogic.InventoryScreenScrollDown ...

function game.InventoryScreenScrollUp(a, b) end
---@alias game-Scripts-ResourceLogic.InventoryScreenScrollUp ...

function game.InventoryScreenSelectCategory(a, b) end
---@alias game-Scripts-ResourceLogic.InventoryScreenSelectCategory ...

function game.InventoryScreenUpdate(a, b, c) end
---@alias game-Scripts-ResourceLogic.InventoryScreenUpdate ...

function game.InventoryScreenUpdateVisibility(a, b) end
---@alias game-Scripts-ResourceLogic.InventoryScreenUpdateVisibility ...

function game.OnGiftPointsAdded(a, b, c, d) end
---@alias game-Scripts-ResourceLogic.OnGiftPointsAdded ...

function game.OpenInventoryScreen(a) end
---@alias game-Scripts-ResourceLogic.OpenInventoryScreen ...

function game.RemoveStoreItemPin(a, b) end
---@alias game-Scripts-ResourceLogic.RemoveStoreItemPin ...

function game.SpendResource(a, b, c, d) end
---@alias game-Scripts-ResourceLogic.SpendResource ...

function game.SpendResources(a, b, c) end
---@alias game-Scripts-ResourceLogic.SpendResources ...

return game