---@meta game-Scripts-RewardLogic
local game = {}

function game.CalcMetaProgressRatio(a) end
---@alias game-Scripts-RewardLogic.CalcMetaProgressRatio ...

function game.CalcRoomRewardStores(a, b) end
---@alias game-Scripts-RewardLogic.CalcRoomRewardStores ...

function game.ChooseLoot(a, b) end
---@alias game-Scripts-RewardLogic.ChooseLoot ...

function game.ChooseRoomReward(a, b, c, d, e) end
---@alias game-Scripts-RewardLogic.ChooseRoomReward ...

function game.GetEligibleLootNames(a) end
---@alias game-Scripts-RewardLogic.GetEligibleLootNames ...

function game.GetRewardStoreData(a) end
---@alias game-Scripts-RewardLogic.GetRewardStoreData ...

function game.InitClockworkGoalReward(a, b) end
---@alias game-Scripts-RewardLogic.InitClockworkGoalReward ...

function game.InitializeRewardStores(a) end
---@alias game-Scripts-RewardLogic.InitializeRewardStores ...

function game.IsRoomRewardEligible(a, b, c, d, e) end
---@alias game-Scripts-RewardLogic.IsRoomRewardEligible ...

function game.SetupClockworkGoalReward(a, b, c, d, e, f) end
---@alias game-Scripts-RewardLogic.SetupClockworkGoalReward ...

function game.SetupRoomReward(a, b, c, d) end
---@alias game-Scripts-RewardLogic.SetupRoomReward ...

function game.SpawnClockworkGoalReward(a, b, c) end
---@alias game-Scripts-RewardLogic.SpawnClockworkGoalReward ...

function game.SpawnPerfectClearRoomReward(a, b) end
---@alias game-Scripts-RewardLogic.SpawnPerfectClearRoomReward ...

function game.SpawnRoomReward(a, b) end
---@alias game-Scripts-RewardLogic.SpawnRoomReward ...

return game