---@meta SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late
local game = {}

function game.DestroyShipWheelPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.DestroyShipWheelPresentation ...

function game.RoomEntranceCharybdis(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.RoomEntranceCharybdis ...

function game.ExitBiomeGRoomPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ExitBiomeGRoomPresentation ...

function game.LeaveRoomHPostBossPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.LeaveRoomHPostBossPresentation ...

function game.ShipWheelEnd(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShipWheelEnd ...

function game.BiomeOverlookShips(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.BiomeOverlookShips ...

function game.ShipsRoomEntrancePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShipsRoomEntrancePresentation ...

function game.StartFinalBossChronosMusic() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.StartFinalBossChronosMusic ...

function game.FirstUnityBoonPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.FirstUnityBoonPresentation ...

function game.UseShipWheelLeft(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.UseShipWheelLeft ...

function game.BiomeBackToRoomShips(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.BiomeBackToRoomShips ...

function game.AnomalyStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.AnomalyStartPresentation ...

function game.BiomeOverlook(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.BiomeOverlook ...

function game.AttemptUseDoorNemesisTookPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.AttemptUseDoorNemesisTookPresentation ...

function game.NemesisLeaveRoomPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.NemesisLeaveRoomPresentation ...

function game.AnomalyEndPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.AnomalyEndPresentation ...

function game.HubMapViewPresentationStart() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.HubMapViewPresentationStart ...

function game.ScyllaActivatePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ScyllaActivatePresentation ...

function game.StartChronosFakeBossPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.StartChronosFakeBossPresentation ...

function game.GustWindBoss(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.GustWindBoss ...

function game.ShrineUnlockedFirstPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShrineUnlockedFirstPresentation ...

function game.ChaosInteractPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ChaosInteractPresentation ...

function game.HandleNHubWingDimmers(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.HandleNHubWingDimmers ...

function game.EndTinyVerminRadialBlur() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.EndTinyVerminRadialBlur ...

function game.UseShipWheelForward(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.UseShipWheelForward ...

function game.SlightDescent() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.SlightDescent ...

function game.ExitToAnomalyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ExitToAnomalyPresentation ...

function game.BiomeMapPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.BiomeMapPresentation ...

function game.ChronosThronePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ChronosThronePresentation ...

function game.AnomalyExitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.AnomalyExitPresentation ...

function game.BountyBoardReturnPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.BountyBoardReturnPresentationEnd ...

function game.EnterBiomeGRoomPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.EnterBiomeGRoomPresentation ...

function game.LeaveRoomSecretDoorPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.LeaveRoomSecretDoorPresentation ...

function game.LeaveRoomSecretExitDoorPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.LeaveRoomSecretExitDoorPresentation ...

function game.ShipsLeaveRoomPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShipsLeaveRoomPresentation ...

function game.ShipsExitsUnlockedPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShipsExitsUnlockedPresentation ...

function game.NightmareFlickerPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.NightmareFlickerPresentation ...

function game.StartFinalBossChronos(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.StartFinalBossChronos ...

function game.RoomEntranceBossShips(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.RoomEntranceBossShips ...

function game.DoChronosOnHitConversation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.DoChronosOnHitConversation ...

function game.AnomalyEntrancePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.AnomalyEntrancePresentation ...

function game.TrophyQuestUnlockedFirstPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.TrophyQuestUnlockedFirstPresentation ...

function game.BouldyHitPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.BouldyHitPresentation ...

function game.EntranceFromAnomalyPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.EntranceFromAnomalyPresentation ...

function game.ElementalIconsUnlockedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ElementalIconsUnlockedPresentation ...

function game.ChronosExit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ChronosExit ...

function game.FieldsBridgeCharonMusic() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.FieldsBridgeCharonMusic ...

function game.HubMapViewPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.HubMapViewPresentationEnd ...

function game.LeaveRoomHBossPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.LeaveRoomHBossPresentation ...

function game.ShipsSteeringWheelChoicePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShipsSteeringWheelChoicePresentation ...

function game.UseShipWheelRight(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.UseShipWheelRight ...

function game.ShrineReturnPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShrineReturnPresentationEnd ...

function game.FieldsLeaveRoomPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.FieldsLeaveRoomPresentation ...

function game.FieldsRoomEntrancePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.FieldsRoomEntrancePresentation ...

function game.BountyBoardUnlockedFirstPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.BountyBoardUnlockedFirstPresentation ...

function game.ShipsSteeringWheelSelectionPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShipsSteeringWheelSelectionPresentation ...

function game.RoomEntrancePortalFields(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.RoomEntrancePortalFields ...

function game.GustWinds(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.GustWinds ...

function game.RoomEntranceBossFields(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.RoomEntranceBossFields ...

function game.PlayerUseBiomeGDoorPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.PlayerUseBiomeGDoorPresentation ...

function game.FieldsBridgeEchoMusic() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.FieldsBridgeEchoMusic ...

function game.LeaveRoomIPreBossPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.LeaveRoomIPreBossPresentation ...

function game.StartChronosFakeBossMusic(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.StartChronosFakeBossMusic ...

function game.ShipWheelUsedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.ShipWheelUsedPresentation ...

function game.RoomEntranceCrawlerMiniBoss(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.RoomEntranceCrawlerMiniBoss ...

function game.RoomEntranceBossBiomeG(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.RoomEntranceBossBiomeG ...

function game.RoomEntranceChronos(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.RoomEntranceChronos ...

function game.StartFinalBossChronosIntroMusic() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation_Late.StartFinalBossChronosIntroMusic ...

return game