---@meta SGG_Modding-Hades2GameDef-Scripts-RoomPresentation
local game = {}

function game.AltRunDoorReturnPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.AltRunDoorReturnPresentationEnd ...

function game.AltRunDoorUnlockedFirstPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.AltRunDoorUnlockedFirstPresentation ...

function game.AssistHintPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.AssistHintPresentation ...

function game.BiomeBackToRoom(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.BiomeBackToRoom ...

function game.BiomeTimeCheckpointPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.BiomeTimeCheckpointPresentation ...

function game.BoonInteractPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.BoonInteractPresentation ...

function game.CannotRerollPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.CannotRerollPresentation ...

function game.CloseSpellScreenPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.CloseSpellScreenPresentation ...

function game.CloseTalentScreenPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.CloseTalentScreenPresentation ...

function game.ConsumableUsedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ConsumableUsedPresentation ...

function game.DeathEscapeVFX(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.DeathEscapeVFX ...

function game.DeathPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.DeathPresentation ...

function game.DelayedRemoveInputBlock(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.DelayedRemoveInputBlock ...

function game.DestroyDoorRewardPresenation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.DestroyDoorRewardPresenation ...

function game.DoomAppearancePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.DoomAppearancePresentation ...

function game.DoorEntranceAnimation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.DoorEntranceAnimation ...

function game.EasyModeDisabledPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.EasyModeDisabledPresentation ...

function game.EasyModeEnabledPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.EasyModeEnabledPresentation ...

function game.EasyModeLevelUpPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.EasyModeLevelUpPresentation ...

function game.EncounterCostDoorUsedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.EncounterCostDoorUsedPresentation ...

function game.EndEarlyAccessPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.EndEarlyAccessPresentation ...

function game.EndOverlookAdvanced(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.EndOverlookAdvanced ...

function game.ExitDoorUnlockedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ExitDoorUnlockedPresentation ...

function game.FadeBackgroundForestIn() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FadeBackgroundForestIn ...

function game.FadeBackgroundForestOut() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FadeBackgroundForestOut ...

function game.FamilyPortraitUsabilityToggle(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FamilyPortraitUsabilityToggle ...

function game.FastEnterPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FastEnterPresentation ...

function game.FastExitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FastExitPresentation ...

function game.FishingPointAvailablePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FishingPointAvailablePresentation ...

function game.FountainDamagePresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FountainDamagePresentation ...

function game.FullScreenFadeInAnimation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FullScreenFadeInAnimation ...

function game.FullScreenFadeInAnimationReroll(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FullScreenFadeInAnimationReroll ...

function game.FullScreenFadeOutAnimation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FullScreenFadeOutAnimation ...

function game.FullScreenFadeOutAnimationReroll(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.FullScreenFadeOutAnimationReroll ...

function game.GameplayTimerDisabledPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.GameplayTimerDisabledPresentation ...

function game.GameplayTimerEnabledPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.GameplayTimerEnabledPresentation ...

function game.GatherRoomPresentationObjects(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.GatherRoomPresentationObjects ...

function game.GetDefaultClampIds() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.GetDefaultClampIds ...

function game.HandleWeaponAspectsRevealObjective() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.HandleWeaponAspectsRevealObjective ...

function game.HarvestPointAvailablePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.HarvestPointAvailablePresentation ...

function game.HecateExit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.HecateExit ...

function game.HeroAlphaDelay(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.HeroAlphaDelay ...

function game.HubCombatRoomEntrance(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.HubCombatRoomEntrance ...

function game.KillCritter(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.KillCritter ...

function game.LeaveRoomAudio(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.LeaveRoomAudio ...

function game.LeaveRoomPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.LeaveRoomPresentation ...

function game.LeaveRoomStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.LeaveRoomStartPresentation ...

function game.LegendaryAspectPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.LegendaryAspectPresentation ...

function game.LockExtraExitsPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.LockExtraExitsPresentation ...

function game.ManaFountainUsedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ManaFountainUsedPresentation ...

function game.ManaUpgradeInteractPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ManaUpgradeInteractPresentation ...

function game.MaxHealthIncreaseText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.MaxHealthIncreaseText ...

function game.MoneyDropPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.MoneyDropPresentation ...

function game.MoveHeroAlongPath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.MoveHeroAlongPath ...

function game.MoveHeroToRoomPosition(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.MoveHeroToRoomPosition ...

function game.NPCTeleportToExit(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.NPCTeleportToExit ...

function game.OpenSpellScreenPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.OpenSpellScreenPresentation ...

function game.OverlookAdvanced(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.OverlookAdvanced ...

function game.OverlookFlourish() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.OverlookFlourish ...

function game.PassiveGoldGainPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.PassiveGoldGainPresentation ...

function game.PostRerollPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.PostRerollPresentation ...

function game.PreRerollPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.PreRerollPresentation ...

function game.ReattachCameraOnInput(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ReattachCameraOnInput ...

function game.RemoveScreenEdgeIndicator(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RemoveScreenEdgeIndicator ...

function game.RemoveScreenEdgeIndicators() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RemoveScreenEdgeIndicators ...

function game.RestoreUnlockRoomExitsPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RestoreUnlockRoomExitsPresentation ...

function game.RoomEntranceBoss(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RoomEntranceBoss ...

function game.RoomEntranceDrop(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RoomEntranceDrop ...

function game.RoomEntranceMaterialize(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RoomEntranceMaterialize ...

function game.RoomEntrancePortal(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RoomEntrancePortal ...

function game.RoomEntranceStandard(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RoomEntranceStandard ...

function game.RoomOpeningUIDelay() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.RoomOpeningUIDelay ...

function game.ScreenEdgeIndicatorSpawnPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ScreenEdgeIndicatorSpawnPresentation ...

function game.SendCritters(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.SendCritters ...

function game.SetupArachneTheme() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.SetupArachneTheme ...

function game.ShowFullScreenImage(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ShowFullScreenImage ...

function game.ShrinePointDoorUsedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ShrinePointDoorUsedPresentation ...

function game.SpellDropInteractPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.SpellDropInteractPresentation ...

function game.SpellDropInteractPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.SpellDropInteractPresentationEnd ...

function game.StartDevotionTestPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.StartDevotionTestPresentation ...

function game.StartRoomMusic(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.StartRoomMusic ...

function game.StartRoomPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.StartRoomPresentation ...

function game.StopMiniBossMusic(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.StopMiniBossMusic ...

function game.StorePurchasePresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.StorePurchasePresentation ...

function game.TrophyQuestReturnPresentationEnd() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.TrophyQuestReturnPresentationEnd ...

function game.UpgradeAcquiredPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.UpgradeAcquiredPresentation ...

function game.ViewPortraitPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.ViewPortraitPresentation ...

function game.WaitForEndOverlookAdvancedInput(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RoomPresentation.WaitForEndOverlookAdvancedInput ...

return game