---@meta SGG_Modding-Hades2GameDef-Scripts-RunLogic
local game = {}

function game.AddTimerBlock(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.AddTimerBlock ...

function game.AddToSpawnTable(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.AddToSpawnTable ...

function game.BuildMetaupgradeCache() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.BuildMetaupgradeCache ...

function game.CalculateEnemyDifficultyRating(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CalculateEnemyDifficultyRating ...

function game.CalculateStartingMoney() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CalculateStartingMoney ...

function game.CheckPreviousReward(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CheckPreviousReward ...

function game.CheckReloadEncounters(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CheckReloadEncounters ...

function game.CheckSetupFunction(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CheckSetupFunction ...

function game.ChooseChallengeEncounter(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.ChooseChallengeEncounter ...

function game.ChooseEncounter(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.ChooseEncounter ...

function game.ChooseNextRoomData(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.ChooseNextRoomData ...

function game.ChooseStartingRoom(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.ChooseStartingRoom ...

function game.CloseDoorForRun(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CloseDoorForRun ...

function game.CreateNewHero(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CreateNewHero ...

function game.CreateRoom(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.CreateRoom ...

function game.DidFailRun(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.DidFailRun ...

function game.EndBiomeRecords(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.EndBiomeRecords ...

function game.EndRun(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.EndRun ...

function game.FillEnemyCounts(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.FillEnemyCounts ...

function game.FillEnemyTypes(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.FillEnemyTypes ...

function game.GameStateInit() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GameStateInit ...

function game.GenerateEncounter(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GenerateEncounter ...

function game.GetBiomeDepth(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetBiomeDepth ...

function game.GetCompletedRuns() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetCompletedRuns ...

function game.GetEligibleInteractedGod(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetEligibleInteractedGod ...

function game.GetEligibleInteractedGods(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetEligibleInteractedGods ...

function game.GetEligibleMeleeWeapons() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetEligibleMeleeWeapons ...

function game.GetInteractedGods(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetInteractedGods ...

function game.GetInteractedGodsThisRun(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetInteractedGodsThisRun ...

function game.GetInteractedGodThisRun(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetInteractedGodThisRun ...

function game.GetNumMetaUpgrades(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetNumMetaUpgrades ...

function game.GetPreviousRoom(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetPreviousRoom ...

function game.GetRunDepth(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetRunDepth ...

function game.GetTotalAccumulatedMetaPoints() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetTotalAccumulatedMetaPoints ...

function game.GetTotalSpentMetaPoints() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.GetTotalSpentMetaPoints ...

function game.HandleSubRoomData(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HandleSubRoomData ...

function game.HandleSubRoomReturnData(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HandleSubRoomReturnData ...

function game.HasEncounterBeenCompleted(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasEncounterBeenCompleted ...

function game.HasEncounterOccurred(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasEncounterOccurred ...

function game.HasSeenEncounter(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasSeenEncounter ...

function game.HasSeenRoom(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasSeenRoom ...

function game.HasSeenRoomEarlierInRun(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasSeenRoomEarlierInRun ...

function game.HasSeenRoomInNumRuns(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasSeenRoomInNumRuns ...

function game.HasSeenRoomInRun(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasSeenRoomInRun ...

function game.HasSetupFunction(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasSetupFunction ...

function game.HasTimerBlock(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.HasTimerBlock ...

function game.InitHeroLastStands(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.InitHeroLastStands ...

function game.InvalidateCheckpoint() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.InvalidateCheckpoint ...

function game.IsDoorClosedForRun(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsDoorClosedForRun ...

function game.IsEncounterEligible(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsEncounterEligible ...

function game.IsEncounterForced(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsEncounterForced ...

function game.IsEnemyEligible(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsEnemyEligible ...

function game.IsInspectPointEligible(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsInspectPointEligible ...

function game.IsRoomEligible(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsRoomEligible ...

function game.IsRoomForced(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsRoomForced ...

function game.IsSameMode(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsSameMode ...

function game.IsTraitEligible(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsTraitEligible ...

function game.IsWeaponEligible(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.IsWeaponEligible ...

function game.RandomizeObject(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.RandomizeObject ...

function game.ReachedMaxGods(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.ReachedMaxGods ...

function game.RecordRunCleared() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.RecordRunCleared ...

function game.RecordRunStats() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.RecordRunStats ...

function game.RemoveTimerBlock(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.RemoveTimerBlock ...

function game.RequestSave(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.RequestSave ...

function game.RunStateInit() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.RunStateInit ...

function game.SelectBannedEliteAttributes(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.SelectBannedEliteAttributes ...

function game.SetupEncounter(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.SetupEncounter ...

function game.SetupObstacle(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.SetupObstacle ...

function game.StartNewGame(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.StartNewGame ...

function game.StartNewRun(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.StartNewRun ...

function game.UpdateConfigOptionCache() end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.UpdateConfigOptionCache ...

function game.UpdateRunHistoryCache(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.UpdateRunHistoryCache ...

function game.UpdateTimers(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.UpdateTimers ...

function game.UpdateWeaponHistory(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-RunLogic.UpdateWeaponHistory ...

return game