---@meta SGG_Modding-Hades2GameDef-Scripts-ShrineLogic
local game = {}

function game.PickEliteAttributes(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.PickEliteAttributes ...

function game.CloseShrineUpgradeScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.CloseShrineUpgradeScreen ...

function game.ShrineLogicResetAll(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ShrineLogicResetAll ...

function game.DisableBiomeSpeedShrineUpgrade(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.DisableBiomeSpeedShrineUpgrade ...

function game.CheckPrevTraitsManaReserveShrineUpgrade(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.CheckPrevTraitsManaReserveShrineUpgrade ...

function game.ErisCurseUpdate(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ErisCurseUpdate ...

function game.RespawnEggCountdown(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.RespawnEggCountdown ...

function game.ShrineEliteAttributeManaDrain(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ShrineEliteAttributeManaDrain ...

function game.IsEliteAttributeEligible(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.IsEliteAttributeEligible ...

function game.RespawnEggPickedUp(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.RespawnEggPickedUp ...

function game.OpenShrineScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.OpenShrineScreen ...

function game.ErisCurseEnemySetup(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ErisCurseEnemySetup ...

function game.CheckNewTraitManaReserveShrineUpgrade(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.CheckNewTraitManaReserveShrineUpgrade ...

function game.ApplyErisCurse(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ApplyErisCurse ...

function game.GetMaxShrinePoints() end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.GetMaxShrinePoints ...

function game.ApplyEliteAttribute(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ApplyEliteAttribute ...

function game.GetNumShrineUpgrades(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.GetNumShrineUpgrades ...

function game.SpawnErisForCurse(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.SpawnErisForCurse ...

function game.GetTotalSpentShrinePoints() end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.GetTotalSpentShrinePoints ...

function game.ShrineScreenRankDown(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ShrineScreenRankDown ...

function game.CheckBoonSkipShrineUpgrade(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.CheckBoonSkipShrineUpgrade ...

function game.CheckEggRespawn(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.CheckEggRespawn ...

function game.ShrineScreenRankUp(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ShrineScreenRankUp ...

function game.ShrineUpgradeExtractValues(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ShrineUpgradeExtractValues ...

function game.GetShrineUpgradeChangeValue(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.GetShrineUpgradeChangeValue ...

function game.ShrineEliteAttributeHitStun(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.ShrineEliteAttributeHitStun ...

function game.UseShrineObject(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrineLogic.UseShrineObject ...

return game