---@meta SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation
local game = {}

function game.ShrineScreenAlreadyAtMinPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenAlreadyAtMinPresentation ...

function game.SkellyStatueAdmire(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.SkellyStatueAdmire ...

function game.FirstDamageShrineUpgradePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.FirstDamageShrineUpgradePresentation ...

function game.BoonSkipShrineUpgradePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.BoonSkipShrineUpgradePresentation ...

function game.RespawnEggPickedUpPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.RespawnEggPickedUpPresentation ...

function game.StatueHitPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.StatueHitPresentation ...

function game.ShrineScreenMouseOverItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenMouseOverItem ...

function game.ShrinePointRefundPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrinePointRefundPresentation ...

function game.SkellyStatueUnveil(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.SkellyStatueUnveil ...

function game.ShrineScreenRankUpPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenRankUpPresentation ...

function game.ShrineScreenRankDownPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenRankDownPresentation ...

function game.ShrineScreenUpdateNextRankText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenUpdateNextRankText ...

function game.RespawnEggCountdownTickPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.RespawnEggCountdownTickPresentation ...

function game.ShrineScreenUpdateRankActions(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenUpdateRankActions ...

function game.ShrineScreenUpdateActivePoints(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenUpdateActivePoints ...

function game.ErisCurseAppliedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ErisCurseAppliedPresentation ...

function game.ShrineScreenAlreadyAtMaxPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenAlreadyAtMaxPresentation ...

function game.ShrineScreenUpdateItems(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenUpdateItems ...

function game.ShrineEliteAttributeManaDrainTickPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineEliteAttributeManaDrainTickPresentation ...

function game.BanUnpickedBoonPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.BanUnpickedBoonPresentation ...

function game.ShrineScreenMouseOffItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrineScreenMouseOffItem ...

function game.RespawnEggRespawnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.RespawnEggRespawnPresentation ...

function game.BountyReadyConfirmPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.BountyReadyConfirmPresentation ...

function game.UpdateShrineRunDoorArrow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.UpdateShrineRunDoorArrow ...

function game.StatueUnlockedPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.StatueUnlockedPresentation ...

function game.ErisTakeOff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ErisTakeOff ...

function game.BoonManaReserveShrineUpgradePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.BoonManaReserveShrineUpgradePresentation ...

function game.ShrinePointSpendPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-ShrinePresentation.ShrinePointSpendPresentation ...

return game