---@meta SGG_Modding-Hades2GameDef-Scripts-SpellPresentation
local game = {}

function game.CheckSpellOutOfManaPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.CheckSpellOutOfManaPresentation ...

function game.CreateSpellHUD(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.CreateSpellHUD ...

function game.SelectSpellPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SelectSpellPresentation ...

function game.SpellActivateTrait(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellActivateTrait ...

function game.SpellChargeEndPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellChargeEndPresentation ...

function game.SpellChargeNumber(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellChargeNumber ...

function game.SpellChargePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellChargePresentation ...

function game.SpellFailToFirePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellFailToFirePresentation ...

function game.SpellHasManaPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellHasManaPresentation ...

function game.SpellHasNoManaPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellHasNoManaPresentation ...

function game.SpellHintPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellHintPresentation ...

function game.SpellMeteorPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellMeteorPresentation ...

function game.SpellMeteorPresentationThreaded(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellMeteorPresentationThreaded ...

function game.SpellPolymorphResistedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellPolymorphResistedPresentation ...

function game.SpellPotionUsedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellPotionUsedPresentation ...

function game.SpellReadyPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellReadyPresentation ...

function game.SpellReloadPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellReloadPresentation ...

function game.SpellSummonPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellSummonPresentation ...

function game.SpellTransformEndPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellTransformEndPresentation ...

function game.SpellTransformStartPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellTransformStartPresentation ...

function game.SpellTransformWarnPresentation() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellTransformWarnPresentation ...

function game.SpellUnreadyPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.SpellUnreadyPresentation ...

function game.TeleportSummonPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellPresentation.TeleportSummonPresentation ...

return game