---@meta SGG_Modding-Hades2GameDef-Scripts-SpellLogic
local game = {}

function game.AddTransformAttackSpeed(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.AddTransformAttackSpeed ...

function game.ApplyLeapSprint(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.ApplyLeapSprint ...

function game.ApplySelfBuff(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.ApplySelfBuff ...

function game.CanChargeSpell() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.CanChargeSpell ...

function game.ChargeSpell(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.ChargeSpell ...

function game.CheckPolymorphApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.CheckPolymorphApply ...

function game.CheckPolymorphDeathExplosion(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.CheckPolymorphDeathExplosion ...

function game.CheckSpellMultiuse(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.CheckSpellMultiuse ...

function game.CreatePolymorphHealItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.CreatePolymorphHealItem ...

function game.CreateTalentTree(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.CreateTalentTree ...

function game.DetonateSummon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.DetonateSummon ...

function game.DisableCastArm() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.DisableCastArm ...

function game.DoSpellDrain(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.DoSpellDrain ...

function game.EnableCastArm() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EnableCastArm ...

function game.EndCooldownBuff() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EndCooldownBuff ...

function game.EndSpellDrain(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EndSpellDrain ...

function game.EndSpellSummon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EndSpellSummon ...

function game.EndSpellTransform() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EndSpellTransform ...

function game.EndTimeSlow(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EndTimeSlow ...

function game.EndTimeSlowCrit() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EndTimeSlowCrit ...

function game.EndTimeSlowSpeed() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.EndTimeSlowSpeed ...

function game.FireSummonDeathWeapon(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.FireSummonDeathWeapon ...

function game.ForceLaserFacing() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.ForceLaserFacing ...

function game.GetManaSpendCost(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.GetManaSpendCost ...

function game.GetTalentRarity(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.GetTalentRarity ...

function game.GrantPotionBonusCharges(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.GrantPotionBonusCharges ...

function game.LaserHoldClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.LaserHoldClear ...

function game.LaserMatchDuration(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.LaserMatchDuration ...

function game.LaserSpellFire(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.LaserSpellFire ...

function game.LaserSpellForceRelease(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.LaserSpellForceRelease ...

function game.LaserSpellReload(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.LaserSpellReload ...

function game.LeapEnableBlink(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.LeapEnableBlink ...

function game.LeapSimSlow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.LeapSimSlow ...

function game.MeteorCheckInvulnerability(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.MeteorCheckInvulnerability ...

function game.MeteorExCast(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.MeteorExCast ...

function game.MeteorFirePreattack(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.MeteorFirePreattack ...

function game.MeteorPreattackThread(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.MeteorPreattackThread ...

function game.MeteorResetVulnerability(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.MeteorResetVulnerability ...

function game.MeteorStartVulnerability(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.MeteorStartVulnerability ...

function game.MeteorVulnerabilityThread(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.MeteorVulnerabilityThread ...

function game.PolymorphCastTeleport(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.PolymorphCastTeleport ...

function game.PolymorphCopyStatus(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.PolymorphCopyStatus ...

function game.PolymorphManaRegen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.PolymorphManaRegen ...

function game.PolymorphManaRegenSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.PolymorphManaRegenSetup ...

function game.PolymorphStunApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.PolymorphStunApply ...

function game.PolymorphStunClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.PolymorphStunClear ...

function game.RecordDamageInWindow(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.RecordDamageInWindow ...

function game.RecordLastDamaged(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.RecordLastDamaged ...

function game.RecordSpellSummonEnemyDeath(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.RecordSpellSummonEnemyDeath ...

function game.ReleaseDamageInWindow(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.ReleaseDamageInWindow ...

function game.RemoveTransformAttackSpeed(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.RemoveTransformAttackSpeed ...

function game.SelfBuffOutputApply(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SelfBuffOutputApply ...

function game.SelfBuffOutputClear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SelfBuffOutputClear ...

function game.SetupSpellLeap(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SetupSpellLeap ...

function game.SorceryChargeSetup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SorceryChargeSetup ...

function game.SpellCheckCharges(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellCheckCharges ...

function game.SpellFire(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellFire ...

function game.SpellHasMana(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellHasMana ...

function game.SpellHasNoMana(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellHasNoMana ...

function game.SpellMultiuseExpire(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellMultiuseExpire ...

function game.SpellPotion(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellPotion ...

function game.SpellPotionCheckCharges(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellPotionCheckCharges ...

function game.SpellReloadStarted(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellReloadStarted ...

function game.SpellSummon(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellSummon ...

function game.SpellSummonCheckCharges(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellSummonCheckCharges ...

function game.SpellTransform(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SpellTransform ...

function game.StartCooldownBuff() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.StartCooldownBuff ...

function game.StartSpellCharge(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.StartSpellCharge ...

function game.StartSpellSlow(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.StartSpellSlow ...

function game.StartTimeSlowCrit(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.StartTimeSlowCrit ...

function game.StartTimeSlowSpeed() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.StartTimeSlowSpeed ...

function game.StartWeaponSpellDrain(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.StartWeaponSpellDrain ...

function game.SummonTakeDamage(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.SummonTakeDamage ...

function game.TeleportSummonsToPlayer(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.TeleportSummonsToPlayer ...

function game.TimeSlowDamageBonus(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.TimeSlowDamageBonus ...

function game.TimeSlowDestroyProjectiles() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.TimeSlowDestroyProjectiles ...

function game.TimeSlowResetBuff() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.TimeSlowResetBuff ...

function game.TransformArmCast() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.TransformArmCast ...

function game.UpdateSpellActiveStatus() end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.UpdateSpellActiveStatus ...

function game.UpdateTalentPointInvestedCache(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-SpellLogic.UpdateTalentPointInvestedCache ...

return game