---@meta SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic
local game = {}

function game.CleanRecentTraitsRecord() end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.CleanRecentTraitsRecord ...

function game.GetTraitIndex(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.GetTraitIndex ...

function game.IsPossibleMetaUpgradeAutoPin(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.IsPossibleMetaUpgradeAutoPin ...

function game.IsPossibleShrineUpgradeAutoPin(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.IsPossibleShrineUpgradeAutoPin ...

function game.IsPossibleTraitAutoPin(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.IsPossibleTraitAutoPin ...

function game.IsShownInHUD(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.IsShownInHUD ...

function game.OpenTraitTrayScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.OpenTraitTrayScreen ...

function game.PinTraitDetails(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.PinTraitDetails ...

function game.RemovePriorityPin(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.RemovePriorityPin ...

function game.SetHighlightedTraitFrame(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.SetHighlightedTraitFrame ...

function game.SetTraitTrayDetails(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.SetTraitTrayDetails ...

function game.ShowTraitTrayScreen(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.ShowTraitTrayScreen ...

function game.TraitTrayCalcPinSpacing(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayCalcPinSpacing ...

function game.TraitTrayDoAutoPins(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayDoAutoPins ...

function game.TraitTrayGetUniqueName(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayGetUniqueName ...

function game.TraitTrayIconButtonMouseOff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayIconButtonMouseOff ...

function game.TraitTrayIconButtonMouseOver(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayIconButtonMouseOver ...

function game.TraitTrayScreenCategoryMouseOff(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenCategoryMouseOff ...

function game.TraitTrayScreenCategoryMouseOver(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenCategoryMouseOver ...

function game.TraitTrayScreenClose(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenClose ...

function game.TraitTrayScreenInfo(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenInfo ...

function game.TraitTrayScreenNextCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenNextCategory ...

function game.TraitTrayScreenPrevCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenPrevCategory ...

function game.TraitTrayScreenRemoveItems(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenRemoveItems ...

function game.TraitTrayScreenSelectCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenSelectCategory ...

function game.TraitTrayScreenSetupTabs(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenSetupTabs ...

function game.TraitTrayScreenShowCategory(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayScreenShowCategory ...

function game.TraitTrayShowMetaUpgrades(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayShowMetaUpgrades ...

function game.TraitTrayShowShrineUpgrades(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayShowShrineUpgrades ...

function game.TraitTrayShowTraits(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayShowTraits ...

function game.TraitTrayUpdatePinLocations(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-TraitTrayLogic.TraitTrayUpdatePinLocations ...

return game