---@meta game-Scripts-UILogic
local game = {}

function game.AddContextualAction(a, b, c) end
---@alias game-Scripts-UILogic.AddContextualAction ...

function game.AddResourceCostDisplay(a, b, c, d) end
---@alias game-Scripts-UILogic.AddResourceCostDisplay ...

function game.AddResourceCostText(a, b, c) end
---@alias game-Scripts-UILogic.AddResourceCostText ...

function game.AltAspectRatioFramesHide() end
---@alias game-Scripts-UILogic.AltAspectRatioFramesHide ...

function game.AltAspectRatioFramesShow() end
---@alias game-Scripts-UILogic.AltAspectRatioFramesShow ...

function game.AreScreensActive(a) end
---@alias game-Scripts-UILogic.AreScreensActive ...

function game.AttachChildrenFromData(a, b, c, d) end
---@alias game-Scripts-UILogic.AttachChildrenFromData ...

function game.BossHealthBarPresentation(a) end
---@alias game-Scripts-UILogic.BossHealthBarPresentation ...

function game.CheckCallLock(a) end
---@alias game-Scripts-UILogic.CheckCallLock ...

function game.CheckInputRepeat(a, b, c) end
---@alias game-Scripts-UILogic.CheckInputRepeat ...

function game.CheckRemoveGroupHealthBar(a) end
---@alias game-Scripts-UILogic.CheckRemoveGroupHealthBar ...

function game.ClearCameraFocusOverride() end
---@alias game-Scripts-UILogic.ClearCameraFocusOverride ...

function game.ClearHealthShroud() end
---@alias game-Scripts-UILogic.ClearHealthShroud ...

function game.CloseScreen(a, b, c) end
---@alias game-Scripts-UILogic.CloseScreen ...

function game.CloseScreenButton(a, b) end
---@alias game-Scripts-UILogic.CloseScreenButton ...

function game.CreateBossHealthBar(a) end
---@alias game-Scripts-UILogic.CreateBossHealthBar ...

function game.CreateComponentFromData(a, b) end
---@alias game-Scripts-UILogic.CreateComponentFromData ...

function game.CreateGroupHealthBar(a) end
---@alias game-Scripts-UILogic.CreateGroupHealthBar ...

function game.CreateHealthShroud() end
---@alias game-Scripts-UILogic.CreateHealthShroud ...

function game.CreateScreenComponent(a) end
---@alias game-Scripts-UILogic.CreateScreenComponent ...

function game.CreateScreenFromData(a, b, c) end
---@alias game-Scripts-UILogic.CreateScreenFromData ...

function game.CreateScreenObstacle(a) end
---@alias game-Scripts-UILogic.CreateScreenObstacle ...

function game.CreateTextBoxWithFormat(a) end
---@alias game-Scripts-UILogic.CreateTextBoxWithFormat ...

function game.CreateTextBoxWithScreenFormat(a, b, c, d) end
---@alias game-Scripts-UILogic.CreateTextBoxWithScreenFormat ...

function game.DeferredUIScripts() end
---@alias game-Scripts-UILogic.DeferredUIScripts ...

function game.DestroyHealthShroud() end
---@alias game-Scripts-UILogic.DestroyHealthShroud ...

function game.DestroyScreenDataComponents(a, b) end
---@alias game-Scripts-UILogic.DestroyScreenDataComponents ...

function game.DisableGamepadCursor(a) end
---@alias game-Scripts-UILogic.DisableGamepadCursor ...

function game.DisableWeapons() end
---@alias game-Scripts-UILogic.DisableWeapons ...

function game.EnableGamepadCursor(a) end
---@alias game-Scripts-UILogic.EnableGamepadCursor ...

function game.FreezePlayerUnit(a, b) end
---@alias game-Scripts-UILogic.FreezePlayerUnit ...

function game.GetAllIds(a) end
---@alias game-Scripts-UILogic.GetAllIds ...

function game.GetComponentByHotkey(a, b) end
---@alias game-Scripts-UILogic.GetComponentByHotkey ...

function game.GetComponentById(a, b) end
---@alias game-Scripts-UILogic.GetComponentById ...

function game.GetLowHealthUIThreshold(a) end
---@alias game-Scripts-UILogic.GetLowHealthUIThreshold ...

function game.GetUseText(a) end
---@alias game-Scripts-UILogic.GetUseText ...

function game.GroupHealthBarPresentation(a) end
---@alias game-Scripts-UILogic.GroupHealthBarPresentation ...

function game.HandleScreenInput(a) end
---@alias game-Scripts-UILogic.HandleScreenInput ...

function game.HandleWASDInput(a) end
---@alias game-Scripts-UILogic.HandleWASDInput ...

function game.HideAllUseButtons() end
---@alias game-Scripts-UILogic.HideAllUseButtons ...

function game.HideUseButton(a, b, c) end
---@alias game-Scripts-UILogic.HideUseButton ...

function game.IsPauseBlocked() end
---@alias game-Scripts-UILogic.IsPauseBlocked ...

function game.IsScreenOpen(a) end
---@alias game-Scripts-UILogic.IsScreenOpen ...

function game.MouseOffContextualAction(a) end
---@alias game-Scripts-UILogic.MouseOffContextualAction ...

function game.MouseOverContextualAction(a) end
---@alias game-Scripts-UILogic.MouseOverContextualAction ...

function game.OnLanguageChanged(a) end
---@alias game-Scripts-UILogic.OnLanguageChanged ...

function game.OnScreenCloseFinished(a, b) end
---@alias game-Scripts-UILogic.OnScreenCloseFinished ...

function game.OnScreenCloseStarted(a, b) end
---@alias game-Scripts-UILogic.OnScreenCloseStarted ...

function game.OnScreenOpened(a, b) end
---@alias game-Scripts-UILogic.OnScreenOpened ...

function game.RefreshUseButton(a, b) end
---@alias game-Scripts-UILogic.RefreshUseButton ...

function game.ReleaseCallLock(a) end
---@alias game-Scripts-UILogic.ReleaseCallLock ...

function game.ScreenResetCursorToStartLocation(a) end
---@alias game-Scripts-UILogic.ScreenResetCursorToStartLocation ...

function game.SetCameraFocusOverride() end
---@alias game-Scripts-UILogic.SetCameraFocusOverride ...

function game.SetGamepadNavigation(a) end
---@alias game-Scripts-UILogic.SetGamepadNavigation ...

function game.ShowAllUseButtons() end
---@alias game-Scripts-UILogic.ShowAllUseButtons ...

function game.ShowRunIntro() end
---@alias game-Scripts-UILogic.ShowRunIntro ...

function game.ShowUseButton(a, b) end
---@alias game-Scripts-UILogic.ShowUseButton ...

function game.UnfreezePlayerUnit(a) end
---@alias game-Scripts-UILogic.UnfreezePlayerUnit ...

function game.UnzeroMouseTether(a) end
---@alias game-Scripts-UILogic.UnzeroMouseTether ...

function game.ZeroMouseTether(a) end
---@alias game-Scripts-UILogic.ZeroMouseTether ...

return game