---@meta SGG_Modding-Hades2GameDef-Scripts-UIPresentation
local game = {}

function game.DelayedScreenObstacle(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.DelayedScreenObstacle ...

function game.DisplayInfoBanner(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.DisplayInfoBanner ...

function game.MouseOverMetaIconTray(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.MouseOverMetaIconTray ...

function game.GenericInfoPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.GenericInfoPresentation ...

function game.FinalMetaUpgradePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.FinalMetaUpgradePresentation ...

function game.TraitTrayHoverOnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.TraitTrayHoverOnPresentation ...

function game.GenericMouseOverPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.GenericMouseOverPresentation ...

function game.MouseOffMetaIconTray(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.MouseOffMetaIconTray ...

function game.GenericScrollPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.GenericScrollPresentation ...

function game.DisplayInfoToast(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.DisplayInfoToast ...

function game.UpdateLockedKeyPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.UpdateLockedKeyPresentation ...

function game.ScreenCantAffordPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.ScreenCantAffordPresentation ...

function game.TraitTrayPinOnPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.TraitTrayPinOnPresentation ...

function game.RunInterstitialPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.RunInterstitialPresentation ...

function game.TraitTrayPinOffPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.TraitTrayPinOffPresentation ...

function game.GenericScreenCloseFinishedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.GenericScreenCloseFinishedPresentation ...

function game.RunClearMessagePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.RunClearMessagePresentation ...

function game.GenericScreenOpenStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.GenericScreenOpenStartPresentation ...

function game.GenericScreenOpenEndPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.GenericScreenOpenEndPresentation ...

function game.UpgradeChoiceScreenOpenStartPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.UpgradeChoiceScreenOpenStartPresentation ...

function game.HUDTraitAddedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.HUDTraitAddedPresentation ...

function game.GenericScreenClosePresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UIPresentation.GenericScreenClosePresentation ...

return game