---@meta SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic
local game = {}

function game.CloseUpgradeChoiceScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.CloseUpgradeChoiceScreen ...

function game.GetRarityValue(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetRarityValue ...

function game.TryUpgradeBoon(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.TryUpgradeBoon ...

function game.MouseOverBoonButton(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.MouseOverBoonButton ...

function game.LogUpgradeChoice(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.LogUpgradeChoice ...

function game.GetUpgradedRarity(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetUpgradedRarity ...

function game.MouseOverBlockedButton(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.MouseOverBlockedButton ...

function game.RerollBoonLoot(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.RerollBoonLoot ...

function game.GetPriorityTraits(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetPriorityTraits ...

function game.UpgradeChoiceRetaliate(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.UpgradeChoiceRetaliate ...

function game.GetEligibleUpgrades(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetEligibleUpgrades ...

function game.GetEligibleWeaponTraits(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetEligibleWeaponTraits ...

function game.UpgradeChoiceScreenCheckRarifyButton(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.UpgradeChoiceScreenCheckRarifyButton ...

function game.MouseOffBoonButton(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.MouseOffBoonButton ...

function game.GetDowngradedRarity(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetDowngradedRarity ...

function game.OpenUpgradeChoiceMenu(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.OpenUpgradeChoiceMenu ...

function game.CreateUpgradeChoiceButton(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.CreateUpgradeChoiceButton ...

function game.GetRarityKey(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetRarityKey ...

function game.GetEligibleTraitUpgrades(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetEligibleTraitUpgrades ...

function game.DestroyBoonLootButtons(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.DestroyBoonLootButtons ...

function game.UpgradeChoiceScreenOpenTraitTray(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.UpgradeChoiceScreenOpenTraitTray ...

function game.HandleUpgradeChoiceSelection(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.HandleUpgradeChoiceSelection ...

function game.GetReplacementTraits(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetReplacementTraits ...

function game.MouseOffBlockedButton(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.MouseOffBlockedButton ...

function game.CreateBoonLootButtons(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.CreateBoonLootButtons ...

function game.GetPriorityDependentTraits(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.GetPriorityDependentTraits ...

function game.UpgradeChoiceScreenCloseTraitTray(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.UpgradeChoiceScreenCloseTraitTray ...

function game.UpgradeMouseOverUpgradeChoice(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UpgradeChoiceLogic.UpgradeMouseOverUpgradeChoice ...

return game