---@meta game-Scripts-UpgradeLogic
local game = {}

function game.AddEnemyUpgrade(a) end
---@alias game-Scripts-UpgradeLogic.AddEnemyUpgrade ...

function game.AddOnDamageWeapons(a, b, c) end
---@alias game-Scripts-UpgradeLogic.AddOnDamageWeapons ...

function game.AddOnDeathWeapon(a, b) end
---@alias game-Scripts-UpgradeLogic.AddOnDeathWeapon ...

function game.AddOnFireWeapons(a, b, c) end
---@alias game-Scripts-UpgradeLogic.AddOnFireWeapons ...

function game.AddOnHitWeapons(a, b) end
---@alias game-Scripts-UpgradeLogic.AddOnHitWeapons ...

function game.ApplyAllTraitWeapons(a) end
---@alias game-Scripts-UpgradeLogic.ApplyAllTraitWeapons ...

function game.ApplyEnemyTrait(a, b, c) end
---@alias game-Scripts-UpgradeLogic.ApplyEnemyTrait ...

function game.ApplyEnemyTraits(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyEnemyTraits ...

function game.ApplyLifePropertyChange(a, b, c) end
---@alias game-Scripts-UpgradeLogic.ApplyLifePropertyChange ...

function game.ApplyMetaModifierHeroUpgrades(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyMetaModifierHeroUpgrades ...

function game.ApplyMetaUpgrade(a, b, c, d) end
---@alias game-Scripts-UpgradeLogic.ApplyMetaUpgrade ...

function game.ApplyMetaUpgrades(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyMetaUpgrades ...

function game.ApplyProjectilePropertyChanges(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyProjectilePropertyChanges ...

function game.ApplyTraitUpgrade(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyTraitUpgrade ...

function game.ApplyUnitPropertyChange(a, b, c, d) end
---@alias game-Scripts-UpgradeLogic.ApplyUnitPropertyChange ...

function game.ApplyUnitPropertyChanges(a, b, c, d) end
---@alias game-Scripts-UpgradeLogic.ApplyUnitPropertyChanges ...

function game.ApplyWeaponPropertyChange(a, b, c, d) end
---@alias game-Scripts-UpgradeLogic.ApplyWeaponPropertyChange ...

function game.ApplyWeaponPropertyChanges(a, b) end
---@alias game-Scripts-UpgradeLogic.ApplyWeaponPropertyChanges ...

function game.DeleteMatchingPropertyChange(a, b) end
---@alias game-Scripts-UpgradeLogic.DeleteMatchingPropertyChange ...

function game.EquipDumbFireWeapons(a, b) end
---@alias game-Scripts-UpgradeLogic.EquipDumbFireWeapons ...

function game.GatherAndEquipWeapons(a) end
---@alias game-Scripts-UpgradeLogic.GatherAndEquipWeapons ...

function game.GetDerivedPropertyChangeValues(a) end
---@alias game-Scripts-UpgradeLogic.GetDerivedPropertyChangeValues ...

function game.GetNumLockedWeapons() end
---@alias game-Scripts-UpgradeLogic.GetNumLockedWeapons ...

function game.GetPropertyOrderingValue(a, b) end
---@alias game-Scripts-UpgradeLogic.GetPropertyOrderingValue ...

function game.GetRandomUnequippedWeapon() end
---@alias game-Scripts-UpgradeLogic.GetRandomUnequippedWeapon ...

function game.GetTraitOrderingValue(a) end
---@alias game-Scripts-UpgradeLogic.GetTraitOrderingValue ...

function game.HandleWeaponAnimSwaps() end
---@alias game-Scripts-UpgradeLogic.HandleWeaponAnimSwaps ...

function game.HasMeleeWeapon(a) end
---@alias game-Scripts-UpgradeLogic.HasMeleeWeapon ...

function game.IsBonusUnusedWeapon(a) end
---@alias game-Scripts-UpgradeLogic.IsBonusUnusedWeapon ...

function game.IsWeaponUnlocked(a) end
---@alias game-Scripts-UpgradeLogic.IsWeaponUnlocked ...

function game.IsWeaponUntouched(a) end
---@alias game-Scripts-UpgradeLogic.IsWeaponUntouched ...

function game.OrderAndApplyPropertyChanges(a) end
---@alias game-Scripts-UpgradeLogic.OrderAndApplyPropertyChanges ...

function game.ProcessHeroTraitChanges(a, b) end
---@alias game-Scripts-UpgradeLogic.ProcessHeroTraitChanges ...

function game.ReapplyWeaponSwitchMetaUpgrades() end
---@alias game-Scripts-UpgradeLogic.ReapplyWeaponSwitchMetaUpgrades ...

function game.RecordTraitPropertyChange(a, b, c) end
---@alias game-Scripts-UpgradeLogic.RecordTraitPropertyChange ...

function game.RemoveEnemyUpgrade(a) end
---@alias game-Scripts-UpgradeLogic.RemoveEnemyUpgrade ...

function game.RemoveOnDamageWeapons(a, b, c) end
---@alias game-Scripts-UpgradeLogic.RemoveOnDamageWeapons ...

function game.RemoveOnDeathWeapons(a) end
---@alias game-Scripts-UpgradeLogic.RemoveOnDeathWeapons ...

function game.RemoveOnFireWeapons(a, b) end
---@alias game-Scripts-UpgradeLogic.RemoveOnFireWeapons ...

function game.RemoveOnHitWeapons(a, b) end
---@alias game-Scripts-UpgradeLogic.RemoveOnHitWeapons ...

function game.RemoveTraitPropertyChange(a, b, c) end
---@alias game-Scripts-UpgradeLogic.RemoveTraitPropertyChange ...

function game.ReorderPropertyChanges(a) end
---@alias game-Scripts-UpgradeLogic.ReorderPropertyChanges ...

function game.TraitOrderingSort(a, b) end
---@alias game-Scripts-UpgradeLogic.TraitOrderingSort ...

return game