---@meta SGG_Modding-Hades2GameDef-Scripts-UtilityLogic
local game = {}

function game.__genOrderedIndex(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.__genOrderedIndex ...

function game.AddTableKeysCheckDupes(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.AddTableKeysCheckDupes ...

function game.AllRumble(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.AllRumble ...

function game.ArrayContains(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ArrayContains ...

function game.CalcAngleDifference(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CalcAngleDifference ...

function game.CalcArcDistance(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CalcArcDistance ...

function game.CalcOffset(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CalcOffset ...

function game.CalcTotalNumEntries(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CalcTotalNumEntries ...

function game.ChangeDrawGroup(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ChangeDrawGroup ...

function game.CheckCooldown(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CheckCooldown ...

function game.CheckCooldownNoTrigger(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CheckCooldownNoTrigger ...

function game.CheckCountInWindow(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CheckCountInWindow ...

function game.Clamp(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.Clamp ...

function game.Clear(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.Clear ...

function game.cmp_multitype(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.cmp_multitype ...

function game.CollapseTable(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CollapseTable ...

function game.CollapseTableAsKeyValuePairs(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CollapseTableAsKeyValuePairs ...

function game.CollapseTableAsOrderedKeyValuePairs(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CollapseTableAsOrderedKeyValuePairs ...

function game.CollapseTableOrdered(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CollapseTableOrdered ...

function game.CollapseTableOrderedByKeys(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CollapseTableOrderedByKeys ...

function game.ColorClamp(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ColorClamp ...

function game.CombineAllValues(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CombineAllValues ...

function game.CombineTables(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CombineTables ...

function game.CombineTablesIPairs(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CombineTablesIPairs ...

function game.CompareGameDataTables(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CompareGameDataTables ...

function game.ConcatTableValues(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ConcatTableValues ...

function game.ConcatTableValuesIPairs(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ConcatTableValuesIPairs ...

function game.Contains(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.Contains ...

function game.ContainsAll(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ContainsAll ...

function game.ContainsAny(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ContainsAny ...

function game.ContainsAnyKey(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ContainsAnyKey ...

function game.CountKeys(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CountKeys ...

function game.CountValues(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.CountValues ...

function game.DebugContains(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.DebugContains ...

function game.DecrementTableValue(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.DecrementTableValue ...

function game.DeepCopyTable(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.DeepCopyTable ...

function game.DeepMergeTables(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.DeepMergeTables ...

function game.FindMatchingPair(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.FindMatchingPair ...

function game.FlashLightBar(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.FlashLightBar ...

function game.FYShuffle(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.FYShuffle ...

function game.GetAllKeys(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetAllKeys ...

function game.GetAllValues(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetAllValues ...

function game.GetAverageDistance(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetAverageDistance ...

function game.GetFirstKey(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetFirstKey ...

function game.GetFirstValue(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetFirstValue ...

function game.GetHighestIndex(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetHighestIndex ...

function game.GetIndex(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetIndex ...

function game.GetKey(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetKey ...

function game.GetMaxDistance(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetMaxDistance ...

function game.GetRandomEligiblePrioritizedItem(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetRandomEligiblePrioritizedItem ...

function game.GetRandomEligibleValueFromWeightedList(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetRandomEligibleValueFromWeightedList ...

function game.GetRandomKey(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetRandomKey ...

function game.GetRandomValue(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetRandomValue ...

function game.GetRandomValueFromWeightedList(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetRandomValueFromWeightedList ...

function game.GetTimerString(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetTimerString ...

function game.GetTimerStringHours(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.GetTimerStringHours ...

function game.HSVtoRGB(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.HSVtoRGB ...

function game.IncrementTableValue(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.IncrementTableValue ...

function game.IsEmpty(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.IsEmpty ...

function game.isint(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.isint ...

function game.Lerp(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.Lerp ...

function game.MergeAllTables(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.MergeAllTables ...

function game.MergeTables(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.MergeTables ...

function game.orderedNext(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.orderedNext ...

function game.orderedPairs(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.orderedPairs ...

function game.OverwriteAndCollapseTable(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.OverwriteAndCollapseTable ...

function game.OverwritePrimitiveTableKeys(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.OverwritePrimitiveTableKeys ...

function game.OverwriteSelf(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.OverwriteSelf ...

function game.OverwriteTableKeys(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.OverwriteTableKeys ...

function game.RandomTableCycle(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RandomTableCycle ...

function game.RemoveAllValues(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveAllValues ...

function game.RemoveFirstIndexValue(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveFirstIndexValue ...

function game.RemoveFirstValue(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveFirstValue ...

function game.RemoveIndexAndCollapse(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveIndexAndCollapse ...

function game.RemoveRandomKey(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveRandomKey ...

function game.RemoveRandomValue(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveRandomValue ...

function game.RemoveValue(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveValue ...

function game.RemoveValueAndCollapse(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveValueAndCollapse ...

function game.RemoveValuesFromTable(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.RemoveValuesFromTable ...

function game.ResetCooldown(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ResetCooldown ...

function game.round(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.round ...

function game.SetPathValue(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.SetPathValue ...

function game.ShallowCopyTable(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ShallowCopyTable ...

function game.stringends(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.stringends ...

function game.StringToJSONLiteral(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.StringToJSONLiteral ...

function game.StripChars(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.StripChars ...

function game.StripForwardSlashes(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.StripForwardSlashes ...

function game.TableLength(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.TableLength ...

function game.TableToJSONString(a, b, c, d, e) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.TableToJSONString ...

function game.TriggerCooldown(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.TriggerCooldown ...

function game.ValidateIds(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ValidateIds ...

function game.ValidateOrderData(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ValidateOrderData ...

function game.ValidateRoomSecretData(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-UtilityLogic.ValidateRoomSecretData ...

return game