---@meta SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation
local game = {}

function game.MouseOffWeaponShopItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.MouseOffWeaponShopItem ...

function game.MouseOverWeaponShopItem(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.MouseOverWeaponShopItem ...

function game.UpdateWeaponShopInteractionText(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.UpdateWeaponShopInteractionText ...

function game.WeaponShopCloseCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopCloseCategory ...

function game.WeaponShopItemPurchasedPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopItemPurchasedPresentation ...

function game.WeaponShopPurchaseNoEquipPresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopPurchaseNoEquipPresentation ...

function game.WeaponShopPurchasePostActivatePresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopPurchasePostActivatePresentation ...

function game.WeaponShopPurchasePreActivatePresentation(a, b, c, d) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopPurchasePreActivatePresentation ...

function game.WeaponShopRevealCategoryPresentation(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopRevealCategoryPresentation ...

function game.WeaponShopScreenCloseFinishedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopScreenCloseFinishedPresentation ...

function game.WeaponShopScreenCloseStartPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopScreenCloseStartPresentation ...

function game.WeaponShopScreenOpenedPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopScreenOpenedPresentation ...

function game.WeaponShopScreenOpenFinishedPresentation(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopScreenOpenFinishedPresentation ...

function game.WeaponShopScreenScrollPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopScreenScrollPresentation ...

function game.WeaponShopScreenSelectCategoryPresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopScreenSelectCategoryPresentation ...

function game.WeaponShopSessionCompletePresentation(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopPresentation.WeaponShopSessionCompletePresentation ...

return game