---@meta SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic
local game = {}

function game.ActivateToolKit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.ActivateToolKit ...

function game.ActivateWeaponKit(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.ActivateWeaponKit ...

function game.AssignWeaponKits(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.AssignWeaponKits ...

function game.AssignToolKits(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.AssignToolKits ...

function game.UpdateWeaponKits(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.UpdateWeaponKits ...

function game.WeaponShopScreenNextCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScreenNextCategory ...

function game.GetWeaponOrToolKit(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.GetWeaponOrToolKit ...

function game.SetWeaponKitUseText(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.SetWeaponKitUseText ...

function game.UseToolKit(a, b, c) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.UseToolKit ...

function game.WeaponShopScrollDown(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScrollDown ...

function game.DoWeaponShopPurchase(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.DoWeaponShopPurchase ...

function game.WeaponShopScreenControlHotSwap(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScreenControlHotSwap ...

function game.UpdateWeaponKitUpgrade(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.UpdateWeaponKitUpgrade ...

function game.CloseWeaponShopScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.CloseWeaponShopScreen ...

function game.WeaponShopScreenDisplayCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScreenDisplayCategory ...

function game.WeaponShopPinItem(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopPinItem ...

function game.UseWeaponShop(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.UseWeaponShop ...

function game.OpenWeaponShopScreen(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.OpenWeaponShopScreen ...

function game.WeaponShopScreenHideItems(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScreenHideItems ...

function game.WeaponShopScrollUp(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScrollUp ...

function game.HandleWeaponShopPurchase(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.HandleWeaponShopPurchase ...

function game.WeaponShopScreenSelectCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScreenSelectCategory ...

function game.WeaponShopScreenPrevCategory(a, b) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopScreenPrevCategory ...

function game.WeaponShopUpdateVisibility(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.WeaponShopUpdateVisibility ...

function game.UpdateToolKits(a) end
---@alias SGG_Modding-Hades2GameDef-Scripts-WeaponShopLogic.UpdateToolKits ...

return game