---@meta SGG_Modding-Hades2GameDef-Engine
local game = {}

game._VERSION = "Lua 5.2"
---@alias SGG_Modding-Hades2GameDef-Engine._VERSION ...

---@class SGG_Modding-Hades2GameDef-Engine*_G

---@type SGG_Modding-Hades2GameDef-Engine*_G
game._G = {}
---@alias SGG_Modding-Hades2GameDef-Engine._G ...

function game._rom_error(...) end
---@alias SGG_Modding-Hades2GameDef-Engine._rom_error ...

function game._rom_tostring(...) end
---@alias SGG_Modding-Hades2GameDef-Engine._rom_tostring ...

function game.Activate(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Activate ...

function game.AddAutoLockTarget(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AddAutoLockTarget ...

function game.AddChild(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AddChild ...

function game.AddEffectBlock(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AddEffectBlock ...

function game.AddInputBlock(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AddInputBlock ...

function game.AddOutline(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AddOutline ...

function game.AddToGroup(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AddToGroup ...

function game.AddWeaponControl(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AddWeaponControl ...

function game.AdjustBrightness(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustBrightness ...

function game.AdjustColorGrading(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustColorGrading ...

function game.AdjustContrast(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustContrast ...

function game.AdjustFrame(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustFrame ...

function game.AdjustFullscreenBloom(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustFullscreenBloom ...

function game.AdjustRadialBlurDistance(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustRadialBlurDistance ...

function game.AdjustRadialBlurStrength(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustRadialBlurStrength ...

function game.AdjustSaturation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustSaturation ...

function game.AdjustSimulationSpeed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustSimulationSpeed ...

function game.AdjustZLocation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustZLocation ...

function game.AdjustZoom(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AdjustZoom ...

function game.AngleTowardTarget(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AngleTowardTarget ...

function game.ApplyEffect(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ApplyEffect ...

function game.ApplyEffectFromWeapon(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ApplyEffectFromWeapon ...

function game.ApplyForce(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ApplyForce ...

function game.ApplyUpwardForce(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ApplyUpwardForce ...

function game.ArmAndDetonateProjectiles(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ArmAndDetonateProjectiles ...

function game.Attach(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Attach ...

function game.AttachLua(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AttachLua ...

function game.AttachProjectiles(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.AttachProjectiles ...

function game.BlockProjectileSpawns(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.BlockProjectileSpawns ...

function game.BlockVfx(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.BlockVfx ...

function game.CanAttack(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CanAttack ...

function game.CancelWeaponFireRequests(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CancelWeaponFireRequests ...

function game.CanMove(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CanMove ...

function game.ClearAudioListener(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ClearAudioListener ...

function game.ClearAutoLock(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ClearAutoLock ...

function game.ClearCameraClamp(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ClearCameraClamp ...

function game.ClearEffect(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ClearEffect ...

function game.ClearGroup(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ClearGroup ...

function game.ClearUseTarget(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ClearUseTarget ...

function game.ColorAnimation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ColorAnimation ...

function game.CreateAnimation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateAnimation ...

function game.CreateAnimations(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateAnimations ...

function game.CreateAnimationsBetween(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateAnimationsBetween ...

function game.CreateCameraWalls(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateCameraWalls ...

function game.CreateFormatContainer(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateFormatContainer ...

function game.CreateGroup(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateGroup ...

function game.CreateMeteringEntry(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateMeteringEntry ...

function game.CreateProjectileFromUnit(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateProjectileFromUnit ...

function game.CreateTextBox(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CreateTextBox ...

function game.CursorSelectInDirection(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.CursorSelectInDirection ...

function game.DebugAssert(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DebugAssert ...

function game.DebugException(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DebugException ...

function game.DebugMessage(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DebugMessage ...

function game.DebugPrint(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DebugPrint ...

function game.Destroy(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Destroy ...

function game.DestroyCameraWalls(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DestroyCameraWalls ...

function game.DestroyMeteringEntry(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DestroyMeteringEntry ...

function game.DestroyTextBox(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DestroyTextBox ...

function game.DetachProjectiles(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DetachProjectiles ...

function game.DisableComponent(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DisableComponent ...

function game.DrawScreenRelative(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DrawScreenRelative ...

function game.DrawWorldRelative(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.DrawWorldRelative ...

function game.EnableComponent(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.EnableComponent ...

function game.EndAllControlSwaps(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.EndAllControlSwaps ...

function game.EndBlinkWeapons(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.EndBlinkWeapons ...

function game.EndRamWeapons(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.EndRamWeapons ...

function game.EquipWeapon(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.EquipWeapon ...

function game.ExitMenu(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ExitMenu ...

function game.ExpireProjectiles(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ExpireProjectiles ...

function game.FadeIn(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.FadeIn ...

function game.FadeObstacleIn(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.FadeObstacleIn ...

function game.FadeOut(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.FadeOut ...

function game.FireWeaponFromUnit(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.FireWeaponFromUnit ...

function game.Flash(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Flash ...

function game.FlipHorizontal(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.FlipHorizontal ...

function game.FlipVertical(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.FlipVertical ...

function game.FocusCamera(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.FocusCamera ...

function game.GetActiveUnitId(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetActiveUnitId ...

function game.GetAmbientLightColor(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAmbientLightColor ...

function game.GetAngle(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAngle ...

function game.GetAngleBetween(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAngleBetween ...

function game.GetAnimationName(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAnimationName ...

function game.GetAttachedIds(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAttachedIds ...

function game.GetAttachedToId(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAttachedToId ...

function game.GetAutoLockId(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAutoLockId ...

function game.GetAvgFps(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetAvgFps ...

function game.GetBaseDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetBaseDataValue ...

function game.GetBloomSettingName(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetBloomSettingName ...

function game.GetCameraZoom(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetCameraZoom ...

function game.GetCharmDuration(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetCharmDuration ...

function game.GetClosest(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetClosest ...

function game.GetClosestIds(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetClosestIds ...

function game.GetClosestInactiveId(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetClosestInactiveId ...

function game.GetClosestUnitOfType(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetClosestUnitOfType ...

function game.GetConfigOptionValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetConfigOptionValue ...

function game.GetCurrentTargetId(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetCurrentTargetId ...

function game.GetCursorWorldLocation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetCursorWorldLocation ...

function game.GetDisplayName(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetDisplayName ...

function game.GetDistance(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetDistance ...

function game.GetEffectDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetEffectDataValue ...

function game.GetEffectTimeRemaining(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetEffectTimeRemaining ...

function game.GetFarthest(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetFarthest ...

function game.GetGroupName(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetGroupName ...

function game.GetGroupWithSubGroups(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetGroupWithSubGroups ...

function game.GetIds(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetIds ...

function game.GetIdsByType(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetIdsByType ...

function game.GetIdsWithSubGroups(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetIdsWithSubGroups ...

function game.GetInactiveIds(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetInactiveIds ...

function game.GetInactiveIdsByType(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetInactiveIdsByType ...

function game.GetInProjectilesBlast(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetInProjectilesBlast ...

function game.GetInteractDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetInteractDataValue ...

function game.GetIntersectingIds(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetIntersectingIds ...

function game.GetLanguage(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetLanguage ...

function game.GetLifeDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetLifeDataValue ...

function game.GetLocation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetLocation ...

function game.GetMapThings(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetMapThings ...

function game.GetMapThingsByType(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetMapThingsByType ...

function game.GetMixingId(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetMixingId ...

function game.GetName(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetName ...

function game.GetNumConnectedControllers(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetNumConnectedControllers ...

function game.GetProjectileDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetProjectileDataValue ...

function game.GetProjectileProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetProjectileProperty ...

function game.GetScrollOffsetFraction(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetScrollOffsetFraction ...

function game.GetSoundCueValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetSoundCueValue ...

function game.GetSpawnedById(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetSpawnedById ...

function game.GetThingDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetThingDataValue ...

function game.GetTime(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetTime ...

function game.GetUnitDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetUnitDataValue ...

function game.GetUnitProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetUnitProperty ...

function game.GetUsername(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetUsername ...

function game.GetUseTargetId(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetUseTargetId ...

function game.GetVelocity(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetVelocity ...

function game.GetWeaponChargeFraction(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetWeaponChargeFraction ...

function game.GetWeaponDataValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetWeaponDataValue ...

function game.GetWeaponEffectiveRange(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetWeaponEffectiveRange ...

function game.GetWeaponProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetWeaponProperty ...

function game.GetZLocation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.GetZLocation ...

function game.Halt(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Halt ...

function game.HaltCamera(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HaltCamera ...

function game.HasDisplayName(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HasDisplayName ...

function game.HasEffect(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HasEffect ...

function game.HasGroup(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HasGroup ...

function game.HasLineOfSight(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HasLineOfSight ...

function game.HasSaveFile(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HasSaveFile ...

function game.HideObstacle(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HideObstacle ...

function game.HideTopMenuScreenTooltips(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.HideTopMenuScreenTooltips ...

function game.IdExists(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IdExists ...

function game.IgnoreGravity(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IgnoreGravity ...

function game.Import(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Import ...

function game.InitObstacle(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.InitObstacle ...

function game.InitUnit(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.InitUnit ...

function game.InsertGroupBehind(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.InsertGroupBehind ...

function game.InsertGroupInFront(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.InsertGroupInFront ...

function game.IsAlive(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsAlive ...

function game.IsCharmed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsCharmed ...

function game.IsControlDown(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsControlDown ...

function game.IsHeadedToward(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsHeadedToward ...

function game.IsHorizontallyFlipped(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsHorizontallyFlipped ...

function game.IsIdle(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsIdle ...

function game.IsImpulsing(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsImpulsing ...

function game.IsInputAllowed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsInputAllowed ...

function game.IsInvulnerable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsInvulnerable ...

function game.IsLocationBlocked(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsLocationBlocked ...

function game.IsLocationValid(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsLocationValid ...

function game.IsMoving(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsMoving ...

function game.IsPS4(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsPS4 ...

function game.IsUntargetable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsUntargetable ...

function game.IsUseable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsUseable ...

function game.IsWithinDistance(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.IsWithinDistance ...

function game.KeyOffSoundCue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.KeyOffSoundCue ...

function game.LoadCheckpoint(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.LoadCheckpoint ...

function game.LoadMapInternal(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.LoadMapInternal ...

function game.LoadPackages(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.LoadPackages ...

function game.LoadVoiceBank(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.LoadVoiceBank ...

function game.LockCamera(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.LockCamera ...

function game.ModifyEffect(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ModifyEffect ...

function game.ModifyFormatContainer(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ModifyFormatContainer ...

function game.ModifySubtitles(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ModifySubtitles ...

function game.ModifyTextBox(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ModifyTextBox ...

function game.Move(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Move ...

function game.MultiplyScale(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.MultiplyScale ...

function game.NotifyNotColliding(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyNotColliding ...

function game.NotifyOnAllDead(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnAllDead ...

function game.NotifyOnAnimationTimeRemaining(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnAnimationTimeRemaining ...

function game.NotifyOnCanAttack(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnCanAttack ...

function game.NotifyOnCollide(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnCollide ...

function game.NotifyOnControlPressed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnControlPressed ...

function game.NotifyOnControlReleased(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnControlReleased ...

function game.NotifyOnEffectExpired(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnEffectExpired ...

function game.NotifyOnFramePassed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnFramePassed ...

function game.NotifyOnInputAllowed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnInputAllowed ...

function game.NotifyOnInteract(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnInteract ...

function game.NotifyOnPlayerInput(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnPlayerInput ...

function game.NotifyOnProjectilesDead(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnProjectilesDead ...

function game.NotifyOnRotationComplete(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnRotationComplete ...

function game.NotifyOnStopped(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnStopped ...

function game.NotifyOnWeaponCharge(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOnWeaponCharge ...

function game.NotifyOutsideDistance(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOutsideDistance ...

function game.NotifyOutsideDistanceAll(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyOutsideDistanceAll ...

function game.NotifyWithinDistance(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyWithinDistance ...

function game.NotifyWithinDistanceAny(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NotifyWithinDistanceAny ...

function game.NumAlive(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.NumAlive ...

function game.ObeyGravity(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ObeyGravity ...

function game.OnActiveUseTarget(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnActiveUseTarget ...

function game.OnActiveUseTargetLost(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnActiveUseTargetLost ...

function game.OnAllegianceFlip(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnAllegianceFlip ...

function game.OnAnyLoad(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnAnyLoad ...

function game.OnAutoUseFailed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnAutoUseFailed ...

function game.OnBlinkFinished(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnBlinkFinished ...

function game.OnCollisionEnd(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnCollisionEnd ...

function game.OnCollisionReaction(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnCollisionReaction ...

function game.OnComeToRest(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnComeToRest ...

function game.OnControlHotSwap(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnControlHotSwap ...

function game.OnControlPressed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnControlPressed ...

function game.OnControlReleased(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnControlReleased ...

function game.OnDodge(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnDodge ...

function game.OnEffectApply(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnEffectApply ...

function game.OnEffectCanceled(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnEffectCanceled ...

function game.OnEffectCleared(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnEffectCleared ...

function game.OnEffectDelayedKnockbackForce(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnEffectDelayedKnockbackForce ...

function game.OnEffectStackDecrease(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnEffectStackDecrease ...

function game.OnFall(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnFall ...

function game.OnFinishedPath(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnFinishedPath ...

function game.OnHit(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnHit ...

function game.OnKeyPressed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnKeyPressed ...

function game.OnMenuClosed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnMenuClosed ...

function game.OnMenuCloseFinished(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnMenuCloseFinished ...

function game.OnMenuOpened(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnMenuOpened ...

function game.OnMouseOff(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnMouseOff ...

function game.OnMouseOver(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnMouseOver ...

function game.OnMovementReaction(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnMovementReaction ...

function game.OnMusicMarker(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnMusicMarker ...

function game.OnObstacleCollision(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnObstacleCollision ...

function game.OnPackageLoaded(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPackageLoaded ...

function game.OnPerfectChargeWindowEntered(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPerfectChargeWindowEntered ...

function game.OnPlayerDistance(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPlayerDistance ...

function game.OnPlayerDistanceAll(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPlayerDistanceAll ...

function game.OnPlayerDistanceAny(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPlayerDistanceAny ...

function game.OnPlayerInput(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPlayerInput ...

function game.OnPlayerMoveStarted(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPlayerMoveStarted ...

function game.OnPlayerMoveStopped(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPlayerMoveStopped ...

function game.OnPreThingCreation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnPreThingCreation ...

function game.OnProjectileArm(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnProjectileArm ...

function game.OnProjectileBlock(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnProjectileBlock ...

function game.OnProjectileCreation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnProjectileCreation ...

function game.OnProjectileDeath(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnProjectileDeath ...

function game.OnProjectileReflect(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnProjectileReflect ...

function game.OnRamWeaponComplete(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnRamWeaponComplete ...

function game.OnSpawn(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnSpawn ...

function game.OnTakeoff(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnTakeoff ...

function game.OnTouchdown(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnTouchdown ...

function game.OnUnitCollision(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnUnitCollision ...

function game.OnUsed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnUsed ...

function game.OnWeaponChargeCanceled(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponChargeCanceled ...

function game.OnWeaponCharging(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponCharging ...

function game.OnWeaponClipEmpty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponClipEmpty ...

function game.OnWeaponEquipped(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponEquipped ...

function game.OnWeaponFailedToFire(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponFailedToFire ...

function game.OnWeaponFired(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponFired ...

function game.OnWeaponTriggerRelease(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponTriggerRelease ...

function game.OnWeaponUnequipped(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OnWeaponUnequipped ...

function game.OpenMenu(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OpenMenu ...

function game.OverrideWeaponFire(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.OverrideWeaponFire ...

function game.PanCamera(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PanCamera ...

function game.PauseGame(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PauseGame ...

function game.PauseSound(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PauseSound ...

function game.PauseSpeech(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PauseSpeech ...

function game.PerfStartCapture(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PerfStartCapture ...

function game.PerfStopCapture(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PerfStopCapture ...

function game.PlayAmbientSound(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PlayAmbientSound ...

function game.PlayPropertyAnimation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PlayPropertyAnimation ...

function game.PlaySound(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PlaySound ...

function game.PlaySpeech(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PlaySpeech ...

function game.PlaySpeechNow(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PlaySpeechNow ...

function game.PreLoadBinks(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PreLoadBinks ...

function game.ProfileZoneEnd(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ProfileZoneEnd ...

function game.ProfileZoneStart(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ProfileZoneStart ...

function game.ProjectileExists(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ProjectileExists ...

function game.PutDownGently(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.PutDownGently ...

function game.RefreshProjectile(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RefreshProjectile ...

function game.RemoveAutoLockTarget(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RemoveAutoLockTarget ...

function game.RemoveEffectBlock(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RemoveEffectBlock ...

function game.RemoveFromGroup(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RemoveFromGroup ...

function game.RemoveInputBlock(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RemoveInputBlock ...

function game.RemoveOutline(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RemoveOutline ...

function game.ResetWeapon(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ResetWeapon ...

function game.ResumeGame(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ResumeGame ...

function game.ResumeSound(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ResumeSound ...

function game.ResumeSpeech(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ResumeSpeech ...

function game.Rumble(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Rumble ...

function game.RunDebugFunction(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RunDebugFunction ...

function game.RunInteractMethod(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RunInteractMethod ...

function game.RunPhysicsMethod(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RunPhysicsMethod ...

function game.RunThingMethod(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RunThingMethod ...

function game.RunWeaponMethod(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.RunWeaponMethod ...

function game.SaveCheckpoint(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SaveCheckpoint ...

function game.SaveProfile(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SaveProfile ...

function game.SendSaveFileEmail(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SendSaveFileEmail ...

function game.SetAlpha(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetAlpha ...

function game.SetAngle(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetAngle ...

function game.SetAnimation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetAnimation ...

function game.SetAnimationFrameTarget(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetAnimationFrameTarget ...

function game.SetAnimationSpeedMultiplier(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetAnimationSpeedMultiplier ...

function game.SetAudioEffectState(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetAudioEffectState ...

function game.SetAudioListener(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetAudioListener ...

function game.SetBlue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetBlue ...

function game.SetCameraClamp(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetCameraClamp ...

function game.SetCameraZoomWeight(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetCameraZoomWeight ...

function game.SetColor(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetColor ...

function game.SetConfigOption(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetConfigOption ...

function game.SetDamageMultiplier(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetDamageMultiplier ...

function game.SetDamageRadiusMultiplier(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetDamageRadiusMultiplier ...

function game.SetEffectProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetEffectProperty ...

function game.SetGoalAngle(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetGoalAngle ...

function game.SetGreen(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetGreen ...

function game.SetGroupVisibility(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetGroupVisibility ...

function game.SetHSV(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetHSV ...

function game.SetInteractProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetInteractProperty ...

function game.SetInvulnerable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetInvulnerable ...

function game.SetLifeProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetLifeProperty ...

function game.SetLightBarColor(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetLightBarColor ...

function game.SetMenuOptions(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetMenuOptions ...

function game.SetMetering(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetMetering ...

function game.SetObstacleProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetObstacleProperty ...

function game.SetParallax(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetParallax ...

function game.SetPitch(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetPitch ...

function game.SetProjectileProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetProjectileProperty ...

function game.SetProjectileScale(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetProjectileScale ...

function game.SetRed(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetRed ...

function game.SetRGB(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetRGB ...

function game.SetRichPresence(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetRichPresence ...

function game.SetScale(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetScale ...

function game.SetScaleX(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetScaleX ...

function game.SetScaleY(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetScaleY ...

function game.SetSoundCueValue(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetSoundCueValue ...

function game.SetSoundPosition(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetSoundPosition ...

function game.SetSoundSource(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetSoundSource ...

function game.SetTargetable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetTargetable ...

function game.SetThingProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetThingProperty ...

function game.SetUnitProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetUnitProperty ...

function game.SetUntargetable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetUntargetable ...

function game.SetVolume(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetVolume ...

function game.SetVulnerable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetVulnerable ...

function game.SetWeaponProperty(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SetWeaponProperty ...

function game.Shake(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Shake ...

function game.ShakeScreen(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ShakeScreen ...

function game.Shift(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Shift ...

function game.SpawnObstacle(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SpawnObstacle ...

function game.SpawnUnit(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SpawnUnit ...

function game.Stop(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Stop ...

function game.StopAmbientSound(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.StopAmbientSound ...

function game.StopAnimation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.StopAnimation ...

function game.StopFlashing(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.StopFlashing ...

function game.StopLoopingAnimation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.StopLoopingAnimation ...

function game.StopSound(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.StopSound ...

function game.StopSpeech(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.StopSpeech ...

function game.StopUnattachedAnimations(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.StopUnattachedAnimations ...

function game.SwapAnimation(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SwapAnimation ...

function game.SwapSound(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SwapSound ...

function game.SwapWeapon(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SwapWeapon ...

function game.SwitchActiveUnit(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SwitchActiveUnit ...

function game.SwitchAllegiance(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.SwitchAllegiance ...

function game.Teleport(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Teleport ...

function game.TeleportCursor(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.TeleportCursor ...

function game.ToggleControl(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ToggleControl ...

function game.ToggleMove(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ToggleMove ...

function game.ToggleUseable(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ToggleUseable ...

function game.Track(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Track ...

function game.Unattach(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Unattach ...

function game.UnblockVfx(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UnblockVfx ...

function game.UnequipWeapon(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UnequipWeapon ...

function game.UnloadPackages(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UnloadPackages ...

function game.UnloadVoiceBanks(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UnloadVoiceBanks ...

function game.UnlockAchievement(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UnlockAchievement ...

function game.UnlockCamera(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UnlockCamera ...

function game.UpdateAttackTarget(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UpdateAttackTarget ...

function game.UpdateSortScore(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UpdateSortScore ...

function game.Use(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.Use ...

function game.UseableOff(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UseableOff ...

function game.UseableOn(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.UseableOn ...

function game.ValidateCheckpoint(...) end
---@alias SGG_Modding-Hades2GameDef-Engine.ValidateCheckpoint ...

return game