---@meta game-engine
local game = {}

game._VERSION = "Lua 5.2"
---@alias game-engine._VERSION ...

---@class game-engine*_G

---@type game-engine*_G
game._G = game
---@alias game-engine._G ...

function game._rom_error(...) end
---@alias game-engine._rom_error ...

function game._rom_tostring(...) end
---@alias game-engine._rom_tostring ...

function game.Activate(...) end
---@alias game-engine.Activate ...

function game.AddAutoLockTarget(...) end
---@alias game-engine.AddAutoLockTarget ...

function game.AddChild(...) end
---@alias game-engine.AddChild ...

function game.AddEffectBlock(...) end
---@alias game-engine.AddEffectBlock ...

function game.AddInputBlock(...) end
---@alias game-engine.AddInputBlock ...

function game.AddOutline(...) end
---@alias game-engine.AddOutline ...

function game.AddToGroup(...) end
---@alias game-engine.AddToGroup ...

function game.AddWeaponControl(...) end
---@alias game-engine.AddWeaponControl ...

function game.AdjustBrightness(...) end
---@alias game-engine.AdjustBrightness ...

function game.AdjustColorGrading(...) end
---@alias game-engine.AdjustColorGrading ...

function game.AdjustContrast(...) end
---@alias game-engine.AdjustContrast ...

function game.AdjustFrame(...) end
---@alias game-engine.AdjustFrame ...

function game.AdjustFullscreenBloom(...) end
---@alias game-engine.AdjustFullscreenBloom ...

function game.AdjustRadialBlurDistance(...) end
---@alias game-engine.AdjustRadialBlurDistance ...

function game.AdjustRadialBlurStrength(...) end
---@alias game-engine.AdjustRadialBlurStrength ...

function game.AdjustSaturation(...) end
---@alias game-engine.AdjustSaturation ...

function game.AdjustSimulationSpeed(...) end
---@alias game-engine.AdjustSimulationSpeed ...

function game.AdjustZLocation(...) end
---@alias game-engine.AdjustZLocation ...

function game.AdjustZoom(...) end
---@alias game-engine.AdjustZoom ...

function game.AngleTowardTarget(...) end
---@alias game-engine.AngleTowardTarget ...

function game.ApplyEffect(...) end
---@alias game-engine.ApplyEffect ...

function game.ApplyEffectFromWeapon(...) end
---@alias game-engine.ApplyEffectFromWeapon ...

function game.ApplyForce(...) end
---@alias game-engine.ApplyForce ...

function game.ApplyUpwardForce(...) end
---@alias game-engine.ApplyUpwardForce ...

function game.ArmAndDetonateProjectiles(...) end
---@alias game-engine.ArmAndDetonateProjectiles ...

function game.Attach(...) end
---@alias game-engine.Attach ...

function game.AttachLua(...) end
---@alias game-engine.AttachLua ...

function game.AttachProjectiles(...) end
---@alias game-engine.AttachProjectiles ...

function game.BlockProjectileSpawns(...) end
---@alias game-engine.BlockProjectileSpawns ...

function game.BlockVfx(...) end
---@alias game-engine.BlockVfx ...

function game.CanAttack(...) end
---@alias game-engine.CanAttack ...

function game.CancelWeaponFireRequests(...) end
---@alias game-engine.CancelWeaponFireRequests ...

function game.CanMove(...) end
---@alias game-engine.CanMove ...

function game.ClearAudioListener(...) end
---@alias game-engine.ClearAudioListener ...

function game.ClearAutoLock(...) end
---@alias game-engine.ClearAutoLock ...

function game.ClearCameraClamp(...) end
---@alias game-engine.ClearCameraClamp ...

function game.ClearEffect(...) end
---@alias game-engine.ClearEffect ...

function game.ClearGroup(...) end
---@alias game-engine.ClearGroup ...

function game.ClearUseTarget(...) end
---@alias game-engine.ClearUseTarget ...

function game.ColorAnimation(...) end
---@alias game-engine.ColorAnimation ...

function game.CreateAnimation(...) end
---@alias game-engine.CreateAnimation ...

function game.CreateAnimations(...) end
---@alias game-engine.CreateAnimations ...

function game.CreateAnimationsBetween(...) end
---@alias game-engine.CreateAnimationsBetween ...

function game.CreateCameraWalls(...) end
---@alias game-engine.CreateCameraWalls ...

function game.CreateFormatContainer(...) end
---@alias game-engine.CreateFormatContainer ...

function game.CreateGroup(...) end
---@alias game-engine.CreateGroup ...

function game.CreateMeteringEntry(...) end
---@alias game-engine.CreateMeteringEntry ...

function game.CreateProjectileFromUnit(...) end
---@alias game-engine.CreateProjectileFromUnit ...

function game.CreateTextBox(...) end
---@alias game-engine.CreateTextBox ...

function game.CursorSelectInDirection(...) end
---@alias game-engine.CursorSelectInDirection ...

function game.DebugAssert(...) end
---@alias game-engine.DebugAssert ...

function game.DebugException(...) end
---@alias game-engine.DebugException ...

function game.DebugMessage(...) end
---@alias game-engine.DebugMessage ...

function game.DebugPrint(...) end
---@alias game-engine.DebugPrint ...

function game.Destroy(...) end
---@alias game-engine.Destroy ...

function game.DestroyCameraWalls(...) end
---@alias game-engine.DestroyCameraWalls ...

function game.DestroyMeteringEntry(...) end
---@alias game-engine.DestroyMeteringEntry ...

function game.DestroyTextBox(...) end
---@alias game-engine.DestroyTextBox ...

function game.DetachProjectiles(...) end
---@alias game-engine.DetachProjectiles ...

function game.DisableComponent(...) end
---@alias game-engine.DisableComponent ...

function game.DrawScreenRelative(...) end
---@alias game-engine.DrawScreenRelative ...

function game.DrawWorldRelative(...) end
---@alias game-engine.DrawWorldRelative ...

function game.EnableComponent(...) end
---@alias game-engine.EnableComponent ...

function game.EndAllControlSwaps(...) end
---@alias game-engine.EndAllControlSwaps ...

function game.EndBlinkWeapons(...) end
---@alias game-engine.EndBlinkWeapons ...

function game.EndRamWeapons(...) end
---@alias game-engine.EndRamWeapons ...

function game.EquipWeapon(...) end
---@alias game-engine.EquipWeapon ...

function game.ExitMenu(...) end
---@alias game-engine.ExitMenu ...

function game.ExpireProjectiles(...) end
---@alias game-engine.ExpireProjectiles ...

function game.FadeIn(...) end
---@alias game-engine.FadeIn ...

function game.FadeObstacleIn(...) end
---@alias game-engine.FadeObstacleIn ...

function game.FadeOut(...) end
---@alias game-engine.FadeOut ...

function game.FireWeaponFromUnit(...) end
---@alias game-engine.FireWeaponFromUnit ...

function game.Flash(...) end
---@alias game-engine.Flash ...

function game.FlipHorizontal(...) end
---@alias game-engine.FlipHorizontal ...

function game.FlipVertical(...) end
---@alias game-engine.FlipVertical ...

function game.FocusCamera(...) end
---@alias game-engine.FocusCamera ...

function game.GetActiveUnitId(...) end
---@alias game-engine.GetActiveUnitId ...

function game.GetAmbientLightColor(...) end
---@alias game-engine.GetAmbientLightColor ...

function game.GetAngle(...) end
---@alias game-engine.GetAngle ...

function game.GetAngleBetween(...) end
---@alias game-engine.GetAngleBetween ...

function game.GetAnimationName(...) end
---@alias game-engine.GetAnimationName ...

function game.GetAttachedIds(...) end
---@alias game-engine.GetAttachedIds ...

function game.GetAttachedToId(...) end
---@alias game-engine.GetAttachedToId ...

function game.GetAutoLockId(...) end
---@alias game-engine.GetAutoLockId ...

function game.GetAvgFps(...) end
---@alias game-engine.GetAvgFps ...

function game.GetBaseDataValue(...) end
---@alias game-engine.GetBaseDataValue ...

function game.GetBloomSettingName(...) end
---@alias game-engine.GetBloomSettingName ...

function game.GetCameraZoom(...) end
---@alias game-engine.GetCameraZoom ...

function game.GetCharmDuration(...) end
---@alias game-engine.GetCharmDuration ...

function game.GetClosest(...) end
---@alias game-engine.GetClosest ...

function game.GetClosestIds(...) end
---@alias game-engine.GetClosestIds ...

function game.GetClosestInactiveId(...) end
---@alias game-engine.GetClosestInactiveId ...

function game.GetClosestUnitOfType(...) end
---@alias game-engine.GetClosestUnitOfType ...

function game.GetConfigOptionValue(...) end
---@alias game-engine.GetConfigOptionValue ...

function game.GetCurrentTargetId(...) end
---@alias game-engine.GetCurrentTargetId ...

function game.GetCursorWorldLocation(...) end
---@alias game-engine.GetCursorWorldLocation ...

function game.GetDisplayName(...) end
---@alias game-engine.GetDisplayName ...

function game.GetDistance(...) end
---@alias game-engine.GetDistance ...

function game.GetEffectDataValue(...) end
---@alias game-engine.GetEffectDataValue ...

function game.GetEffectTimeRemaining(...) end
---@alias game-engine.GetEffectTimeRemaining ...

function game.GetFarthest(...) end
---@alias game-engine.GetFarthest ...

function game.GetGroupName(...) end
---@alias game-engine.GetGroupName ...

function game.GetGroupWithSubGroups(...) end
---@alias game-engine.GetGroupWithSubGroups ...

function game.GetIds(...) end
---@alias game-engine.GetIds ...

function game.GetIdsByType(...) end
---@alias game-engine.GetIdsByType ...

function game.GetIdsWithSubGroups(...) end
---@alias game-engine.GetIdsWithSubGroups ...

function game.GetInactiveIds(...) end
---@alias game-engine.GetInactiveIds ...

function game.GetInactiveIdsByType(...) end
---@alias game-engine.GetInactiveIdsByType ...

function game.GetInProjectilesBlast(...) end
---@alias game-engine.GetInProjectilesBlast ...

function game.GetInteractDataValue(...) end
---@alias game-engine.GetInteractDataValue ...

function game.GetIntersectingIds(...) end
---@alias game-engine.GetIntersectingIds ...

function game.GetLanguage(...) end
---@alias game-engine.GetLanguage ...

function game.GetLifeDataValue(...) end
---@alias game-engine.GetLifeDataValue ...

function game.GetLocation(...) end
---@alias game-engine.GetLocation ...

function game.GetMapThings(...) end
---@alias game-engine.GetMapThings ...

function game.GetMapThingsByType(...) end
---@alias game-engine.GetMapThingsByType ...

function game.GetMixingId(...) end
---@alias game-engine.GetMixingId ...

function game.GetName(...) end
---@alias game-engine.GetName ...

function game.GetNumConnectedControllers(...) end
---@alias game-engine.GetNumConnectedControllers ...

function game.GetProjectileDataValue(...) end
---@alias game-engine.GetProjectileDataValue ...

function game.GetProjectileProperty(...) end
---@alias game-engine.GetProjectileProperty ...

function game.GetScrollOffsetFraction(...) end
---@alias game-engine.GetScrollOffsetFraction ...

function game.GetSoundCueValue(...) end
---@alias game-engine.GetSoundCueValue ...

function game.GetSpawnedById(...) end
---@alias game-engine.GetSpawnedById ...

function game.GetThingDataValue(...) end
---@alias game-engine.GetThingDataValue ...

function game.GetTime(...) end
---@alias game-engine.GetTime ...

function game.GetUnitDataValue(...) end
---@alias game-engine.GetUnitDataValue ...

function game.GetUnitProperty(...) end
---@alias game-engine.GetUnitProperty ...

function game.GetUsername(...) end
---@alias game-engine.GetUsername ...

function game.GetUseTargetId(...) end
---@alias game-engine.GetUseTargetId ...

function game.GetVelocity(...) end
---@alias game-engine.GetVelocity ...

function game.GetWeaponChargeFraction(...) end
---@alias game-engine.GetWeaponChargeFraction ...

function game.GetWeaponDataValue(...) end
---@alias game-engine.GetWeaponDataValue ...

function game.GetWeaponEffectiveRange(...) end
---@alias game-engine.GetWeaponEffectiveRange ...

function game.GetWeaponProperty(...) end
---@alias game-engine.GetWeaponProperty ...

function game.GetZLocation(...) end
---@alias game-engine.GetZLocation ...

function game.Halt(...) end
---@alias game-engine.Halt ...

function game.HaltCamera(...) end
---@alias game-engine.HaltCamera ...

function game.HasDisplayName(...) end
---@alias game-engine.HasDisplayName ...

function game.HasEffect(...) end
---@alias game-engine.HasEffect ...

function game.HasGroup(...) end
---@alias game-engine.HasGroup ...

function game.HasLineOfSight(...) end
---@alias game-engine.HasLineOfSight ...

function game.HasSaveFile(...) end
---@alias game-engine.HasSaveFile ...

function game.HideObstacle(...) end
---@alias game-engine.HideObstacle ...

function game.HideTopMenuScreenTooltips(...) end
---@alias game-engine.HideTopMenuScreenTooltips ...

function game.IdExists(...) end
---@alias game-engine.IdExists ...

function game.IgnoreGravity(...) end
---@alias game-engine.IgnoreGravity ...

function game.Import(...) end
---@alias game-engine.Import ...

function game.InitObstacle(...) end
---@alias game-engine.InitObstacle ...

function game.InitUnit(...) end
---@alias game-engine.InitUnit ...

function game.InsertGroupBehind(...) end
---@alias game-engine.InsertGroupBehind ...

function game.InsertGroupInFront(...) end
---@alias game-engine.InsertGroupInFront ...

function game.IsAlive(...) end
---@alias game-engine.IsAlive ...

function game.IsCharmed(...) end
---@alias game-engine.IsCharmed ...

function game.IsControlDown(...) end
---@alias game-engine.IsControlDown ...

function game.IsHeadedToward(...) end
---@alias game-engine.IsHeadedToward ...

function game.IsHorizontallyFlipped(...) end
---@alias game-engine.IsHorizontallyFlipped ...

function game.IsIdle(...) end
---@alias game-engine.IsIdle ...

function game.IsImpulsing(...) end
---@alias game-engine.IsImpulsing ...

function game.IsInputAllowed(...) end
---@alias game-engine.IsInputAllowed ...

function game.IsInvulnerable(...) end
---@alias game-engine.IsInvulnerable ...

function game.IsLocationBlocked(...) end
---@alias game-engine.IsLocationBlocked ...

function game.IsLocationValid(...) end
---@alias game-engine.IsLocationValid ...

function game.IsMoving(...) end
---@alias game-engine.IsMoving ...

function game.IsPS4(...) end
---@alias game-engine.IsPS4 ...

function game.IsUntargetable(...) end
---@alias game-engine.IsUntargetable ...

function game.IsUseable(...) end
---@alias game-engine.IsUseable ...

function game.IsWithinDistance(...) end
---@alias game-engine.IsWithinDistance ...

function game.KeyOffSoundCue(...) end
---@alias game-engine.KeyOffSoundCue ...

function game.LoadCheckpoint(...) end
---@alias game-engine.LoadCheckpoint ...

function game.LoadMapInternal(...) end
---@alias game-engine.LoadMapInternal ...

function game.LoadPackages(...) end
---@alias game-engine.LoadPackages ...

function game.LoadVoiceBank(...) end
---@alias game-engine.LoadVoiceBank ...

function game.LockCamera(...) end
---@alias game-engine.LockCamera ...

function game.ModifyEffect(...) end
---@alias game-engine.ModifyEffect ...

function game.ModifyFormatContainer(...) end
---@alias game-engine.ModifyFormatContainer ...

function game.ModifySubtitles(...) end
---@alias game-engine.ModifySubtitles ...

function game.ModifyTextBox(...) end
---@alias game-engine.ModifyTextBox ...

function game.Move(...) end
---@alias game-engine.Move ...

function game.MultiplyScale(...) end
---@alias game-engine.MultiplyScale ...

function game.NotifyNotColliding(...) end
---@alias game-engine.NotifyNotColliding ...

function game.NotifyOnAllDead(...) end
---@alias game-engine.NotifyOnAllDead ...

function game.NotifyOnAnimationTimeRemaining(...) end
---@alias game-engine.NotifyOnAnimationTimeRemaining ...

function game.NotifyOnCanAttack(...) end
---@alias game-engine.NotifyOnCanAttack ...

function game.NotifyOnCollide(...) end
---@alias game-engine.NotifyOnCollide ...

function game.NotifyOnControlPressed(...) end
---@alias game-engine.NotifyOnControlPressed ...

function game.NotifyOnControlReleased(...) end
---@alias game-engine.NotifyOnControlReleased ...

function game.NotifyOnEffectExpired(...) end
---@alias game-engine.NotifyOnEffectExpired ...

function game.NotifyOnFramePassed(...) end
---@alias game-engine.NotifyOnFramePassed ...

function game.NotifyOnInputAllowed(...) end
---@alias game-engine.NotifyOnInputAllowed ...

function game.NotifyOnInteract(...) end
---@alias game-engine.NotifyOnInteract ...

function game.NotifyOnPlayerInput(...) end
---@alias game-engine.NotifyOnPlayerInput ...

function game.NotifyOnProjectilesDead(...) end
---@alias game-engine.NotifyOnProjectilesDead ...

function game.NotifyOnRotationComplete(...) end
---@alias game-engine.NotifyOnRotationComplete ...

function game.NotifyOnStopped(...) end
---@alias game-engine.NotifyOnStopped ...

function game.NotifyOnWeaponCharge(...) end
---@alias game-engine.NotifyOnWeaponCharge ...

function game.NotifyOutsideDistance(...) end
---@alias game-engine.NotifyOutsideDistance ...

function game.NotifyOutsideDistanceAll(...) end
---@alias game-engine.NotifyOutsideDistanceAll ...

function game.NotifyWithinDistance(...) end
---@alias game-engine.NotifyWithinDistance ...

function game.NotifyWithinDistanceAny(...) end
---@alias game-engine.NotifyWithinDistanceAny ...

function game.NumAlive(...) end
---@alias game-engine.NumAlive ...

function game.ObeyGravity(...) end
---@alias game-engine.ObeyGravity ...

function game.OnActiveUseTarget(...) end
---@alias game-engine.OnActiveUseTarget ...

function game.OnActiveUseTargetLost(...) end
---@alias game-engine.OnActiveUseTargetLost ...

function game.OnAllegianceFlip(...) end
---@alias game-engine.OnAllegianceFlip ...

function game.OnAnyLoad(...) end
---@alias game-engine.OnAnyLoad ...

function game.OnAutoUseFailed(...) end
---@alias game-engine.OnAutoUseFailed ...

function game.OnBlinkFinished(...) end
---@alias game-engine.OnBlinkFinished ...

function game.OnCollisionEnd(...) end
---@alias game-engine.OnCollisionEnd ...

function game.OnCollisionReaction(...) end
---@alias game-engine.OnCollisionReaction ...

function game.OnComeToRest(...) end
---@alias game-engine.OnComeToRest ...

function game.OnControlHotSwap(...) end
---@alias game-engine.OnControlHotSwap ...

function game.OnControlPressed(...) end
---@alias game-engine.OnControlPressed ...

function game.OnControlReleased(...) end
---@alias game-engine.OnControlReleased ...

function game.OnDodge(...) end
---@alias game-engine.OnDodge ...

function game.OnEffectApply(...) end
---@alias game-engine.OnEffectApply ...

function game.OnEffectCanceled(...) end
---@alias game-engine.OnEffectCanceled ...

function game.OnEffectCleared(...) end
---@alias game-engine.OnEffectCleared ...

function game.OnEffectDelayedKnockbackForce(...) end
---@alias game-engine.OnEffectDelayedKnockbackForce ...

function game.OnEffectStackDecrease(...) end
---@alias game-engine.OnEffectStackDecrease ...

function game.OnFall(...) end
---@alias game-engine.OnFall ...

function game.OnFinishedPath(...) end
---@alias game-engine.OnFinishedPath ...

function game.OnHit(...) end
---@alias game-engine.OnHit ...

function game.OnKeyPressed(...) end
---@alias game-engine.OnKeyPressed ...

function game.OnMenuClosed(...) end
---@alias game-engine.OnMenuClosed ...

function game.OnMenuCloseFinished(...) end
---@alias game-engine.OnMenuCloseFinished ...

function game.OnMenuOpened(...) end
---@alias game-engine.OnMenuOpened ...

function game.OnMouseOff(...) end
---@alias game-engine.OnMouseOff ...

function game.OnMouseOver(...) end
---@alias game-engine.OnMouseOver ...

function game.OnMovementReaction(...) end
---@alias game-engine.OnMovementReaction ...

function game.OnMusicMarker(...) end
---@alias game-engine.OnMusicMarker ...

function game.OnObstacleCollision(...) end
---@alias game-engine.OnObstacleCollision ...

function game.OnPackageLoaded(...) end
---@alias game-engine.OnPackageLoaded ...

function game.OnPerfectChargeWindowEntered(...) end
---@alias game-engine.OnPerfectChargeWindowEntered ...

function game.OnPlayerDistance(...) end
---@alias game-engine.OnPlayerDistance ...

function game.OnPlayerDistanceAll(...) end
---@alias game-engine.OnPlayerDistanceAll ...

function game.OnPlayerDistanceAny(...) end
---@alias game-engine.OnPlayerDistanceAny ...

function game.OnPlayerInput(...) end
---@alias game-engine.OnPlayerInput ...

function game.OnPlayerMoveStarted(...) end
---@alias game-engine.OnPlayerMoveStarted ...

function game.OnPlayerMoveStopped(...) end
---@alias game-engine.OnPlayerMoveStopped ...

function game.OnPreThingCreation(...) end
---@alias game-engine.OnPreThingCreation ...

function game.OnProjectileArm(...) end
---@alias game-engine.OnProjectileArm ...

function game.OnProjectileBlock(...) end
---@alias game-engine.OnProjectileBlock ...

function game.OnProjectileCreation(...) end
---@alias game-engine.OnProjectileCreation ...

function game.OnProjectileDeath(...) end
---@alias game-engine.OnProjectileDeath ...

function game.OnProjectileReflect(...) end
---@alias game-engine.OnProjectileReflect ...

function game.OnRamWeaponComplete(...) end
---@alias game-engine.OnRamWeaponComplete ...

function game.OnSpawn(...) end
---@alias game-engine.OnSpawn ...

function game.OnTakeoff(...) end
---@alias game-engine.OnTakeoff ...

function game.OnTouchdown(...) end
---@alias game-engine.OnTouchdown ...

function game.OnUnitCollision(...) end
---@alias game-engine.OnUnitCollision ...

function game.OnUsed(...) end
---@alias game-engine.OnUsed ...

function game.OnWeaponChargeCanceled(...) end
---@alias game-engine.OnWeaponChargeCanceled ...

function game.OnWeaponCharging(...) end
---@alias game-engine.OnWeaponCharging ...

function game.OnWeaponClipEmpty(...) end
---@alias game-engine.OnWeaponClipEmpty ...

function game.OnWeaponEquipped(...) end
---@alias game-engine.OnWeaponEquipped ...

function game.OnWeaponFailedToFire(...) end
---@alias game-engine.OnWeaponFailedToFire ...

function game.OnWeaponFired(...) end
---@alias game-engine.OnWeaponFired ...

function game.OnWeaponTriggerRelease(...) end
---@alias game-engine.OnWeaponTriggerRelease ...

function game.OnWeaponUnequipped(...) end
---@alias game-engine.OnWeaponUnequipped ...

function game.OpenMenu(...) end
---@alias game-engine.OpenMenu ...

function game.OverrideWeaponFire(...) end
---@alias game-engine.OverrideWeaponFire ...

function game.PanCamera(...) end
---@alias game-engine.PanCamera ...

function game.PauseGame(...) end
---@alias game-engine.PauseGame ...

function game.PauseSound(...) end
---@alias game-engine.PauseSound ...

function game.PauseSpeech(...) end
---@alias game-engine.PauseSpeech ...

function game.PerfStartCapture(...) end
---@alias game-engine.PerfStartCapture ...

function game.PerfStopCapture(...) end
---@alias game-engine.PerfStopCapture ...

function game.PlayAmbientSound(...) end
---@alias game-engine.PlayAmbientSound ...

function game.PlayPropertyAnimation(...) end
---@alias game-engine.PlayPropertyAnimation ...

function game.PlaySound(...) end
---@alias game-engine.PlaySound ...

function game.PlaySpeech(...) end
---@alias game-engine.PlaySpeech ...

function game.PlaySpeechNow(...) end
---@alias game-engine.PlaySpeechNow ...

function game.PreLoadBinks(...) end
---@alias game-engine.PreLoadBinks ...

function game.ProfileZoneEnd(...) end
---@alias game-engine.ProfileZoneEnd ...

function game.ProfileZoneStart(...) end
---@alias game-engine.ProfileZoneStart ...

function game.ProjectileExists(...) end
---@alias game-engine.ProjectileExists ...

function game.PutDownGently(...) end
---@alias game-engine.PutDownGently ...

function game.RefreshProjectile(...) end
---@alias game-engine.RefreshProjectile ...

function game.RemoveAutoLockTarget(...) end
---@alias game-engine.RemoveAutoLockTarget ...

function game.RemoveEffectBlock(...) end
---@alias game-engine.RemoveEffectBlock ...

function game.RemoveFromGroup(...) end
---@alias game-engine.RemoveFromGroup ...

function game.RemoveInputBlock(...) end
---@alias game-engine.RemoveInputBlock ...

function game.RemoveOutline(...) end
---@alias game-engine.RemoveOutline ...

function game.ResetWeapon(...) end
---@alias game-engine.ResetWeapon ...

function game.ResumeGame(...) end
---@alias game-engine.ResumeGame ...

function game.ResumeSound(...) end
---@alias game-engine.ResumeSound ...

function game.ResumeSpeech(...) end
---@alias game-engine.ResumeSpeech ...

function game.Rumble(...) end
---@alias game-engine.Rumble ...

function game.RunDebugFunction(...) end
---@alias game-engine.RunDebugFunction ...

function game.RunInteractMethod(...) end
---@alias game-engine.RunInteractMethod ...

function game.RunPhysicsMethod(...) end
---@alias game-engine.RunPhysicsMethod ...

function game.RunThingMethod(...) end
---@alias game-engine.RunThingMethod ...

function game.RunWeaponMethod(...) end
---@alias game-engine.RunWeaponMethod ...

function game.SaveCheckpoint(...) end
---@alias game-engine.SaveCheckpoint ...

function game.SaveProfile(...) end
---@alias game-engine.SaveProfile ...

function game.SendSaveFileEmail(...) end
---@alias game-engine.SendSaveFileEmail ...

function game.SetAlpha(...) end
---@alias game-engine.SetAlpha ...

function game.SetAngle(...) end
---@alias game-engine.SetAngle ...

function game.SetAnimation(...) end
---@alias game-engine.SetAnimation ...

function game.SetAnimationFrameTarget(...) end
---@alias game-engine.SetAnimationFrameTarget ...

function game.SetAnimationSpeedMultiplier(...) end
---@alias game-engine.SetAnimationSpeedMultiplier ...

function game.SetAudioEffectState(...) end
---@alias game-engine.SetAudioEffectState ...

function game.SetAudioListener(...) end
---@alias game-engine.SetAudioListener ...

function game.SetBlue(...) end
---@alias game-engine.SetBlue ...

function game.SetCameraClamp(...) end
---@alias game-engine.SetCameraClamp ...

function game.SetCameraZoomWeight(...) end
---@alias game-engine.SetCameraZoomWeight ...

function game.SetColor(...) end
---@alias game-engine.SetColor ...

function game.SetConfigOption(...) end
---@alias game-engine.SetConfigOption ...

function game.SetDamageMultiplier(...) end
---@alias game-engine.SetDamageMultiplier ...

function game.SetDamageRadiusMultiplier(...) end
---@alias game-engine.SetDamageRadiusMultiplier ...

function game.SetEffectProperty(...) end
---@alias game-engine.SetEffectProperty ...

function game.SetGoalAngle(...) end
---@alias game-engine.SetGoalAngle ...

function game.SetGreen(...) end
---@alias game-engine.SetGreen ...

function game.SetGroupVisibility(...) end
---@alias game-engine.SetGroupVisibility ...

function game.SetHSV(...) end
---@alias game-engine.SetHSV ...

function game.SetInteractProperty(...) end
---@alias game-engine.SetInteractProperty ...

function game.SetInvulnerable(...) end
---@alias game-engine.SetInvulnerable ...

function game.SetLifeProperty(...) end
---@alias game-engine.SetLifeProperty ...

function game.SetLightBarColor(...) end
---@alias game-engine.SetLightBarColor ...

function game.SetMenuOptions(...) end
---@alias game-engine.SetMenuOptions ...

function game.SetMetering(...) end
---@alias game-engine.SetMetering ...

function game.SetObstacleProperty(...) end
---@alias game-engine.SetObstacleProperty ...

function game.SetParallax(...) end
---@alias game-engine.SetParallax ...

function game.SetPitch(...) end
---@alias game-engine.SetPitch ...

function game.SetProjectileProperty(...) end
---@alias game-engine.SetProjectileProperty ...

function game.SetProjectileScale(...) end
---@alias game-engine.SetProjectileScale ...

function game.SetRed(...) end
---@alias game-engine.SetRed ...

function game.SetRGB(...) end
---@alias game-engine.SetRGB ...

function game.SetRichPresence(...) end
---@alias game-engine.SetRichPresence ...

function game.SetScale(...) end
---@alias game-engine.SetScale ...

function game.SetScaleX(...) end
---@alias game-engine.SetScaleX ...

function game.SetScaleY(...) end
---@alias game-engine.SetScaleY ...

function game.SetSoundCueValue(...) end
---@alias game-engine.SetSoundCueValue ...

function game.SetSoundPosition(...) end
---@alias game-engine.SetSoundPosition ...

function game.SetSoundSource(...) end
---@alias game-engine.SetSoundSource ...

function game.SetTargetable(...) end
---@alias game-engine.SetTargetable ...

function game.SetThingProperty(...) end
---@alias game-engine.SetThingProperty ...

function game.SetUnitProperty(...) end
---@alias game-engine.SetUnitProperty ...

function game.SetUntargetable(...) end
---@alias game-engine.SetUntargetable ...

function game.SetVolume(...) end
---@alias game-engine.SetVolume ...

function game.SetVulnerable(...) end
---@alias game-engine.SetVulnerable ...

function game.SetWeaponProperty(...) end
---@alias game-engine.SetWeaponProperty ...

function game.Shake(...) end
---@alias game-engine.Shake ...

function game.ShakeScreen(...) end
---@alias game-engine.ShakeScreen ...

function game.Shift(...) end
---@alias game-engine.Shift ...

function game.SpawnObstacle(...) end
---@alias game-engine.SpawnObstacle ...

function game.SpawnUnit(...) end
---@alias game-engine.SpawnUnit ...

function game.Stop(...) end
---@alias game-engine.Stop ...

function game.StopAmbientSound(...) end
---@alias game-engine.StopAmbientSound ...

function game.StopAnimation(...) end
---@alias game-engine.StopAnimation ...

function game.StopFlashing(...) end
---@alias game-engine.StopFlashing ...

function game.StopLoopingAnimation(...) end
---@alias game-engine.StopLoopingAnimation ...

function game.StopSound(...) end
---@alias game-engine.StopSound ...

function game.StopSpeech(...) end
---@alias game-engine.StopSpeech ...

function game.StopUnattachedAnimations(...) end
---@alias game-engine.StopUnattachedAnimations ...

function game.SwapAnimation(...) end
---@alias game-engine.SwapAnimation ...

function game.SwapSound(...) end
---@alias game-engine.SwapSound ...

function game.SwapWeapon(...) end
---@alias game-engine.SwapWeapon ...

function game.SwitchActiveUnit(...) end
---@alias game-engine.SwitchActiveUnit ...

function game.SwitchAllegiance(...) end
---@alias game-engine.SwitchAllegiance ...

function game.Teleport(...) end
---@alias game-engine.Teleport ...

function game.TeleportCursor(...) end
---@alias game-engine.TeleportCursor ...

function game.ToggleControl(...) end
---@alias game-engine.ToggleControl ...

function game.ToggleMove(...) end
---@alias game-engine.ToggleMove ...

function game.ToggleUseable(...) end
---@alias game-engine.ToggleUseable ...

function game.Track(...) end
---@alias game-engine.Track ...

function game.Unattach(...) end
---@alias game-engine.Unattach ...

function game.UnblockVfx(...) end
---@alias game-engine.UnblockVfx ...

function game.UnequipWeapon(...) end
---@alias game-engine.UnequipWeapon ...

function game.UnloadPackages(...) end
---@alias game-engine.UnloadPackages ...

function game.UnloadVoiceBanks(...) end
---@alias game-engine.UnloadVoiceBanks ...

function game.UnlockAchievement(...) end
---@alias game-engine.UnlockAchievement ...

function game.UnlockCamera(...) end
---@alias game-engine.UnlockCamera ...

function game.UpdateAttackTarget(...) end
---@alias game-engine.UpdateAttackTarget ...

function game.UpdateSortScore(...) end
---@alias game-engine.UpdateSortScore ...

function game.Use(...) end
---@alias game-engine.Use ...

function game.UseableOff(...) end
---@alias game-engine.UseableOff ...

function game.UseableOn(...) end
---@alias game-engine.UseableOn ...

function game.ValidateCheckpoint(...) end
---@alias game-engine.ValidateCheckpoint ...

return game